### PR TITLE
Factor interface

### PR DESCRIPTION
**Pull request by thofma**
- Introduce some type which holds factorizations.
- Adjust all factor_* functions to return this type.
- Add test code.
- Change factor_shape to return Dict{Int, T} instead of Dict{T, Int}

I am currently building binaries for Win64.

### CODE REVIEW

**Comment by wbhart** [comment]
Looks like the test failures are just because we don't import iszero.

Do you want me to hold off on accepting this until you have the Win64 binaries done?

**Comment by thofma** [comment]
I will wait for the Win64 binaries.

Nightlies are failing because they stopped exporting iszero. I will take care of it in another PR

**Comment by thofma** [comment]
New binaries a here:
www.mathematik.uni-kl.de/~thofmann/build_20170117/w64-libarb.dll
www.mathematik.uni-kl.de/~thofmann/build_20170117/w64-libflint.dll
www.mathematik.uni-kl.de/~thofmann/build_20170117/w64-libgmp-16.dll
www.mathematik.uni-kl.de/~thofmann/build_20170117/w64-libmpfr-4.dll

**Comment by wbhart** [comment]
Do you want me to put them on the website?

**Comment by thofma** [comment]
Yes, that would be nice (but backup the old ones). I tested it locally in a Windows virtual machine. But I would also like to see appveyor pass.

**Comment by wbhart** [comment]
Done.

**Comment by thofma** [comment]
Passing.

**Pull request merged**
