### PR TITLE
Bump flint version

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by wbhart** [comment]
The error message looks ominous, so I won't merge this.

**Comment by thofma** [comment]
Network problem. I have restarted.

**Comment by wbhart** [comment]
Look ok. Is it really necessary to put a separate hash in for each arch we support? That's not going to have to be changed every time is it?

Also when you dev Nemo and then update it later, if the LoadFlint version has changed, it complains and does not update it. You have to do it manually. I hope it won't be necessary to change all these hashes manually every time that happens.

**Comment by thofma** [comment]
I don't understand the comment about the separate hashs. These are the hashs of the tarballs. As the tarballs change for the new flint binaries, the hashs have to be updated. This has to be updated with every flint version, unless we drop support for jula < 1.3.

If you have Nemo dev'ed, and no other thing that depends on LoadFlint in your environment (like Oscar), you can just pull and call update or resolve. I never had to change something manually. The woes with the package manager seem unrelated to this PR here.

**Comment by wbhart** [comment]
That's good to know, thanks.

Regarding the hashes, it might be a good idea for us to eventually write a script which can do that.

**Comment by thofma** [comment]
Thankfully, this is already done by a script, see https://github.com/JuliaPackaging/Yggdrasil#binaryproviderjl :-)

**Comment by wbhart** [comment]
Oh right. That's good news. 👍

**Comment by slel** [comment]
> Thankfully, this is already done by a script, see https://github.com/JuliaPackaging/Yggdrasil#binaryproviderjl :-)

Add a note about that to the development page?

- http://nemocas.org/development.html

**Comment by thofma** [comment]
Not sure this is the right place. It would have to go to the developer documentation, which we don't have.

**Pull request merged**
