### PR TITLE
Test divides of integers where second argument is zero #687.

### LINKED ISSUE #687: divides(a, 0) raises exception for integers a
By definition, b divides a if there exists c such that a = bc. This is a true/false question. There should be no exceptions raised. In particular 0 divides 0 and 0 is a quotient and 0 does not divide any other integer.

### PR DESCRIPTION
**Pull request by wbhart**
This will fail until PR #527 is merged in AbstractAlgebra and a new release is made. It's only test code to ensure the fix works.

Closes #687

### CODE REVIEW

**Comment by thofma** [comment]
Tests are failing.

**Comment by wbhart** [comment]
The tests will not pass here until the binaries are updated.

**Comment by wbhart** [comment]
And until #527 is merged, as mentioned above.

**Comment by thofma** [comment]
And a new release is made.

**Comment by rfourquet** [comment]
> And until #527 is merged, as mentioned above.

https://github.com/Nemocas/AbstractAlgebra.jl/pull/527 is already merged.

**Comment by wbhart** [comment]
Ok to merge?

**Pull request merged**
