### PR TITLE
disable the greeting banner when loaded from Oscar

### PR DESCRIPTION
**Pull request by rfourquet**
This is a hack, hoping that a better solution appears someday. The same can be replicated in other packages (Hecke, Polymake, I can make PR there is requested).

The idea is to look inside the `Base.package_locks` internal dict to see if `Oscar`'s loading has been initiated when `Nemo` is loading. In other words, `Nemo` will load before `Oscar`, but while loading, `Nemo` can know whether `Oscar` is about to be loaded afterwards.

In addition to `Oscar`, we can manually add a check for other packages, e.g. `Hecke`, unfortunately there is no way for packages to "register" into a "no-print-banner hook". So this PR also gives an escape hatch, by checking an environment variable (`"NEMO_PRINT_BANNER"`), which can be set by end-user.

### CODE REVIEW

**Comment by rfourquet** [comment]
While I am at it, I added a check for `isinteractive()`, so that the banner is not printed multiple times when packages depending on it are being precompiled.

**Comment by thofma** [comment]
Amazing!

**Comment by fieker** [comment]
what about a slightly more readable version

show_banner = isinteractive() &&
                 !any(x->x.name in ["Hecke", "Oscar"], keys(Base.package_locks))

**Comment by rfourquet** [comment]
> what about a slightly more readable version

Good idea, will do.

**Pull request merged**
