### PR TITLE
make binomial match julia

### LINKED ISSUE #1210: `binomial(ZZ(-4), ZZ(3)) != binomial(-4, 3)` and this is bad

### PR DESCRIPTION
**Pull request by tthsqe12**
fixes #1210

### CODE REVIEW

**Review by thofma — APPROVED** [review]

**Comment by tthsqe12** [comment]
Some tests are failing, but that is only because the code was also broken before.

**Comment by thofma** [comment]
How does that explain the failure on Windows? Can you elaborate?

**Comment by tthsqe12** [comment]
it's the usual stupid long is 32 bits issue. This is why I added the typemax test.

**Comment by tthsqe12** [comment]
Alright, we don't have binomial anymore. The julia implementation is buggy too.

**Comment by thofma** [comment]
Buggy or are the values too large?

**Comment by tthsqe12** [comment]
Yes, but the answers are small.

**Comment by thofma** [comment]
Will merge this once we think it is time for a new breaking release (this might be soon).

**Comment by tthsqe12** [comment]
Ok, I will fix it completely then.

**Review by tthsqe12 — COMMENTED** [review]
finally good now

**Comment by tthsqe12** [comment]
> Will merge this once we think it is time for a new breaking release (this might be soon).

No need to rush - nemo was fine before, and I don't need these changes any longer.

**Pull request merged**
