### PR TITLE
This is what used to be #3 (aka fieker/newbranch3)

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by wbhart** [comment]
1) The comment  
   
   #actually wrong: it is an array of flint-nmod_poly

is still not correct. In the flint nmod_factor_t struct the field is

   nmod_poly_struct *p;

So the comment should say:

   # actually an array of Flint nmod_poly_struct's

2) The constructor fmpz_mat(r::Int, c::Int, arr::Array{fmpz, 1})
should be implemented for other matrix types in Nemo, including the
generic matrices for consistency reasons.

3) Instead of doing things like:

   const error_dim_non_negative = "Dimensions must be non-negative"

I would prefer that we define our own error objects and throw them,
rather than implementing something ad hoc like this. We should also
use these consistently across Nemo.

Also the name should be dim_negative as it isn't an error to
have a nonnegative dimension.

4) Why does _check_dim have a leading underscore?

5) Why are we defining functions like _hash_integer with a name of
a type in the name, and underscores in the name? This is only needed
in languages that aren't polymorphic, like C.

We should be able to define a function hash() for the given prototype.

Similarly for _fmpz_limbs (there is already such a function),
__fmpz_is_small, __fmpz_limbs and so on.

6) Why was the hash function for fq changed to
b = 0xb310fb6ea97e1f1a%UInt

I don't see what the purpose of the %UInt is.

7) For which types are we supporting zero! and one!? There are too many
arbitrary hacks like this happening. We seem to be converging away from
consistency not towards it!

8) valuation(z::nmod_poly, p::nmod_poly) should at least use divrem
so it doesn't do the same computation twice every iteration.

**Comment by wbhart** [comment]
It would be nice if valuation could be defined more generally for all polynomial rings over a field, including a generic function of this kind.

We still need a special version of the function for nmod_poly since this is not a poly over a field.

**Comment by fieker** [comment]
2: Agreed, but I still would like to make this change and then add more stuff later on, it is an improvement.

3: also agree. However, using at least the const string is ore memory efficient and an improvement over the previous behaviour.  In this case, I am certain, there would be an appropriate Julia Error Object to throw. But as I said: it is a gradual improvement...

The name is designed from the string, not from the usage.

4: I use leading underscores to designate private functions.

5: I am happy to change the name - this entire framework for hashing was copied out of the julia base.
I cannot see any limbs function outside my changes, same with is_small. Possibly one can use a ccall for the same purpose - albeit slower (I assume that those functions are inlined)

6: the %UInt make a difference in 32bit systems. I thought you put it in originally, but I have no opinion on it at all

7: ultimately, zero! and one! should be there for all non-immutables. However, doing this systematically is a lot of work, so I prefer to add them whem needed. Maybe the three of us should schedule a ?? Afternoon, all together in one room, trying to increase consistency across the universe.

8: this is a 1st version of valuation. Anyhting serious need to switch to a logarithmic alorithm, not a linear one. However, currently, the valuations are small - as are the polys.

And yes: this could and should also be done on the level of generic polynomials.

Once this really messy and screwed up request is in, I can actually clean up my repos. The plan is to delete my Nemo stuff and replace it with a fresh clone from Nemocas. This way no hidden pitfalls will remain.

**Comment by wbhart** [comment]
4. Private functions are denoted in Julia by not exporting them. Using leading underscores is not encouraged, though they stopped short of explicitly adding that to the style guide. However, the style guide does now set out when underscores should be used. They adopted the convention that I ended up using:

iszero

but 

flat_module

In other words, squash when readable, otherwise separate with underscores. Not very precise, but it's good enough for a convention.

6. It looks like you are right about requiring %UInt. I was under the impression that hashes were explicitly UInt64's on a 32 bit machine. But I just tried it and it seems I'm wrong.

I don't recall adding it anywhere else though. I guess we should check.

**Comment by wbhart** [comment]
I'm happy to make some of my points tickets instead of requirements for the merge of the patch. I just don't want to get to the point where we have so many arbitrary hacks that we have to change the name of our software to something starting with Sin.

**Comment by thofma** [comment]
There is a considerable amount of functions in Base starting with _. Why shouldn't we do the same for functions a user should never ever see?

The "rule" with the use of "_" and readabilty just means that there is no rule at all. As can be seen at looking at the names in Base, e.g. `this_module` and `thisminor`.

Can you please point out which of the changes here are "arbitary hacks" (except for one! and zero!)?

**Comment by wbhart** [comment]
The style guide for Julia was certainly written after large parts of Base were written. They also have consistency issues and it is my understanding they will work towards fixing this. The conventions they are using seem to be gradually converging over time, and as they reach agreement after changing things, they seem to be updating their style guide.

Of course we don't need to follow it. It just might increase the number of serious Julia coders who contribute down the track. I was just bringing attention to the issue.

There is actually a discussion online about function hiding and one of the core devs suggests that he doesn't like leading underscores and that although he wouldn't prohibit it at this stage, he would prefer "hiding" is done by not exporting functions from the module.

Sorry about the wording "arbitrary hacks". It's perhaps not the best wording. What I mean is introducing new things that aren't rolled out across the whole of Nemo. One of the main features of Nemo is to have a generic system which actually *relies* on things being consistent across the system for the most part. 

Documentation, coding style and so on also benefit from being consistent, both with the Julia codebase where possible and across Nemo. If we ourselves all do things differently across the codebase, other developers will do the same and we'll have many different coding styles, including ones that encourage errors or that are unreadable or that we explicitly don't like. 

Here is a bad example of this:

https://github.com/wbhart/mpir/blob/06d4a329430d3e44675aad5ea1e20972fabbc683/mpn/generic/divrem_euclidean_r_1.c

Anyway, I would say that 1-5, 7 and 8 are all examples of things that either need a convention to be decided or which need rolling out across the whole of Nemo.

My argument was simply that if we introduce more such things with each patch, we aren't converging any more. It's not a problem, I'm just wanting to point it out so we can discuss and agree on how far we want to go with consistency. That depends on our ultimate goals I guess.

**Comment by wbhart** [comment]
Actually, you now find in the Julia docs [1]:

"Names of functions and macros are in lower case, without underscores."

Presumably here they mean leading underscores because in their actual style guide they say underscores in function names are permitted if squashing makes them hard to read.

For example pos_hit instead of poshit.

http://docs.julialang.org/en/release-0.4/manual/variables/

**Comment by wbhart** [comment]
Why don't we agree on the following convention for now. Reviewing code for Nemocas will be like reviewing a paper. The reviewer can reject a patch entirely if it is complete rubbish (this is only going to happen with new contributors who don't know what they are doing), the can suggest corrections, which if the author agrees should be corrected before merging, or the reviewer can suggest stylistic changes which the author can choose to ignore entirely, as commonly happens when reviewing papers.

Ultimately the author is responsible for the code they write, not the reviewer. Does this sound like a good strategy?

**Comment by fieker** [comment]
On Thu, Mar 17, 2016 at 11:38:22AM -0700, wbhart wrote:
> Actually, you now find in the Julia docs [1]:
> 
> "Names of functions and macros are in lower case, without underscores."
> 
> Presumably here they mean leading underscores because in their actual style guide they say underscores in function names are permitted if squashing makes them hard to read.
> 
> For example pos_hit instead of poshit.
> 
> http://docs.julialang.org/en/release-0.4/manual/variables/
> 
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/Nemocas/Nemo.jl/pull/4#issuecomment-198025737

I'm afaraid, this is a convention that I am planning to ignore. The
julia names for lots of functions are utterly unreadable - unless you
come from R/ matlab or similar.

__init__

So it is clearly always going to be legal...

The guys don't like underscores  - nor camel-case - why I don't know.

Greetings
 Claus

**Comment by fieker** [comment]
On Thu, Mar 17, 2016 at 11:31:13AM -0700, wbhart wrote:
> The style guide for Julia was certainly written after large parts of Base were written. They also have consistency issues and it is my understanding they will work towards fixing this. The conventions they are using seem to be gradually converging over time, and as they reach agreement after changing things, they seem to be updating their style guide.
> 
> Of course we don't need to follow it. It just might increase the number of serious Julia coders who contribute down the track. I was just bringing attention to the issue.
> 
> There is actually a discussion online about function hiding and one of the core devs suggests that he doesn't like leading underscores and that although he wouldn't prohibit it at this stage, he would prefer "hiding" is done by not exporting functions from the module.
> 
> Sorry about the wording "arbitrary hacks". It's perhaps not the best wording. What I mean is introducing new things that aren't rolled out across the whole of Nemo. One of the main features of Nemo is to have a generic system which actually *relies* on things being consistent across the system for the most part. 
> 
> Documentation, coding style and so on also benefit from being consistent, both with the Julia codebase where possible and across Nemo. If we ourselves all do things differently across the codebase, other developers will do the same and we'll have many different coding styles, including ones that encourage errors or that are unreadable or that we explicitly don't like. 
> 
> Here is a bad example of this:
> 
> https://github.com/wbhart/mpir/blob/06d4a329430d3e44675aad5ea1e20972fabbc683/mpn/generic/divrem_euclidean_r_1.c
> 
> Anyway, I would say that 1-5, 7 and 8 are all examples of things that either need a convention to be decided or which need rolling out across the whole of Nemo.
> 
> My argument was simply that if we introduce more such things with each patch, we aren't converging any more. It's not a problem, I'm just wanting to point it out so we can discuss and agree on how far we want to go with consistency. That depends on our ultimate goals I guess.


Consistency is important - but, im my opinion, even more important is
moving forward. I am happy with the idea of doing coding sprints every
now and then to smooth things over, but on the other hand, I am also
using inconsistencies for experimentation. If it works in a single case,
then next step, we can roll it out everywhere.
Actually, we have a fair number of consistencies and rounding off
patches that are currently in Hecke. We need to look at them, correct
them and seelct some...

eg. rand(ResidueRing) (if the ring is finite)
size, ...

and I have more.

Greetings
 Claus

**Comment by fieker** [comment]
On Thu, Mar 17, 2016 at 09:20:32AM -0700, wbhart wrote:
> 4. Private functions are denoted in Julia by not exporting them. Using leading underscores is not encouraged, though they stopped short of explicitly adding that to the style guide. However, the style guide does now set out when underscores should be used. They adopted the convention that I ended up using:

That is too course - maybe we need submodules? I'd like s.th. that is
smaller tha a module as a name-space. E.g. the class group stuff will,
in the end, have many functions that are not usable outside class
groups, not even in Hecke. I'd like to keep them hidden - like a static
function in a c-file. I know that hiding is not making them
inaccessible, but it helps.

Or, alternatively, our modules (hecke/ Nemo) are too large maybe?

**Pull request merged**
