### PR TITLE
Get the generic linear solving back in

### LINKED ISSUE #1656: Nemo master breaks Oscar
Since the merge of https://github.com/Nemocas/Nemo.jl/pull/1633, there is a test failure regarding the `OscarCI matching` CI job (see https://github.com/Nemocas/Nemo.jl/actions/runs/7752442118/job/21141966021#step:7:3433)

To rule out that #1633 is responsible for this, I created https://github.com/Nemocas/Nemo.jl/pull/1655 to watch the CI there.

```
elliptic parameter: Error During Test at /home/runner/work/Nemo.jl/Nemo.jl/oscar-dev/Oscar/test/AlgebraicGeometry/Schemes/elliptic_surface.jl:59
  Got exception outside of a @test
  BoundsError: attempt to access QQMatrix at index [1, 9]
  Stacktrace:
    [1] throw_boundserror(A::QQMatrix, I::Tuple{Int64, Int64})
      @ Base ./abstractarray.jl:734
    [2] _checkbounds
      @ AbstractAlgebra ~/.julia/packages/AbstractAlgebra/FHURQ/src/Matrix.jl:61 [inlined]
    [3] getindex
      @ Nemo ~/work/Nemo.jl/Nemo.jl/src/flint/fmpq_mat.jl:109 [inlined]
    [4] find_pivots(M::QQMatrix)
      @ Hecke ~/work/Nemo.jl/Nemo.jl/oscar-dev/Hecke/src/Misc/jordan.jl:279
    [5] complete_to_basis(C::QQMatrix)
      @ Hecke ~/work/Nemo.jl/Nemo.jl/oscar-dev/Hecke/src/Misc/jordan.jl:294
    [6] _diagonal(V::Hecke.QuadSpace{QQField, QQMatrix}, with_transform::Bool)
      @ Hecke ~/work/Nemo.jl/Nemo.jl/oscar-dev/Hecke/src/QuadForm/Quad/Spaces.jl:198
    [7] diagonal
      @ Hecke ~/work/Nemo.jl/Nemo.jl/oscar-dev/Hecke/src/QuadForm/Quad/Spaces.jl:190 [inlined]
    [8] is_positive_definite(V::Hecke.QuadSpace{QQField, QQMatrix})
      @ Hecke ~/work/Nemo.jl/Nemo.jl/oscar-dev/Hecke/src/QuadForm/Spaces.jl:481
    [9] is_definite
      @ Hecke ~/work/Nemo.jl/Nemo.jl/oscar-dev/Hecke/src/QuadForm/Spaces.jl:516 [inlined]
   [10] __compute_is_definite__
      @ Hecke ~/work/Nemo.jl/Nemo.jl/oscar-dev/Hecke/src/QuadForm/Lattices.jl:538 [inlined]
   [11] #5259
      @ Hecke ~/.julia/packages/AbstractAlgebra/FHURQ/src/Attributes.jl:357 [inlined]
   [12] get!(default::Hecke.var"#5259#5260"{ZZLat}, h::Dict{Symbol, Any}, key::Symbol)
      @ Base ./dict.jl:479
   [13] get_attribute!
      @ ~/.julia/packages/AbstractAlgebra/FHURQ/src/Attributes.jl:230 [inlined]
   [14] is_definite
      @ ~/work/Nemo.jl/Nemo.jl/oscar-dev/Hecke/src/QuadForm/Lattices.jl:538 [inlined]
   [15] macro expansion
      @ ~/work/Nemo.jl/Nemo.jl/oscar-dev/Hecke/src/Assertions.jl:560 [inlined]
   [16] root_sublattice(L::ZZLat)
      @ Hecke ~/work/Nemo.jl/Nemo.jl/oscar-dev/Hecke/src/QuadForm/Quad/ZLattices.jl:2022
   [17] root_lattice_recognition(L::ZZLat)
      @ Hecke ~/work/Nemo.jl/Nemo.jl/oscar-dev/Hecke/src/QuadForm/Quad/ZLattices.jl:1729
   [18] standardize_fiber(S::EllipticSurface{FqField, AbstractAlgebra.Generic.FracFieldElem{FqPolyRingElem}}, f::Vector{WeilDivisor{EllipticSurface{FqField, AbstractAlgebra.Generic.FracFieldElem{FqPolyRingElem}}, ZZRing, ZZRingElem}})
      @ Oscar ~/work/Nemo.jl/Nemo.jl/oscar-dev/Oscar/experimental/Schemes/elliptic_surface.jl:761
   [19] __compute__trivial_lattice__(S::EllipticSurface{FqField, AbstractAlgebra.Generic.FracFieldElem{FqPolyRingElem}})
      @ Oscar ~/work/Nemo.jl/Nemo.jl/oscar-dev/Oscar/experimental/Schemes/elliptic_surface.jl:671
   [20] #8088
      @ ~/.julia/packages/AbstractAlgebra/FHURQ/src/Attributes.jl:357 [inlined]
   [21] get!(default::Oscar.var"#8088#8090"{EllipticSurface{FqField, AbstractAlgebra.Generic.FracFieldElem{FqPolyRingElem}}}, h::Dict{Symbol, Any}, key::Symbol)
      @ Base ./dict.jl:479
   [22] get_attribute!
      @ ~/.julia/packages/AbstractAlgebra/FHURQ/src/Attributes.jl:230 [inlined]
   [23] _trivial_lattice
      @ ~/work/Nemo.jl/Nemo.jl/oscar-dev/Oscar/experimental/Schemes/elliptic_surface.jl:616 [inlined]
   [24] trivial_lattice(X::EllipticSurface{FqField, AbstractAlgebra.Generic.FracFieldElem{FqPolyRingElem}})
      @ Oscar ~/work/Nemo.jl/Nemo.jl/oscar-dev/Oscar/experimental/Schemes/elliptic_surface.jl:698
   [25] __compute_algebraic_lattice__(X::EllipticSurface{FqField, AbstractAlgebra.Generic.FracFieldElem{FqPolyRingElem}})
      @ Oscar ~/work/Nemo.jl/Nemo.jl/oscar-dev/Oscar/experimental/Schemes/elliptic_surface.jl:162
   [26] #8067
      @ ~/.julia/packages/AbstractAlgebra/FHURQ/src/Attributes.jl:357 [inlined]
   [27] get!(default::Oscar.var"#8067#8070"{EllipticSurface{FqField, AbstractAlgebra.Generic.FracFieldElem{FqPolyRingElem}}}, h::Dict{Symbol, Any}, key::Symbol)
      @ Base ./dict.jl:479
   [28] get_attribute!
      @ ~/.julia/packages/AbstractAlgebra/FHURQ/src/Attributes.jl:230 [inlined]
   [29] algebraic_lattice
      @ ~/work/Nemo.jl/Nemo.jl/oscar-dev/Oscar/experimental/Schemes/elliptic_surface.jl:160 [inlined]
   [30] two_neighbor_step(X::EllipticSurface{FqField, AbstractAlgebra.Generic.FracFieldElem{FqPolyRingElem}}, F::Vector{QQFieldElem})
      @ Oscar ~/work/Nemo.jl/Nemo.jl/oscar-dev/Oscar/experimental/Schemes/elliptic_surface.jl:1115
   [31] macro expansion
      @ ~/work/Nemo.jl/Nemo.jl/oscar-dev/Oscar/test/AlgebraicGeometry/Schemes/elliptic_surface.jl:76 [inlined]
   [32] macro expansion
      @ /opt/hostedtoolcache/julia/1.10.0/x64/share/julia/stdlib/v1.10/Test/src/Test.jl:1577 [inlined]
   [33] macro expansion
      @ ~/work/Nemo.jl/Nemo.jl/oscar-dev/Oscar/test/AlgebraicGeometry/Schemes/elliptic_surface.jl:60 [inlined]
   [34] macro expansion
      @ /opt/hostedtoolcache/julia/1.10.0/x64/share/julia/stdlib/v1.10/Test/src/Test.jl:1577 [inlined]
   [35] top-level scope
      @ ~/work/Nemo.jl/Nemo.jl/oscar-dev/Oscar/test/AlgebraicGeometry/Schemes/elliptic_surface.jl:59
   [36] include
      @ ./Base.jl:496 [inlined]
   [37] macro expansion
      @ ./timing.jl:503 [inlined]
   [38] _timed_include(str::String, mod::Module; use_ctime::Bool)
      @ Oscar ~/work/Nemo.jl/Nemo.jl/oscar-dev/Oscar/src/utils/tests.jl:5
   [39] _timed_include (repeats 2 times)
      @ ~/work/Nemo.jl/Nemo.jl/oscar-dev/Oscar/src/utils/tests.jl:1 [inlined]
   [40] test_module(path::String; new::Bool, timed::Bool, ignore::Vector{Any})
      @ Oscar ~/work/Nemo.jl/Nemo.jl/oscar-dev/Oscar/src/utils/tests.jl:151
   [41] test_module
      @ Oscar ~/work/Nemo.jl/Nemo.jl/oscar-dev/Oscar/src/utils/tests.jl:119 [inlined]
   [42] #29
      @ Main ~/work/Nemo.jl/Nemo.jl/oscar-dev/Oscar/test/runtests.jl:137 [inlined]
   [43] (::Base.var"#1023#1028"{var"#29#30"})(r::Base.RefValue{Any}, args::Tuple{String})
      @ Base ./asyncmap.jl:94
   [44] (::Base.var"#1039#1040"{Base.var"#1023#1028"{var"#29#30"}, Channel{Any}, Nothing})()
      @ Base ./asyncmap.jl:228
Test Summary:        | Error  Total     Time
elliptic surfaces    |     3      3  4m46.8s
  elliptic parameter |     3      3  4m46.8s
```

### PR DESCRIPTION
**Pull request by joschmitt**
Reverts #1655 which reverted #1633.

### CODE REVIEW

**Comment by thofma** [comment]
Please use a `view`.

**Comment by joschmitt** [comment]
> Please use a `view`.

Okay. There are more problems with this. Apparently people relied heavily on the structure of `nullspace(::QQMatrix)` (although nothing was ever promised).

**Comment by lgoettgens** [comment]
You will need to cherry-pick https://github.com/Nemocas/Nemo.jl/commit/e40892bb37b88c10bb2c008225a646d0b8609ffe to the beginning of this branch, once you rebase onto master.

**Comment by joschmitt** [comment]
> You will need to cherry-pick [e40892b](https://github.com/Nemocas/Nemo.jl/commit/e40892bb37b88c10bb2c008225a646d0b8609ffe) to the beginning of this branch, once you rebase onto master.

Ah, saw this too late. I just reverted the revert. Let's see what breaks this time.

**Comment by joschmitt** [comment]
I'll close this now and create two separate pull requests for the linear solving and `nullspace(::QQMatrix)`.

**Pull request closed without merging**
