### PR TITLE
try fixing master names nonsense changes

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by thofma** [comment]
Not working yet. At the moment I get
```
Failed to precompile Nemo [2edaba10-b0f1-5616-af89-8c11ac63239a] to "/bla/compiled/v1.12/Nemo/jl_bWSCtB".
ERROR: LoadError: UndefVarError: `EuclideanRingResidueRingElem` not defined in `Nemo`
```
although
```
julia> :EuclideanRingResidueRingElem in names(AbstractAlgebra; usings_explicit = true, non_public = true)
true
```
Not sure what the problem is. Maybe something to do with `Generic`?

**Comment by thofma** [comment]
Maybe it is a problem with https://github.com/JuliaLang/julia/pull/54659. Apparently it should not have changed the old behavior. I will open an issue.

**Comment by thofma** [comment]
Arg, we are now getting all the symbols in AbstractAlgebra, that every module automatically has, e.g. `include`, `pkgdir`,...

**Comment by thofma** [comment]
OK, let's hope julia folks consider this a bug.

**Comment by lgoettgens** [comment]
The julia commit has been reverted in https://github.com/JuliaLang/julia/pull/54959, so Nemo should work again once the next nightly is available (in a few hours).

**Pull request closed without merging**
