### PR TITLE
ASCIIString -> String for Julia-0.5.

### PR DESCRIPTION
**Pull request by wbhart**

### CODE REVIEW

**Comment by wbhart** [comment]
Great. What am I supposed to do about that.

**Comment by thofma** [comment]
We probably have to do something similar as you did here:
https://github.com/Nemocas/Nemo.jl/blob/master/src/Nemo.jl#L201-L218

Or we ignore the warnings until 0.5 is released and then abandon support for 0.4.

**Comment by wbhart** [comment]
OK, just ignore the PR for now. We'll make 0.5 a requirement once our
release is working well with Julia 0.5.

**Comment by thofma** [comment]
Sounds reasonable.

**Comment by thofma** [comment]
Already fixed.

**Pull request closed without merging**
