### PR TITLE
Solve

### PR DESCRIPTION
**Pull request by fieker**
solve was implicitly always working over the field. This is now solve_rational.
solve itself is working over fmpz_mat and matrices over fields. We will, eventually, expand this to matrives over euclidean rings and others.

We face the same problem in nullspace and inv.

### CODE REVIEW

**Comment by thofma** [comment]
What happens if I use `solve` on `nmod_mat`? Since they are `<: MatElem{RingElem}` and not `<: MatElem{FieldElem}`, I don't know what is happening.

**Comment by fieker** [comment]
On Mon, May 08, 2017 at 06:49:24AM -0700, thofma wrote:
> What happens if I use `solve` on `nmod_mat`? Since they are `<: MatElem{RingElem}` and not `<: MatElem{FieldElem}`, I don't know what is happening.

hopefully an error! But the anwser is: I don't know.
solve should never return a tuple, but it can fail.
Clearly, for nmod_mat we can make solve work - since we have (I think)
a working hnf_with_trafo - which is the limiting factor for solve

**Comment by thofma** [comment]
I more thinking of prime modulus. Because you changed the signature of `solve` from `MatElem{RingElem}` to `MatElem{FieldElem}`, I don't know if you can apply it to matrices over `Z/2Z`.

**Comment by fieker** [comment]
On Mon, May 08, 2017 at 07:00:06AM -0700, thofma wrote:
> I more thinking of prime modulus. Because you changed the signature of `solve` from `MatElem{RingElem}` to `MatElem{FieldElem}`, I don't know if you can apply it to matrices over `Z/2Z`.

Yep - but the problem I wanted to solve is that 
solve for MatElem{RingElem} -> (Mat, RingElem)

which is bad. If you want this, solve_rational is your friend.

solve  - once it is implemented for those rings, will give a solution or
an error.

For the majority of usage, solve has just been replaced by
solve_rational

**Comment by thofma** [comment]
OK, I think I get it.

I will make some minor changes (typos) today or tomorrow and then we can merge it.

**Comment by fieker** [comment]
On Mon, May 08, 2017 at 07:09:17AM -0700, thofma wrote:
> OK, I think I get it.
> 
> I will make some minor changes (typos) today or tomorrow and then we can merge it.

Be my guest... thanks
 Claus

**Comment by wbhart** [comment]
I didn't understand the comment added to todo.txt. It seems to work for me:

julia> R, x = PolynomialRing(QQ, "x")
(Univariate Polynomial Ring in x over Rational Field,x)

julia> K, a = NumberField(x^3 + 3x + 1, "a")
(Number field over Rational Field with defining polynomial x^3 + 3*x + 1,a)

**Comment by fieker** [comment]
On Mon, May 08, 2017 at 07:17:56AM -0700, wbhart wrote:
> I didn't understand the comment added to todo.txt. It seems to work for me:
If you do it with cached=false (or cached=true, so if you add the cached
parameter, you loose the generator
> 
> julia> R, x = PolynomialRing(QQ, "x")
> (Univariate Polynomial Ring in x over Rational Field,x)
> 
> julia> K, a = NumberField(x^3 + 3x + 1, "a")
> (Number field over Rational Field with defining polynomial x^3 + 3*x + 1,a)
> 
>

**Comment by wbhart** [comment]
Oh yeah, that's a nice bug!

**Comment by thofma** [comment]
Can you post the code? I cannot reproduce it.
```
julia> NumberField(f, "a", cached = false)
(Number field over Rational Field with defining polynomial x^18 + 18*x^16 + 135*x^14 + 192*x^12 - 2961*x^10 - 17334*x^8 + 20361*x^6 + 315108*x^4 + 514944*x^2 + 123904,a)

julia> NumberField(f, "a", cached = true)
(Number field over Rational Field with defining polynomial x^18 + 18*x^16 + 135*x^14 + 192*x^12 - 2961*x^10 - 17334*x^8 + 20361*x^6 + 315108*x^4 + 514944*x^2 + 123904,a)
```

**Comment by fieker** [comment]
On Mon, May 08, 2017 at 07:32:39AM -0700, thofma wrote:
> Can you post the code? I cannot reproduce it.

Maybe it has been secretly fixed? I;ll try again all combinations.

BTW: this commit was not meant to be there. It is just a result of my
usual git fun...
Sorry

**Comment by wbhart** [comment]
You can add another commit to the same branch which reverses this change.
It'll automatically show up in the PR.

**Comment by thofma** [comment]
Fixed some type instability. Ready to merge if no one objects.

**Comment by wbhart** [comment]
The addition to todo.txt still appears to be there.

**Comment by thofma** [comment]
Fixed.

**Pull request merged**
