### PR TITLE
remove, optionally, the sanity checks in nmod_poly resultant

### PR DESCRIPTION
**Pull request by fieker**

### CODE REVIEW

**Comment by thofma** [comment]
It is not type stable. It has to be `check::Bool = true` in the signature.

**Comment by fieker** [comment]
On Tue, Feb 21, 2017 at 04:13:38AM -0800, thofma wrote:
> It is not type stable. It has to be `check::Bool = true` in the signature.

When I figure out how I shall fix this.

**Comment by wbhart** [comment]
Can you open a new PR to fix that. I just merged this one before Tommy made that comment.

**Comment by wbhart** [comment]
Can you open a new PR to fix that. I just merged this one before Tommy made that comment.

**Comment by wbhart** [comment]
Alternatively, you can just make the changes directly via the GitHub web interface.

**Comment by wbhart** [comment]
Ok, I did it myself.

**Pull request merged**
