### PR TITLE
Trivial embedding fail in Nemo

### PR DESCRIPTION
**Pull request by erou**
As noticed by @tmagnuss in #670, asking for a trivial embedding in Nemo results in a segfault. 

In fact, trivial embeddings are not implemented in flint.

I added a test to check if the degree of the embedded finite field was 1, I also corrected a stupid bug and some typos.

Tell me if it is the way you want to handle it!

### CODE REVIEW

**Comment by wbhart** [comment]
It's fine. Could the error message be something like, "trivial embeddings are not currently implemented"?

**Comment by thofma** [comment]
Why? I think he just added an implementation for this case.

**Comment by thofma** [comment]
Or do you mean change the segmentation fault to an error message in flint itself?

**Comment by erou** [comment]
It is implemented, If k is a prime field and K an extension, I use the function `f(x) = K(coeff(x, 0))`, which do not need flint at all since the embedding is very easy to understand.

But I could also say in the documentation that it's not implemented and just send an error. I don't know how often people will embed finite fields of degree 1 and if we want to store functions like that `f` in the memory...

**Comment by rfourquet** [comment]
Could you add a test to check that the previous segfault doesn't occur anymore? (for example taken from the Github issue reporting it).

**Comment by thofma** [comment]
Yes, we need the embedding in the degree 1 case.

Would be good to add a test for it.

**Comment by defeo** [comment]
> Or do you mean change the segmentation fault to an error message in flint itself?

When I designed the flint function, I intended it to only be called for non-trivial embeddings. This could easily be documented better; adding a test to avoid the segfault shouldn't be a problem either.

**Comment by erou** [comment]
Sure, I should add tests for trivial embeddings, and maybe also for preimage maps.

**Comment by wbhart** [comment]
@thofma @erou Sorry, my bad. I read the description above which says that degree 1 embeddings are not supported in Flint and assumed that the error message @erou added was to raise an exception in this case. I didn't read the code and realise it was to ban trying to do actually impossible embeddings.

You can ignore that comment from me.

**Comment by wbhart** [comment]
Let us know when you are ready, @erou

**Comment by erou** [comment]
> Let us know when you are ready, @erou

You mean for a merge? If the tests pass, I'm okay with it!

**Comment by wbhart** [comment]
Yes, thanks.

**Comment by wbhart** [comment]
@erou By the way, I have been working all week on fmpz_mod_mat in Nemo. There has been one hell of a mess to fix before I can get there, so it's taking a while. I still don't even have the module loading in Julia without errors....

**Pull request merged**
