### PR TITLE
Renaming of Arb-functions

### LINKED ISSUE #1073: Rethink names for special functions
From #1071:

I am a little distraught at the arcane naming scheme for these functions.
Arbitrarily truncating `elliptic` to `ellip` or using `hyper` sometimes and
`hyp` sometimes is just bad style to me. Also, a nice cute name like `shi` is
really only cute for a few minutes. @fredrik-johansson
```
ei          => exp_integral_ei
si          => sin_integral
ci          => cos_integral
shi         => sinh_integral (or just omit this trivial function)
chi         => cosh_integral (ditto)
li          => log_integral
lioffset    => log_integral
expint      => exp_integral_e
hyp1f1      => hypergeometric_1f1
hyp1f1r     => hypergeometric_1f1_regularized
hyperu      => hypergeometric_u
hyp2f1      => hypergeometric_2f1
jtheta      => jacobi_theta
modeta      => modular_eta
modj        => modular_j
modlambda   => modular_lambda
moddelta    => modular_delta
ellipwp     => weierstrass_p
????        => weierstrass_p_prime
ellipk      => elliptic_k
ellipe      => elliptic_e
```

_Originally posted by @tthsqe12 in https://github.com/Nemocas/Nemo.jl/issues/1071#issuecomment-845745690_

### PR DESCRIPTION
**Pull request by albinahlback**
Let me know if any name should be changed.

Closes #1073

### CODE REVIEW

**Comment by thofma** [comment]
@tthsqe12 since he actually knows what these functions do

**Comment by tthsqe12** [comment]
Looks good. The rationale for using `sin_integral` and `modular_lambda` is simply that that is what we call them most naturally. `integral_sin` just sounds weird. The closer we are to https://functions.wolfram.com/GammaBetaErf/ the better it probably is.
However, these are not perfect either: I would object to `Pochhammer` being used instead of `RisingFactorial`, and the `KleinInvariantJ` is the less standard capital `J` version of the `j` function. Maybe being forced to use PascalCase forces you to use the capital `J` version. :)

**Comment by fredrik-johansson** [comment]
I would suggest also looking at this: https://fredrikj.net/calcium/fexpr_builtin.html for inspiration.

Most names agree with Mathematica but some things have been renamed. I propose, for example:

* modeta -> dedekind_eta (not modular_eta; there is nothing wrong with modular_eta, but this function is absolutely known as the "Dedekind eta function")
* I think I would like to have both legendre_polynomial, legendre_p.

**Comment by albinahlback** [comment]
I agree, I would prefer `dedekind_eta`, but also `eisenstein[_e/_g]` over the `modular_`-prefix. I can fix alias for the Legendre polynomials.

**Review by tthsqe12 — CHANGES_REQUESTED** [review]
I agree with fredrik that modular_eta should be replaced with dedekind_eta, and also do what he wants with legendre polynomials.

**Comment by tthsqe12** [comment]
Maybe also `modular_j => j_invariant`?

**Comment by albinahlback** [comment]
> Maybe also `modular_j => j_invariant`?

Yes!

**Comment by fredrik-johansson** [comment]
JInvariant looks strange in the PascalCase version though.

I think I'd prefer either elliptic_j or modular_j -- both "Elliptic j-function" and "Modular j-function" are common pronunciations.

**Comment by albinahlback** [comment]
How about aliasing `j_invariant` with `modular_j`?

**Comment by wbhart** [comment]
modular_j is good for me. Aliasing can be problematic for search and replace in code. I'm not a huge fan of aliasing. However, it's not up to me. See what the others say.

**Comment by albinahlback** [comment]
I feel finished now. Note that I did not care to deprecate the `modular_`-prefix, since they only have been implemented for less than a week.

> I think I would like to have both legendre_polynomial, legendre_p.
Didn't rename them since they're not implemented in Nemo yet.

**Review by wbhart — APPROVED** [review]

**Comment by thofma** [comment]
Are you happy with the names @tthsqe12? We don't want to do this too often, so I want to double check with you.

**Comment by albinahlback** [comment]
Updated the branch. Ping @tthsqe12.

**Comment by wbhart** [comment]
I've added the breaking label. That means it'll wait until the next breaking release to be merged. But it will get merged!

**Comment by tthsqe12** [comment]
Looks good. I will open an issue for the remaining legendre polynomials and missing functions.

**Pull request merged**
