### PR TITLE
Bump Arb version (requested by Fredrik)

### PR DESCRIPTION
**Pull request by wbhart**

### CODE REVIEW

**Comment by thofma** [comment]
Did you rebuild the Windows binaries?

**Comment by wbhart** [comment]
Ah, no, completely forgot about that bit.

**Comment by thofma** [comment]
I can do it in Monday. Can this PR wait till then?

**Comment by wbhart** [comment]
I think this was prompted by Peter Luschny's comments on matrix multiplication, so I'd say it can wait a day or two. It's not holding up something super critical.

**Pull request closed without merging**
