### PR TITLE
Prepare deprecations for breaking release

### PR DESCRIPTION
**Pull request by lgoettgens**
Includes and thus closes https://github.com/Nemocas/Nemo.jl/pull/1758.

### CODE REVIEW

**Comment by lgoettgens** [comment]
This will need some further changes after https://github.com/Nemocas/Nemo.jl/pull/1824 is merged to deprecate the aliases introduced there.

**Comment by lgoettgens** [comment]
Regarding the error: the line https://github.com/oscar-system/Oscar.jl/blob/251b831144612cb08fcde2be58d40f59d6a15fac/src/imports.jl#L200 needs to be removed in Oscar to make it compatible with this change

**Comment by thofma** [comment]
#1824 has been merged, so I guess this needs to be adjusted now?

**Comment by lgoettgens** [comment]
I'm currently on my way from teaching to the office. I'll rebase and adjust it once I'm there

**Pull request merged**
