### PR TITLE
Clean up remove and valuation

### LINKED ISSUE #132: remove/valuation
- Clean up remove and valuation.
- Add documentation.

### PR DESCRIPTION
**Pull request by thofma**
- Remove turns the valuation and the remainder
- Valuation only returns the valuation
- Extended to fractions

Closes #132.

### CODE REVIEW

**Comment by wbhart** [comment]
It looks like you may have forgotten to commit the fmpq test.

**Comment by wbhart** [comment]
Otherwise it all looks good to me.

**Comment by thofma** [comment]
It is in generic/Fraction.jl, so the test went to test/generic/Fraction-test.jl.

**Comment by wbhart** [comment]
You've actually defined functions in fmpq.jl, according to the list of modified files.

**Comment by wbhart** [comment]
I think they are the ad hoc ones: valuation(fmpq, Int), remove(fmpq, Int)

**Comment by thofma** [comment]
Done. I merge it once travis is done.

**Comment by wbhart** [comment]
Yep, looks good to me.

**Pull request merged**
