### PR TITLE
Add is_zero_entry method; remove is_zero_row methods

### PR DESCRIPTION
**Pull request by fingolfin**
With the addition of the new is_zero_entry method, the removed
is_zero_row methods are not faster than the generic one. Also add some
tests, which were also used for benchmarking, together with

    @benchmark Nemo.is_zero_row($M,4)

### CODE REVIEW

**Review by lgoettgens — APPROVED** [review]

**Comment by lgoettgens** [comment]
Can someone (@fingolfin @thofma) un-require the nightly CI job until https://github.com/oscar-system/Oscar.jl/issues/3882 is resolved?

**Comment by fingolfin** [comment]
Huh, from my POV the tests against Julia nightly should *never* be required. Changed it.

**Comment by fieker** [comment]
is_zero_row should be done for ZZ and ZZ mod, but in a useful way. The removed implementation is highly non-optimal, this can be sped up by a factor of 10 or so

**Comment by fieker** [comment]
although it is probably non critical, timewise

**Comment by lgoettgens** [comment]
There is actually a generic function in https://github.com/Nemocas/AbstractAlgebra.jl/blob/762eab1920547d2e4c3f3e77a4976fff119bf206/src/Matrix.jl#L247-L254, that delegates to a Nemo-backed `is_zero_entry`. Thus Max's removal is essentially no change at all.

**Comment by fieker** [comment]
the point is that is_zero_row for ZZ should be done via
 - get the pointer of the row (no c-call!)
 - check if the entries are binary zero (no c-call)
Currently it uses 2 c-calls per entry hence the generic is fine.
The same logic would apply also to Z/nZ, small or large and possible Native.GF(p)

**Pull request merged**
