### PR TITLE
Fix bug in solve_rational hidden by try & catch

### PR DESCRIPTION
**Pull request by thofma**
Yeah, we should either stop using try & catch or use it more safely.

### CODE REVIEW

**Comment by wbhart** [comment]
Thanks for fixing that!

**Comment by wbhart** [comment]
Though the tests seem to be failing on all builds now....

**Comment by thofma** [comment]
Forgot to run them ..

**Comment by thofma** [comment]
Fixed another bug in the `nmod_mat` constructors.

**Comment by wbhart** [comment]
Thanks!

**Pull request merged**
