### PR TITLE
use Sys.CPU_THREADS when invoking "make"

### PR DESCRIPTION
**Pull request by heiderich**
instead of using hard-coded values

### CODE REVIEW

**Comment by thofma** [comment]
While the hard coded values are questionable, just using all the cores is not a good idea either. In particular on servers with more then one user.

**Comment by heiderich** [comment]
One advantage of this change is that tests finish potentially faster. This in turn may speed up development time, as pull requests can potentially be merged faster.

One may take a fraction of the number of cores. But which one?

**Comment by thofma** [comment]
Note that nothing is built by default anymore. Binaries are just downloaded. If you want to build binaries, you have to explicitly set an environment variable (see the bottom of http://nemocas.github.io/Nemo.jl/latest/).

**Comment by heiderich** [comment]
Thanks for this information. I was not aware of this.

**Comment by heiderich** [comment]
In Jenkins we currently have `NEMO_SOURCE_BUILD=1`. The changed introduced in this PR could speed up the build stage significantly on hardware with many threads.

A different approach would be an environmental variable controlling the number of threads with a sensible default (either a fixed number such as `4` or the approach I propose here). Would you prefer that?

**Comment by thofma** [comment]
The environment variable sounds like a great idea. Would you mind adding it? I am bit at names but maybe something like `NEMO_BUILD_THREADS`? The default can be the one that you propose here. Would be nice if this would also be documented in the building section of https://github.com/Nemocas/Nemo.jl/blob/master/docs/src/index.md.

**Comment by heiderich** [comment]
Please see #609.

**Comment by heiderich** [comment]
Closing this in favor of #609.

**Pull request closed without merging**
