### PR TITLE
re-enable disabled tests

### PR DESCRIPTION
**Pull request by rfourquet**
Cf. https://github.com/Nemocas/Nemo.jl/pull/639#issuecomment-535859767.

### CODE REVIEW

**Comment by wbhart** [comment]
Thanks. I will take a look at the failures and fix some of them.

**Comment by wbhart** [comment]
@thofma Do you remember why the adhoc division tests were disabled at some point? As there are quite a lot of them, I think maybe we did it on purpose for some reason.

**Comment by rfourquet** [comment]
I can trace back to 1ba5fd2dfdcb60f5c4d7b453a9ee4c72e2832651 for e.g. `fmpz_series.adhoc_exact_division`, where the function is created, but just not never called  (i.e. not included in `test_fmpz_series()`). So it doesn't seem to have been disabled on purpose, just never enabled.

**Comment by wbhart** [comment]
It's ok, we figured it out. I forgot to update the ticket accordingly. But thanks for looking into it.

**Comment by wbhart** [comment]
Feel free to squash commits for this PR when it passes.

**Pull request merged**
