### PR TITLE
Added arg checks

### PR DESCRIPTION
**Pull request by JohnAAbbott**
Two independent changes:

1.  added arg checks to `primorial` and `fibonacci` with `Int` args: now immediately reports `InexactError` without computing a potentially large value (which is then simply thrown away) if the supplied arg is too big
2.  arg checks for non-neg matrix dimension in matrix constructors & matrix space constructors (to avoid passing obviously invalid args to FLINT functions)

### CODE REVIEW

**Comment by thofma** [comment]
Could you please drop https://github.com/Nemocas/Nemo.jl/pull/1731/commits/a97df374edf2fcd490641da035a665d01f746ab4? The solution in #1729 is a better fit given the overall design.

**Comment by lgoettgens** [comment]
The error looks kind of weird
```
julia> fibonacci(100)
ERROR: InexactError: fibonacci(Int64, large_integer_value)
Stacktrace:
 [1] fibonacci(x::Int64)
   @ Nemo ~/code/julia/Nemo.jl/src/flint/fmpz.jl:1870
 [2] top-level scope
   @ REPL[2]:1
```
Maybe replace the `fibonacci` in there by `convert` (like the current error) or some other change?

**Comment by JohnAAbbott** [comment]
> Could you please drop [a97df37](https://github.com/Nemocas/Nemo.jl/commit/a97df374edf2fcd490641da035a665d01f746ab4)? The solution in #1729 is a better fit given the overall design.

OK, will try to figure out how to "drop" it...

**Comment by JohnAAbbott** [comment]
> The error looks kind of weird
> [...]
> Maybe replace the `fibonacci` in there by `convert` (like the current error) or some other change?

I have just tried Julia's `factorial` function: it behaves as follows:
```
julia> factorial(999)
ERROR: OverflowError: 999 is too large to look up in the table; consider using `factorial(big(999))` instead
Stacktrace:  [...]
```
I chose `InexactError` because that is what is currently produced; TBH I think that `OverflowError` is more appropriate; but does that count as a "breaking change"?  Not sure about the recommendation to call `fibonacci(ZZ(...))` instead.

**Comment by JohnAAbbott** [comment]
How does this look?
```
julia> fibonacci(999)
ERROR: OverflowError: fibonacci(::Int)
Stacktrace: [...]
```

**Pull request closed without merging**
