### PR TITLE
Remove redundant identity_matrix methods

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by thofma** [comment]
Can you elaborate on the "redundant"? I have not found any other call to `fmpq_mat_one`, so I am not sure where the redundancy comes from.

**Comment by fingolfin** [comment]
@thofma you are 100% right, this method (and two others using `ccall`) should not be removed. I removed the first couple which are essentially equivalent to the default implementation, and then didn't pay attention. I guess I should stop making PRs at 01:00 :-(, at the very least those should be scrutinized doubly.

**Comment by fingolfin** [comment]
Oh, and of course if there are similar `*_mat_one` methods for the other rings, e.g. `fmpz_mat_one`, we could also switch the code to use those, I didn't check for that.

**Comment by thofma** [comment]
Thanks. About the other `_one` methods, those can be added at some point I guess.

**Pull request merged**
