### PR TITLE
change mid_d1, mid_d2 fields to UInts, correct conversion to Float

### PR DESCRIPTION
**Pull request by JeffreySarnoff**
change mid_d1, mid_d2 fields in arb_struct, arf_struct, acb
within convert(::Type{Float64}, x::arb) use explict Int->UInt conversion

### CODE REVIEW

**Comment by thofma** [comment]
Thanks, but why the explicit conversion? It's redundant.

**Comment by JeffreySarnoff** [comment]
_*(because Git and I do not get along)_


It failed again with
Build started
git clone -q https://github.com/Nemocas/Nemo.jl.git C:\projects\nemo-jl-n5gdb
git fetch -q origin +refs/pull/54/merge:
git checkout -qf FETCH_HEAD
Specify a project or solution file. The directory does not contain a project or solution file.

looking up that error message, I found
[this discussion, which might apply](http://help.appveyor.com/discussions/problems/4294-all-builds-say-specify-a-project-or-solution-file-the-directory-does-not-contain-a-project-or-solution-file)

**Comment by JeffreySarnoff** [comment]
The difficulty may be that AppVeyor is looking for appveyor.xml, and it is not there

**Comment by thofma** [comment]
Yes, I know. If fixed it here https://github.com/Nemocas/Nemo.jl/pull/5 but this was never merged.

**Comment by JeffreySarnoff** [comment]
aha! <ok .. I will leave this as is, so it remains available>

**Comment by thofma** [comment]
If no one complains I will merge it on Wednesday.

**Comment by wbhart** [comment]
Fine by me. I'm actually just modifying arb.jl right now, so you may need a
git rebase before you can merge it.

Bill.

**Pull request closed without merging**
