### PR TITLE
Popov form

### PR DESCRIPTION
**Pull request by thofma**
(Weak) popov form from Johannes.

The `det_popov` gives a nice speedup for determinants of matrices over polynomial rings over finite fields:

```julia
julia> F = ResidueRing(ZZ, 3); Fx, x = PolynomialRing(F, "x");

julia> m = Matrix(Fx, 50, 50, [ sum([ rand(0:3)*x^i for i in 1:10]) for j in 1:50*50]);

julia> @benchmark det(m)
BenchmarkTools.Trial: 
  memory estimate:  616.47 MiB
  allocs estimate:  423674
  --------------
  minimum time:     1.948 s (1.11% GC)
  median time:      1.951 s (1.11% GC)
  mean time:        1.956 s (1.12% GC)
  maximum time:     1.969 s (1.16% GC)
  --------------
  samples:          3
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%

julia> @benchmark det_popov(m)
BenchmarkTools.Trial: 
  memory estimate:  3.86 MiB
  allocs estimate:  78267
  --------------
  minimum time:     136.612 ms (0.00% GC)
  median time:      150.648 ms (0.00% GC)
  mean time:        152.557 ms (1.85% GC)
  maximum time:     184.164 ms (10.18% GC)
  --------------
  samples:          33
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
```

Here is the corresponding magma command

```
> F := FiniteField(3); 
> Fx<x> := PolynomialRing(F);
> M := Matrix(Fx, 50, 50, [ &+[ Random(F)*x^i : i in [1..10]] : j in [1..50*50]]); 
> time _ := Determinant(M);
Time: 0.150
```

I would say we are pretty close.

### CODE REVIEW

**Comment by thofma** [comment]
I guess I have to rebase this or something like that.

**Comment by wbhart** [comment]
We can use triangular dispatch from recent Julia here:

function det{S <: FinFieldElem, T <: PolyElem{S}}(M::MatElem{T})

**Comment by thofma** [comment]
This won't help with `GenMat{nmod_poly}`.

Also the methods only work with `GenMat` and not `MatElem` since we do things like `add!(A[i,j], ...)` to update matrix entries inplace.

I could do
```
function det{S <: FinFieldElem, T <: PolyElem{S}}(M::GenMat{T})
```
and something separate for
```
function det(M::GenMat{nmod_poly})
```

**Comment by wbhart** [comment]
On 30 May 2017 at 16:09, thofma <notifications@github.com> wrote:

> This won't help with GenMat{nmod_poly}.
>

True.  But nmod_poly is not a poly over a finite field. If the algorithm
works there too, then there has to be something separate.

Also the methods only work with GenMat and not MatElem since we do things
> like add!(A[i,j], ...) to update matrix entries inplace.
>
Currently there is no way to create a matrix over a polynomial over a
finite field without it being a GenMat. So it shouldn't matter. I guess it
is possible Singular.jl could have a way of creating matrices over
polynomials that are not GenMat's, so you are probably right. May as well
restrict to GenMat.

> I could do
>
> function det{S <: FinFieldElem, T <: PolyElem{S}}(M::GenMat{T})
>
> Yep.

>  and something separate for
>
> function det(M::GenMat{nmod_poly})
>
> Yep, if it works there.

**Comment by thofma** [comment]
I just noticed that triangular dispatch is only available in julia 0.6. Can we just merge this and I open an issue so we won't forget it?

**Comment by wbhart** [comment]
Yeah if you like. The thing is, the code will never get called for determinant at present, unless someone knows about it.

**Comment by thofma** [comment]
I know. But without triangular dispatch it is a real pain. So let's
postpone this.

**Comment by wbhart** [comment]
Is there really enough performance benefit to using Val{True} and Val{false} to justify all the extra complexity in the function prototypes? Isn't popov form quite expensive, and therefore a standard 

popov(..., with_trafo=false)

popov_with_trafo(...) = popov(..., true)

much better?

Is there even a need for the explicit _with_trafo version of the function?

**Comment by wbhart** [comment]
Also, am I reading the test code correctly that it only tests two specific matrices? Isn't there some randomised test you can do as well?

**Comment by wbhart** [comment]
The alternative is to just add a check for the right version of Julia
around the appropriate determinant functions.

**Comment by wbhart** [comment]
i.e. they can still call your existing det_popov for now.

**Comment by thofma** [comment]
If you do it without the Val, you introduce type instability, since the return type of popov is a tuple of matrices or just a single matrix.

The test code is the same as in every test file. Just do a few hardcoded examples.

I guess that julia 0.6 is right around the corner (juliacon is in 3 weeks). When we switch to 0.6 we already have to change a lot of things, so this here would just go to that list.

I am not sure I understand it with the julia version check.

**Comment by wbhart** [comment]
Note in your benchmark above, rand(0:3) generates a random value between 0
and 3 inclusive, which means it is more likely to generate zeroes in the
finite field. Also you don't have any constant coeffiicients, since you
start at i = 1.

However, I timed something similar in Sage, with the appropriate
corrections to give uniformly distributed elements:

R.<x> = PolynomialRing(Integers(3))
M = matrix(R, 50, 50, lambda i, j : R.random_element(10) -
R.random_element(10))

It takes 7.6s on my computer. It would be interesting to correct your
benchmark code and try it with your code.

**Comment by wbhart** [comment]
On 30 May 2017 at 16:59, thofma <notifications@github.com> wrote:

> If you do it without the Val, you introduce type instability, since the
> return type of popov is a tuple of matrices or just a single matrix.
>
> The test code is the same as in every test file. Just do a few hardcoded
> examples.
>
Most of the complex generic matrix code uses randomised testing. We really
need to start moving Nemo towards this for all generic modules. Obviously
it isn't the case for power series and polynomial modules at present. E.g.
things like resultant should be tested randomly.

> I guess that julia 0.6 is right around the corner (juliacon is in 3
> weeks). When we switch to 0.6 we already have to change a lot of things, so
> this here would just go to that list.
>
> I am not sure I understand it with the julia version check.
>
I mean you can have a static if to check if the julia version is 0.6 and
inside the body of the static if, define the appropriate det functions,
which will use triangular dispatch  and simply call your det_popov
function. Obviously those functions won't be available in earlier versions
of Julia.

**Comment by wbhart** [comment]
Incidentally, for randomised testing, I think we should introduce some
functions "random_element" like Sage has. But we can do it better in Julia.

You could have random_element(M::MatrixSpace, vs...) where the additional
parameters vs are any parameters needed for generating random entries to go
in the matrix, e.g. degree bounds on polynomials, etc.

For example, in the popov case, we could do:

R = ResidueRing(ZZ, 3)
S, x = PolynomialRing(R, "x")
M = MatrixSpace(S, 50, 50)

m = random_element(M, 10)

which would generate a random matrix with random degree 10 polynomials. The
random_element function for M would simply pass its extra parameters (in
this case 10) on to the random_element function for the base_ring of M,
which in this case is S. So each entry of m would be set to
random_element(S, 10), which would mean a random polynomial with degree up
to 10 (or degree 10 as Sage has it).

I think we can make this work.

**Comment by thofma** [comment]
Here are the updated timings (did not change):
```julia
julia> m = Matrix(Fx, 50, 50, [ sum([ rand(0:2)*x^i for i in 1:10]) for j in 1:50*50]);

julia> @benchmark det_popov(m)
BenchmarkTools.Trial: 
  memory estimate:  3.85 MiB
  allocs estimate:  79283
  --------------
  minimum time:     131.774 ms (0.00% GC)
  median time:      139.480 ms (0.00% GC)
  mean time:        153.514 ms (1.95% GC)
  maximum time:     227.526 ms (0.00% GC)
  --------------
  samples:          33
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
```
Sage is taking 5.3s on my machine.

I will introduce some static version check and I will change the test code to do some randomized stuff.

I also agree with your `random_element` idea. But I won't do it in this PR.

**Comment by wbhart** [comment]
No need to do the random_element stuff in this PR, obviously. It's enough to just use the existing random functions at the top of Matrix.jl. We can change it later.

I'm just trying out some code to do random matrices. We need random bigints first!

**Comment by wbhart** [comment]
Here's some code to illustrate what is possible:
```
import Base:rand, colon
using Nemo

rand(R::FlintIntegerRing, r::UnitRange{Int}) = R(rand(r))

function rand{T <: RingElem}(M::MatSpace{T}, vs...)
   m = M()
   for i = 1:M.rows
      for j = 1:M.cols
         m[i, j] = rand(base_ring(M), vs...)
      end
   end
   return m
end

function rand{T <: RingElem}(R::PolyRing{T}, n::Int, vs...)
   x = gen(R)
   f = R()
   for i = 0:n
      f += rand(base_ring(R), vs...)*x^i
   end
   return f
end

function rand{T <: RingElem}(R::ResRing{T}, vs...)
   return R(rand(vs...))
end

function rand(R::ResRing{fmpz})
   m = convert(Int, R.modulus)
   return R(rand(0:m - 1))
end

R, x = PolynomialRing(ZZ, "x")
M = MatrixSpace(R, 10, 10)

m1 = rand(M, 2, -5:5)

S = ResidueRing(ZZ, 3)
T, y = PolynomialRing(S, "y")
N = MatrixSpace(T, 10, 10)

m2 = rand(N, 2, 0:2)
m3 = rand(N, 2)
```

**Comment by wbhart** [comment]
You are still doing "for i = 1:10" in your benchmark, whereas the Sage code
is equivalent to "for i = 0:10"

**Comment by thofma** [comment]
Oops. Now proper timings:
```
julia> @benchmark det_popov(m)
BenchmarkTools.Trial: 
  memory estimate:  4.13 MiB
  allocs estimate:  83899
  --------------
  minimum time:     144.090 ms (0.00% GC)
  median time:      149.705 ms (0.00% GC)
  mean time:        156.486 ms (2.07% GC)
  maximum time:     180.820 ms (9.96% GC)
  --------------
  samples:          33
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
```

**Comment by wbhart** [comment]
So, it looks like a really good speedup. I think we should make this one of
our benchmarks on the website when it is merged.

**Comment by wbhart** [comment]
Ready to merge?

**Pull request merged**
