### PR TITLE
Clean up matrix constructors

### PR DESCRIPTION
**Pull request by joschmitt**
Use proper error objects.

### CODE REVIEW

**Comment by thofma** [comment]
Don't merge, it is failing on master.

**Comment by thofma** [comment]
Fixed it. But wait for travis and appveyor.

**Comment by wbhart** [comment]
I only see Travis. Is Appveyor on summer break?

**Comment by wbhart** [comment]
All the new functions of the form arb_mat(M) are a bit strange. We should be overloading the call functions for the matrix spaces, shouldn't we, i.e. so that it is R(M), where R is the matrix space. Even if we wanted functions that used the type name instead of the parent object, we'd use the Julia approach to doing this, which is convert(arb_mat, M).

**Comment by wbhart** [comment]
Oh wait, I see these are constructors. Carry on!

**Pull request merged**
