### PR TITLE
Enh/acb integrate

### PR DESCRIPTION
**Pull request by kalmarek**
Please take a careful look, I am really not experienced in `C`.

With this pull You can e.g.:
```julia
const FF = AcbField()
Nemo.integrate(x -> x^2, FF(0), FF(1))
Nemo.integrate(sin, FF(0), 2const_pi(FF))
```

TODO:

- [ ] documentation
- [ ] tests

Note: this does not allow to pass additional parameters to the integrand. Should it?

Also: should I rewrite history (i.e. prepare a new branch with clean commits)?

### CODE REVIEW

**Comment by wbhart** [comment]
It looks like it tries to include a file acb_struct, which I don't see (I assume it is no longer needed).

**Comment by thofma** [comment]
Thanks. I want to play with it a bit before I merge it.

**Comment by kalmarek** [comment]
Sure, that's what I asked for.

I've already found that this is not GC-safe??:
```julia
for i in 1:10000
    @time Nemo.integrate(x -> x^2 ,CC(-1), CC(1))
end
```
```
0.003962 seconds (981 allocations: 57.355 KiB)
  0.000092 seconds (212 allocations: 8.922 KiB)
  0.000048 seconds (212 allocations: 8.922 KiB)
  0.000044 seconds (212 allocations: 8.922 KiB)
  0.000045 seconds (212 allocations: 8.922 KiB)
  0.000043 seconds (212 allocations: 8.922 KiB)
  0.000042 seconds (212 allocations: 8.922 KiB)
  0.000042 seconds (212 allocations: 8.922 KiB)

.....

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
unknown function (ip: 0x7f78ba8f96e1)
unknown function (ip: 0x7f78ba8fa5f2)
unknown function (ip: 0x7f78ba8fa16e)
unknown function (ip: 0x7f78ba8fe500)
jl_gc_collect at /usr/lib/libjulia.so.0.6 (unknown line)
jl_gc_pool_alloc at /usr/lib/libjulia.so.0.6 (unknown line)
Type at /home/kalmar/.julia/v0.6/Nemo/src/arb/ArbTypes.jl:80
Type at /home/kalmar/.julia/v0.6/Nemo/src/arb/acb.jl:1630
jl_apply_generic at /usr/lib/libjulia.so.0.6 (unknown line)
acb_calc_func_wrap at /home/kalmar/.julia/v0.6/Nemo/src/arb/acb_calc.jl:7
unknown function (ip: 0x7f789467eb76)
acb_calc_integrate_gl_auto_deg at /home/kalmar/.julia/v0.6/Nemo/deps/arb/acb_calc/integrate_gl_auto_deg.c:191
acb_calc_integrate at /home/kalmar/.julia/v0.6/Nemo/deps/arb/acb_calc/integrate.c:220
#integrate#38 at /home/kalmar/.julia/v0.6/Nemo/src/arb/acb_calc.jl:28
unknown function (ip: 0x7f789467e9a6)
jl_apply_generic at /usr/lib/libjulia.
```

**Comment by thofma** [comment]
Yes, the handling of the pointers etc is not quite correct. It is a little bit complicated to explain. Do you mind if I open a new PR based on the commits here? For this it would be helpful if you could squash the commits here into one (rewrite the history).

**Comment by fredrik-johansson** [comment]
I would suggest extending the interface right away to support non-analytic/branch cut-containing integrands (we did it by passing a flag to the object function in Sage) as well as wrapping the optional settings (tolerances etc.).

**Comment by wbhart** [comment]
Julia can't know what Arb still has pointers to. It only knows about the
objects it created and that it still has references to.

Also, unsafe_blah means it is unsafe from the point of view of garbage
collection. The object needs to be kept alive manually, since Julia doesn't
know to keep it alive automatically.

Having said that, I've no idea what the specifics of your code are here.
I'll let Tommy and Fredrik respond.

**Comment by thofma** [comment]
@fredrik-johansson 
```python
        RR = RealField()
        if rel_tol is None:
            cgoal = self._prec
        else:
            tmp = <RealNumber> RR(rel_tol)
            mpfr_get_d_2exp(&cgoal, tmp.value, MPFR_RNDD)
            cgoal = -cgoal
```
Stupid question. Ignoring the sign change at the end, we want `2^cgoal <= rel_tol`, right? After looking at the documentation of `mpfr_get_d_2exp`, I think we have `rel_tol >= tmp * 2^cgoal >= 2^(cgoal - 1)` (because `0.5 <= tmp <= 1`). Is there a +/- 1 missing?

**Comment by wbhart** [comment]
Sorry there is a minor rebase of this PR that is needed after a particularly large and unwieldy patch was merged. We have now completely split Nemo.jl and AbstractAlgebra.jl and updated all the docs accordingly. Apart from minor bugs that might manifest through use, there are no similarly large merges planned in the near future (famous last words).

**Comment by thofma** [comment]
I have a local branch where I have this thing here almost working. I will finish it soon.

**Comment by thofma** [comment]
Sorry for the delay. I think it is best to wait until 0.7 is released. Then `cfunction` will also support closures, see https://github.com/JuliaLang/julia/pull/26486. This will make everything much easier.

**Comment by vtjnash** [comment]
If the C library follows modern conventions and provides some sort of `void*` environment pointer, you're much better off going with that than using the closure support. Otherwise, where you once had one bug with your handling of pointers, now you'll have three.

**Comment by thofma** [comment]
Thanks for chimming in @vtjnash. Is https://julialang.org/blog/2013/05/callback still the recommended way? Is there an example somewhere in Base?

**Comment by vtjnash** [comment]
Yes

There are many examples. They aren't much changed from the blog post.

**Comment by kalmarek** [comment]
@thofma any chances of this happening soon? Could You publish Your branch so that I can play with/study Your solution?

**Comment by thofma** [comment]
My solution had some other flaws, so I took yours and fixed the memory problem. See
https://github.com/Nemocas/Nemo.jl/pull/407

**Comment by kalmarek** [comment]
fixed by https://github.com/Nemocas/Nemo.jl/pull/407

**Pull request closed without merging**
