### PR TITLE
Fix inv for nmod_mat/fmpz_mod_mat

### LINKED ISSUE #956: inv fails for nmod_mat
```
julia> R = ResidueRing(ZZ,9)
julia> G = matrix(R,2,2,[2,1,1,2])
[2  1]
[1  2]
julia> inv(G)
Flint exception (Impossible inverse):
    Cannot invert modulo 2*0
ERROR: Problem in the Flint-Subsystem
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] flint_abort() at .../.julia/packages/Nemo/mmz6V/src/Nemo.jl:118
 [3] inv(::nmod_mat) at .../.julia/packages/Nemo/mmz6V/src/flint/nmod_mat.jl:443
 [4] top-level scope at REPL[303]:1
```
It appears also for other residue rings
```
julia> R = ResidueRing(ZZ,9)
Integers modulo 9julia> G = matrix(R,2,2,[3,1,1,3])
[3  1]
[1  3]
julia> inv(G)
Flint exception (Impossible inverse):
    Cannot invert modulo 3*0
ERROR: Problem in the Flint-Subsystem

```
As far as I can tell the problem occurs when the entry at [1,1] is not invertible.

### PR DESCRIPTION
**Pull request by thofma**
Stopgap to fix #956, #685, #504.

Alternatively/additonally we can `try` `nmod_mat_inv` first and catch the error. Not sure if this is a good idea?

### CODE REVIEW

**Comment by wbhart** [comment]
This will be massively slower, won't it?

If so, shouldn't a test for primality be made first in nmod_mat and a probable prime test for fmpz_mod_mat. Or catch the error first as you suggest, though you will have to pipe stdout/stderr to /dev/null or something first.

**Comment by thofma** [comment]
The primality test sounds like a good idea. We are doing something similar already for `det`.

**Comment by thofma** [comment]
Changed it according to your suggestion.

**Comment by wbhart** [comment]
I can see you added the two individual tests for this. But is pseudo_inv actually tested somewhere extensively for Z/nZ?

The main problem with the new approach is of course that for Z/nZ where n is not prime, it no longer tries the much faster inv first (if n is sufficiently large it would almost always succeed), but instead it now always incurs the slowdown of pseudo_inv.

Leaving aside the question of what the optimal approach would be, assuming we had time to implement it (e.g. some CRT or p-adic approach), it may very well be that for very small composite n the approach of running inv first and catching the exception is actually slower on average than going directly to pseudo_inv, but I suspect n doesn't have to be too large before this is no longer the case.

So I do think the approach you've implemented leads to a performance degradation. Are you sure you are ok with that? Catching an exception doesn't seem like too much of a bother to implement.

**Comment by thofma** [comment]
The `pseudo_inv` was already used for `inv` of `fmpz_mod_mat`, because we were always calling https://github.com/Nemocas/AbstractAlgebra.jl/blob/2ba7fee2dd26cc23f36a0e0a6c4f096b24873ad6/src/generic/Matrix.jl#L2941
So yes, it is tested.

I can also do the try catch. For `nmod_mat`, does this work properly with flint? Will all the memory be cleaned up? I don't know much about exceptions on the C side, so I ask first.

**Comment by wbhart** [comment]
Good point. No it is not. There are some permutations and matrix windows which are not cleaned up. So I guess your approach is the best after all.

I will merge the version with the primality check. It's far from optimal, but the best we can do for now.

**Comment by wbhart** [comment]
I would have just called inv if the probable prime test passed, given that this is only a stop gap. But I'll merge it as is.

**Comment by thofma** [comment]
There is no way to call `inv`, because we are defining it at this point.

**Comment by wbhart** [comment]
Yeah, there is also that. Sorry, I hadn't quite noticed we didn't have it in Flint yet.

**Pull request merged**
