### PR TITLE
Introduce Generic module and make test suite pass.

### PR DESCRIPTION
**Pull request by wbhart**
This PR introduces a Generic submodule of Nemo.

Once again I recommend checking it out in a branch and updating Hecke to work with this, before merging the PR. The process is as follows:

* GenBlah -> Generic.Blah

* If there are functions that should be exported from Generic which aren't currently, do the following:
  -- export it from the relevant generic file, e.g. Poly.jl
  -- in Nemo.jl import the symbol from .Generic around line 195
  -- in Nemo.jl export the symbol from Nemo around line 229

* If there are functions which are in Base that aren't being exported from Nemo, import them from Base in Nemo.jl and in Generic.jl

* If there are ambiguities with fmpz functions, ambiguities.jl is no longer in use. Instead, go into src/flint/adhoc.c and insert the relevant disambiguations (they must actually be implemented, and may not just return nothing). Just copy and paste one of the other functions in that file and modify its prototype.

### CODE REVIEW

**Comment by wbhart** [comment]
Note that GenBlah includes perm and other Groups types which weren't previously called GenBlah.

**Comment by thofma** [comment]
We should just make the changes in Nemo and then we will update Hecke afterwards. I think it is better to do it only once.

I forgot what our plan was for the functions which do not belong into the generic module, but which work for all abstract types like all `PolyElem` objects. Where do they go?

**Comment by wbhart** [comment]
All these changes are already made in Nemo. The branch is ready to merge, assuming Travis passes.

At some point we'll have to make separate files for all the abstract types. But this is an enormous job which can't be done just yet. It involves rewriting a lot of code, because it's currently been done very badly (by me). But the interface should not change at all.

**Comment by wbhart** [comment]
I have no idea why Travis is failing. The code is literally as follows:

```
julia> R, x = PolynomialRing(ZZ, "x")
(Univariate Polynomial Ring in x over Integer Ring, x)

julia> typeof(R)
Nemo.FmpzPolyRing

julia> @which one(R)
one(a::Nemo.FmpzPolyRing) in Nemo at /home/wbhart/.julia/v0.7/Nemo/src/flint/fmpz_poly.jl:45
```
It must be another bug in nightlies.

**Comment by wbhart** [comment]
I fixed the issue. The Julia folks have now defined isone, as of this commit [1]

I put conditional imports and defines in the code so we only define it if they don't.

[1] https://github.com/JuliaLang/julia/commit/b11aec6fef4ddefb9e8fb503c365f6fdf846afc1#diff-c39f3bbf0cb1c2381243b42647d9ff1d

**Comment by thofma** [comment]
Yes, this is not new. We already had the conditional important: https://github.com/Nemocas/Nemo.jl/blob/master/src/Nemo.jl#L58-L60

**Pull request merged**
