### PR TITLE
Polynomial constructor, similar and zero for Nemo polynomial types

### PR DESCRIPTION
**Pull request by wbhart**
This is the Nemo counterpart to https://github.com/Nemocas/AbstractAlgebra.jl/pull/843 and requires that PR to pass.

It almost certainly breaks Hecke as it already has similar functions.

### CODE REVIEW

**Comment by thofma** [comment]
New AA version (0.17) is released. Can you update the Project.toml (also in docs/Project.toml)? I still can't push directly :-/

**Comment by wbhart** [comment]
Sure, sorry for the delay. It thinks I am a first time contributor, so no worries.

**Comment by wbhart** [comment]
Do you want the same thing for the other Nemo PR's?

**Comment by thofma** [comment]
Lets see if closing and opening of the other PRs helps.

**Pull request merged**
