### PR TITLE
use the right fmpz_poly_set_nmod_poly

### PR DESCRIPTION
**Pull request by tthsqe12**
fixes https://github.com/Nemocas/Nemo.jl/issues/1330

### CODE REVIEW

**Comment by thofma** [comment]
Do you want to add a test where it was 'wrong'?

**Comment by tthsqe12** [comment]
already did

**Comment by thofma** [comment]
Where? The tests added are passing also on the current version.

**Comment by tthsqe12** [comment]
oops, my bad

**Comment by thofma** [comment]
thanks!

**Pull request merged**
