### PR TITLE
Adjust to AbstractAlgebra 0.10

### PR DESCRIPTION
**Pull request by thofma**
Includes #841.

### CODE REVIEW

**Comment by wbhart** [comment]
Should we ignore the nightly failure?

**Comment by thofma** [comment]
Yes, it was failing before we touched the flint version.

**Comment by wbhart** [comment]
Are there any doc changes needed?

**Comment by thofma** [comment]
I checked again and it seems no (which is weird). They never mention the `prec` function.

**Comment by wbhart** [comment]
Yeah the Nemo docs are severely abbreviated and just refer to AbstractAlgebra (which I plan to change one day when things have stabilised even more).

**Comment by fingolfin** [comment]
Can this be merged then and a new release be made, please?

Also: can close #863

**Comment by thofma** [comment]
Merging yes. New release? Probably not so quickly. There are other things that I want to adjust (printing). Also I rather wait for the outcome of https://github.com/Nemocas/Nemo.jl/issues/862 and see if we need to adjust things.

**Comment by wbhart** [comment]
In my opinion there is really a lot of work to make the changes for #862 and to fix issues with the division functions inside Nemo #842. There's also AA#554 and AA#555. I would not wait for those before making a release.

**Pull request merged**
