### PR TITLE
Fix minor issues in gcd and setcoeff!.

### PR DESCRIPTION
**Pull request by wbhart**
Fixes a couple of minor bugs.

### CODE REVIEW

**Comment by thofma** [comment]
Can we give a more helpful error message if the gcd call fails?

**Comment by wbhart** [comment]
I'm not sure. What do you think @tthsqe12

At the moment I think it can fail for a number of reasons.

**Comment by wbhart** [comment]
Got it:

"Computer says no!"

https://www.youtube.com/watch?v=0n_Ty_72Qds

**Comment by wbhart** [comment]
Daniel says it's hard to formulate a reason. The nearest thing would be "exponents too large", though this could be misleading.

**Pull request merged**
