### PR TITLE
Use karatsuba where appropriate.

### PR DESCRIPTION
**Pull request by wbhart**

### CODE REVIEW

**Comment by thofma** [comment]
The error downstream is real:
```julia
julia> Qx, x = QQ["x"];

julia> K, a = NumberField(x - 1, "a", cached = false);

julia> Kt, t = K["t"]
(Univariate Polynomial Ring in t over K, t)

julia> zero(Kt) * zero(Kt)
ERROR: DivideError: integer division error
```

**Comment by wbhart** [comment]
You mean there is still really a bug on this branch or that the error lies elsewhere and is not to do with this branch?

**Comment by thofma** [comment]
The error is thrown in `usekaramul`.

**Comment by wbhart** [comment]
Oh I see. I'll investigate.

**Pull request merged**
