### PR TITLE
Add documentation for padic module.

### PR DESCRIPTION
**Pull request by wbhart**

### CODE REVIEW

**Comment by thofma** [comment]
Test is failing for 0.5:
https://s3.amazonaws.com/archive.travis-ci.org/jobs/142013852/log.txt

**Comment by wbhart** [comment]
Passes on 0.5 for me. I think they've screwed something up.

**Comment by thofma** [comment]
How recent is your 0.5?

This is the version of the travis build:
```
Julia Version 0.5.0-dev+5124
Commit be46ceb* (2016-07-03 11:58 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)
```

**Comment by wbhart** [comment]
Mine is older. But if you look at the error, it is complaining about a missing call function. It's certainly not missing, or it wouldn't work on my Julia. I think they have a bug. I'll look into it tomorrow.

**Pull request merged**
