### PR TITLE
remove banner message

### LINKED ISSUE #817: Welcome message
First of all, thanks for your work on Nemo, very useful to me!

I am annoyed by the welcome message. It is a bit intrusive (it is the only Julia package I know that does this) and it also appear when Nemo is loaded as a dependency so it may not be relevant at all for the user. And you already know that this is an issue because there is a special condition to disable the welcome message when Nemo is loaded from Oscar or Hecke ;)

Could you please remove this welcome message?

### PR DESCRIPTION
**Pull request by stevengj**
Fixes #817.

### CODE REVIEW

**Comment by rfourquet** [comment]
I don't think you will get support in removing entirely the banner. Maybe the developers would agree with a solution which makes it easier for users to disable it though.

**Comment by stevengj** [comment]
See the discussion in Polymake.jl#257 … it seems that the developers incorrectly believe that the GPL requires a welcome banner?

**Comment by rfourquet** [comment]
Yes it's my understanding that @wbhart thinks that it's a legal requirement. I didn't realize a discussion on this topic was happening on the polymake repo, let's keep it there.

**Comment by wbhart** [comment]
@stevengj Please do not post legal opinion as though it were fact. We reserve the right to remove future comments on this issue if it starts getting out of hand.

**Comment by stevengj** [comment]
I directly quoted the text of the GNU GPL saying that you "need not" add legal notices where they are displayed.   I also cited examples of both GPL libraries and interactive programs from the GNU project itself that do not display banners in interactive programs. 

I think both the license and the precedent are pretty clear here.  That is an opinion, but I think it is well supported.

(I am not a lawyer, but I have worked on GPL software, including GNU projects, including in consultation with lawyers, for several decades now.  That doesn't mean my opinions are gospel, but it does help me to quickly find the relevant authorities and precedents.)

**Pull request closed without merging**
