### PR TITLE
Remove pari

### PR DESCRIPTION
**Pull request by thofma**
As discussed.

### CODE REVIEW

**Comment by rfourquet** [comment]
Do you have a link to the discussion? And was this code migrated to a standalone pari package? (or is there such a plan?) Thanks!

**Comment by wbhart** [comment]
A lot of the discussion was done offline, actually. The people using Nemo
were complaining about Pari takng over the signal handler, which makes
debugging really difficult. We had a lot of discussion (offline) about what
features from Pari we were really using. Once this functionality was
available in Flint or Hecke, we decided to remove Pari.

Since the Pari interface code was written, we have learned a lot about how
to wrap libraries (e.g. see Singular.jl), and we think that the Pari code
wasn't worth keeping as a standalone library. It would be nice to have a
standalone Pari.jl that is compatible with Nemo.jl, but no one is working
directly on this at the moment.

Was there something you were using in Pari, that you need?

**Comment by defeo** [comment]
Just my 2 cents: I would love to have a Pari.jl library. So, if you guys have an opinion on it, I would love to hear it.

**Comment by rfourquet** [comment]
Thanks for your detailled answer! It's just that I'm a little more familiar with pari, and that I regularly find myself opening gp (and copy pasting to my julia console...). Since I switched to Julia I thought it would be great to wrap it, but for my actual needs Nemo will be probably enough, so I guess it's time for me to learn it. That said, it would probably be interesting to indeed have an "Pari.jl" package, to sometimes be able to compare the results or the speed of the algos. Would you mind if someone picks-up this deleted code as a starting point for a separate package?

**Comment by wbhart** [comment]
Of course we're happy for people to use our deleted code. I think one can
do much better, but it's a starting point.

**Pull request merged**
