### PR TITLE
Fix fq embed

### PR DESCRIPTION
**Pull request by tthsqe12**

### CODE REVIEW

**Comment by wbhart** [comment]
The code looks ok, but what are the limitations here?

Does any of the gfp_fmpz_mat stuff rely on Flint functionality only found in 2.9?

How similar is this to the existing embed module? Would the embeddings be compatible with the ones the fq_nmod_embed module would produce, assuming it could cover all cases?

Is the PR complete? (It seems to pass and there looks to be good test code, so I assume so. Just want to check.)

**Comment by wbhart** [comment]
Compatibility of embeddings is an important issue. The idea is that there is a lattice of embeddings which is mutually compatible.

If you are simply doing what is done elsewhere in Nemo/flint2 for embeddings then no problems. If not, then that would be problematic.

**Comment by tthsqe12** [comment]
It think it is fine as I just copied and pasted some code and changed a few names here and there.

**Comment by wbhart** [comment]
It's ok, you are using fq_embed_gens and fq_embed_matrix.

When I saw the factorisation code being called I thought that perhaps you were doing something custom. This all looks fine.

**Comment by fingolfin** [comment]
Any blockers to merging this?

**Comment by tthsqe12** [comment]
Ah, I just need to write some more tests to get the coverage up. We gotta get off of eighty-eight percent coverage.

**Comment by tthsqe12** [comment]
@thofma just 0.02% away from 89%. Maybe some of the other PRs will fill the gap.

**Comment by ThomasBreuer** [comment]
Thanks, @tthsqe12!

**Pull request merged**
