### PR TITLE
Add basic fq_default wrapper

### PR DESCRIPTION
**Pull request by wbhart**
Requires flint-2.8 or a development snapshot after the fq_default branch is merged.

### CODE REVIEW

**Comment by wbhart** [comment]
@thofma Don't forget this works with flint-2.8

**Comment by thofma** [comment]
Error looks like a real problem.

**Comment by wbhart** [comment]
Yeah I have no idea what is causing it though.

**Comment by wbhart** [comment]
It's not failing locally.

**Comment by tthsqe12** [comment]
I can reproduce locally the crash in fq_default_poly_length.

**Comment by wbhart** [comment]
It doesn't fail locally with Julia-1.5 or 1.6.

**Comment by tthsqe12** [comment]
Indeed. It looks like a problem with the jll. Will investigate...

**Comment by wbhart** [comment]
Ok, I think I found the issue.

**Comment by wbhart** [comment]
The context object was missing in the call to length.

**Comment by tthsqe12** [comment]
Yup, that will do it.

**Comment by tthsqe12** [comment]
All of the fq_poly's in the union have the length at the same offset, so our local compilers are free to optimize out the ctx switch. But not the humble jll compiler ... :(

**Comment by wbhart** [comment]
@thofma Seems to pass now.

**Comment by tthsqe12** [comment]
Funny thing: this is in fact exactly what was happening. My (and presumably yours):
```
00000000008f5ce0 <fq_default_poly_length>:
  8f5ce0:	f3 0f 1e fa          	endbr64 
  8f5ce4:	48 8b 47 10          	mov    0x10(%rdi),%rax
  8f5ce8:	c3                   	retq   
  8f5ce9:	0f 1f 80 00 00 00 00 	nopl   0x0(%rax)
```

The one from the jll (terrible compiling...):
```
00000000008fa170 <fq_default_poly_length>:
  8fa170:	8b 06                	mov    (%rsi),%eax
  8fa172:	83 f8 01             	cmp    $0x1,%eax
  8fa175:	74 11                	je     8fa188 <fq_default_poly_length+0x18>
  8fa177:	83 f8 02             	cmp    $0x2,%eax
  8fa17a:	48 8b 47 10          	mov    0x10(%rdi),%rax
  8fa17e:	74 10                	je     8fa190 <fq_default_poly_length+0x20>
  8fa180:	f3 c3                	repz retq 
  8fa182:	66 0f 1f 44 00 00    	nopw   0x0(%rax,%rax,1)
  8fa188:	48 8b 47 10          	mov    0x10(%rdi),%rax
  8fa18c:	c3                   	retq   
  8fa18d:	0f 1f 00             	nopl   (%rax)
  8fa190:	f3 c3                	repz retq 
  8fa192:	66 66 66 66 66 2e 0f 	data16 data16 data16 data16 nopw %cs:0x0(%rax,%rax,1)
  8fa199:	1f 84 00 00 00 00 00 
```

**Comment by thofma** [comment]
The GCC version used is quite ancient (I think it is 4.8 something). Could this explain the difference?

**Comment by tthsqe12** [comment]
sure

**Pull request merged**
