### PR TITLE
fix some title strings in tests

### PR DESCRIPTION
**Pull request by rfourquet**

### CODE REVIEW

**Comment by rfourquet** [comment]
I recommend hiding whitespace changes while reviewing. A couple a files were in some sort of DOS mode, which my editor modified, so they appear to be completetly updated without "hiding whitespace changes".

**Comment by wbhart** [comment]
@rfourquet The diff seems artificially large. Do you have any insight into why this is?

**Comment by wbhart** [comment]
Ah, I thought we had it set up to ignore whitespace. Typically I set up my git config to always check out in native. This way we don't have revert wars every time someone uses a new editor.

**Comment by rfourquet** [comment]
Alright, I got confused, I actually didn't change the mode away from DOS initially, but then many `^M` appeared locally in my diff, which turned out to simply mean that some spaces have been deleted (my editor also automatically removes useless spaces at end-of-lines), so I manually switched away from DOS. I agree this big diff is annoying, but I think it would be better to have one convention and stick to it.

**Comment by wbhart** [comment]
It's not better for people who use the other convention. The better way to fix this is to ensure git is set up correctly, which is supposed to make this problem irrelevant. Whenever you check out, it automatically changes the line endings for your OS, then when you commit, it doesn't make huge commits.

Having said that, I don't know off the top of my head what the magic commands are you need to type to set your git up to handle this automatically.

**Comment by rfourquet** [comment]
> It's not better for people who use the other convention

I find no convention (i.e. a mix of different conventions) worse than sticking to one convention (even if it's not mine). But of course that's my personal preference.

**Comment by wbhart** [comment]
There is a convention, and we use it, namely to set your git up so it doesn't happen. It's a standard problem when working with contributors from other OS's. You can't just demand that they have an OS other than the one they have!

**Comment by thofma** [comment]
The DOS encoded files in the repo are quite annoying. We should not have accepted them in the first place.

**Comment by wbhart** [comment]
Change them if you want. But you aren't going to be able to convince people to change their OS, editor or other tools for development. We are talking about files that were contributed by Fredrik. Are you just going to tell Windows developers to go away?

**Comment by thofma** [comment]
Hmm no, but we need to find this setting :)

**Comment by wbhart** [comment]
https://help.github.com/en/articles/configuring-git-to-handle-line-endings

**Comment by thofma** [comment]
Thanks!

**Pull request merged**
