### PR TITLE
Update mpolynomial.md

### PR DESCRIPTION
**Pull request by mforets**
Closes https://github.com/Nemocas/Nemo.jl/issues/789.

fix broken links

### CODE REVIEW

**Comment by wbhart** [comment]
Was this the only file? I thought there were similar links in quite a few .md file.

**Comment by mforets** [comment]
True, there are others eg. in https://nemocas.github.io/AbstractAlgebra.jl/euclidean.html from http://nemocas.github.io/Nemo.jl/latest/integer.html#Integer-functionality-1 . 
i can update this PR (later) with those fixes.

**Comment by wbhart** [comment]
Thanks, that would be fantastic.

**Comment by thofma** [comment]
I am inclined to merge this as is, since it fixes at least some links.

**Comment by mforets** [comment]
> i can update this PR (later) with those fixes.

shame on me :disappointed:

**Comment by thofma** [comment]
It is not a problem if you don't find time to do it.

**Comment by thofma** [comment]
Fixed on master.

**Pull request closed without merging**
