### PR TITLE
rename perm -> Perm

### PR DESCRIPTION
**Pull request by rfourquet**
DO NOT MERGE (yet): needs a new AA release (cf. https://github.com/Nemocas/AbstractAlgebra.jl/pull/433).

### CODE REVIEW

**Comment by thofma** [comment]
I bumped the AA version. Will merge once everything is green.

**Comment by rfourquet** [comment]
Thanks! But it won't be green, as the `rand` stuff (#631) needs updating too.

**Comment by thofma** [comment]
Ah, my bad. I just started at the top of the remaining PRs.

**Comment by rfourquet** [comment]
I mean, it's not possible to have everything green in each PR, so we have to start somewhere anyway! (except by putting all breaking related changes in the same PR).

**Comment by thofma** [comment]
Yes, indeed.

**Pull request merged**
