### PR TITLE
trafo->transform, update AbstractAlgebra dependency accordingly.

### PR DESCRIPTION
**Pull request by wbhart**

### CODE REVIEW

**Comment by wbhart** [comment]
No rush to merge this if it is causing any issues. I just needed to update it on my machine so the Nemo tests would pass with the latest AbstractAlgebra.

**Comment by thofma** [comment]
Doesn't seem to pass tests.

**Comment by wbhart** [comment]
It must be pulling an older AbstractAlgebra. We changed the name of this function, so the tests don't pass for me without this change.

Is there something else I need to do to get it to pull the latest AbstractAlgebra?

**Comment by thofma** [comment]
It is pulling 0.4.8, see https://api.travis-ci.org/v3/job/532266255/log.txt.

Are you sure that your recent changes are included in 0.4.8?

**Comment by wbhart** [comment]
Perhaps that is the issue. I guess we have to wait until the next release before this PR is needed (at which point I will have to update the deps).

**Pull request merged**
