### PR TITLE
Generic Hermite normal form

### PR DESCRIPTION
**Pull request by thofma**
Implementation of the Kannan--Bachem algorithm by Johannes. Provides generic Hermite and Smith normal form implementations.

Also a vanilla Hermite normal form a la Cohen.

### CODE REVIEW

**Comment by thofma** [comment]
History looks weird. Should be squashed when merged.

**Comment by wbhart** [comment]
Currently the functions for upper triangular matrices are called blah_triu.
Feel free to change blah_upper_triangular to blah_triu or vice verse (docs
will also need to be changed).

Otherwise, looks really great to me.

**Comment by thofma** [comment]
Changed.

**Comment by wbhart** [comment]
I'm happy with this patch. It looks like the Travis failure is unrelated to
the code.

You mentioned something about squashing commits, which I don't personally
care about. Is there something you want done there?

**Comment by fredrik-johansson** [comment]
upper_triu sounds kind of redundant...

**Comment by thofma** [comment]
```
[ 1 1 ]
[ 0 1 ]
```
and
```
[ 1 0 ]
[ 1 1 ]
```
are both triangular? In fact it must be something like `upper_right_triu`.

**Comment by fredrik-johansson** [comment]
The first is upper triangular, the second is lower triangular.

triu = upper triangular, tril = lower triangular

upper_triu means upper_triangular_upper...

I'd be fine with upper_triangular and lower_triangular, but Julia uses tril and triu, and Flint does too, so the short names are probably standard enough that there won't be much confusion.

**Comment by thofma** [comment]
Thanks for opening my eyes. I always thought the `u` of `triu` is the `u` of `triangular`. So `triu` literally means triangular upper? I will make the changes.

**Comment by thofma** [comment]
Changed.

**Pull request merged**
