### PR TITLE
New gcd

### PR DESCRIPTION
**Pull request by wbhart**
Speeds up removal of content in univariate gcd. Also puts divides function in every ring and adds trail and ismonomial functions for polynomials.

### CODE REVIEW

**Comment by thofma** [comment]
The `divides` test is failing for `fq_poly` and `fq_nmod_poly`.

**Comment by wbhart** [comment]
There's a bug in flint, which I fixed in trunk. I guess the dlls need
updating.

**Comment by wbhart** [comment]
I don't know why travis is failing at the same point. The tests pass for me
with the Flint fix.

**Comment by thofma** [comment]
Because we have fixed the flint version in build.jl.

**Comment by wbhart** [comment]
Was there any reason for that? I forgot.

**Comment by thofma** [comment]
It came up on METADATA while I was trying to tag a new release.

**Comment by wbhart** [comment]
Oh that, Yeah I remember. We really have to stop doing releases through
METADATA.

**Pull request merged**
