### PR TITLE
Laurent series rings and fields (generic only)

### PR DESCRIPTION
**Pull request by wbhart**

### CODE REVIEW

**Comment by wbhart** [comment]
I don't think the failure on 0.6 on Travis can have anything to do with this PR. I've no idea how that can just fail now. It's not failed before.

**Comment by thofma** [comment]
It happens if the array has lenght zero. Then elements will have type Any.
One can just annotate the array when constructing it to have the correct
type.

**Comment by fredrik-johansson** [comment]
Why not implement Laurent series as a power series + leading exponent?

Then we don't need a separate implementation of Laurent series for every base ring that already has a fast implementation of power series.

**Comment by wbhart** [comment]
@fredrik-johansson I want to do Puiseaux series based on these. Each level adds more garbage collection, so I don't want to increase it any more.

**Comment by fredrik-johansson** [comment]
How about basing both Laurent and Puiseux series directly on power series then?

**Comment by wbhart** [comment]
I think Puiseaux series would be too hard to do in terms of PowerSeries.

**Comment by wbhart** [comment]
I could consider doing an abstract LaurentSeries implementation directly in terms of polynomials, designed to work with Flint polynomials. This would cut down the number of implementations necessary without making things too expensive for gc.

**Comment by wbhart** [comment]
Yeah, actually, I think you are right. We should do an Abstract implementation of both Laurent and Puiseaux series in terms of AbsSeries. This cuts down the number of implementations we need. We probably should do the same for RelSeries too.

I still prefer to have a separate implementation of Laurent and RelSeries for Generic though, and same for PuiseauxSeries.

**Comment by thofma** [comment]
So should we merge this here?

**Comment by wbhart** [comment]
You can if you want. I'm not even sure about an abstract Laurent module.
It's not as trivial as I thought and I don't know if I'll have time to
implement it soon or not.

**Pull request merged**
