### PR TITLE
exponent_vector: check that exponents fit Int

### PR DESCRIPTION
**Pull request by rfourquet**
Found out with @tthsqe12.

### CODE REVIEW

**Comment by wbhart** [comment]
Do you also want to make the changes to switch over to the new _si functions @tthsqe12 just added to Flint? This will require rebuilding the libraries, for which you will have to talk to @thofma.

**Comment by tthsqe12** [comment]
This is such a basic operation and should be as fast as possible. Therefore, I recommend using the si functions and relying on flint's faster internal checking for overflow. You can always call `degrees_fit_si` on the whole polynomial before you start to process individual exponents.

**Comment by rfourquet** [comment]
Oups, I should have checked you PR on Flint... Yes, let's use Flint's new functions, although I'm not clear that it will be noticeably faster (I would assume the allocation of the vector makes the checks negligible, whether ther are done on the Flint side or Julia side).
I will update the PR when the new version of Flint is availble to Nemo.

**Comment by thofma** [comment]
We have updated the binaries.

**Comment by rfourquet** [comment]
> We have updated the binaries.

Thanks!

So, I did one basic benchmark, and for a simple `f = x^64` of type `fmpz_mpoly`, `exponent_vector(f, 1)` is about 2% or 3% slower (*) if we also have a check on the julia side (which allows to throw a more specific `DomainError`). What do you prefer?

(*) like 1ns slower for a total of 40ns, not sure it's really meaningful

**Comment by wbhart** [comment]
It's fine, so long as the correct function is called on the Flint side.

**Pull request merged**
