### PR TITLE
fix docs for FlintFiniteField

### PR DESCRIPTION
**Pull request by rfourquet**
This merges duplicated docstring for the version taking a characteristic, and merges implementation for the version taking a polynomial (currently the online docs are not showing the polynomial version because one docstring was missing so Documenter was not even showing the existing one).

### CODE REVIEW

**Comment by wbhart** [comment]
I don't think Integer is correct here in the Union. It should be Int, from memory. The Int version uses a different implementation of finite fields which is more efficient, but is limited to small characteristic, and this probably should be mentioned in the docstring.

**Comment by wbhart** [comment]
It's also relevant for embeddings, since embeddings are currently only available for the version with small Int. And if you have one type of finite field, you can't compatibly embed with another type. So the user needs to know that the two are distinct.

**Comment by rfourquet** [comment]
> I don't think Integer is correct here in the Union. It should be Int,

I didn't touch that part, there was `fmpz` in one signature, `Integer` in the other, I just merged them in `Union{fmpz, Integer}`. And it 
seems to be fine as the integer is converted to `fmpz`.

> It's also relevant for embeddings, since embeddings [...]

I don't really understand this, is it related to the previous comment on `Int` vs `Integer`? I don't know how the embeddings stuff works.... If there is a simple change I can make here to make it more correct, please tell me. But AFAICT, this PR currently changes nothing to the logic of the functions/docstring, except it adds one docstring to a function which didn't have one.

**Comment by wbhart** [comment]
It's ok, you are right. This is just a fallback method. It is not called for Int.

This PR is fine.

**Pull request merged**
