### PR TITLE
use at-testset instead of test_* functions

### PR DESCRIPTION
**Pull request by rfourquet**
Companion to https://github.com/Nemocas/AbstractAlgebra.jl/pull/424.
I observe here almost a 2x speedup! (1m55s vs 3m45)

It allowed me to find that a handful of test functions were not run, and failed when run manually. I still transformed them into a `@testset` but guarded by `if false`. I don't know if someone was aware of that, but at least now it's easy to find the faulty tests and try to fix them.

Also, I had to switch few files away from DOS mode, because my regexes wouldn't work on them...

### CODE REVIEW

**Comment by wbhart** [comment]
If they failed and were previously commented out, we know about them. If they weren't commented out, they should be failing tests and fixed (when we get time).

**Comment by rfourquet** [comment]
They weren't commented out, the functions were just not called (i.e. not included in the list of functions calls at the end of the files), so it was difficult to spot just by skimming through the files.

**Comment by thofma** [comment]
We can sort this out later.

**Comment by wbhart** [comment]
Could you enable them and we'll work through them one by one. Feel free to open another PR for that.

**Comment by rfourquet** [comment]
> Could you enable them and we'll work through them one by one. Feel free to open another PR for that.

Sure I can, but the problem is that CI will always fail until these are fixed, which doesn't seem ideal. I was rather meaning to open an issue referencing specifically these failing tests. But sure if you confirm I will open a PR enabling them.

**Comment by wbhart** [comment]
I don't mean that we will merge the PR. I mean that we can push fixes to that PR until it is working. Hopefully it won't take *that* long to sort them all out (or decide they have to remain turned off).

**Comment by rfourquet** [comment]
OK got it!

**Pull request merged**
