### PR TITLE
Load flint

### PR DESCRIPTION
**Pull request by fieker**
try the new LoadFlint package to load libflint

### CODE REVIEW

**Comment by fingolfin** [comment]
This fails in the Windows builds with this error:
```
ERROR: LoadError: InitError: too many gmp
```
It seems Flint is pulling in a second copy of GMP? I wonder if that's a bug in the FlintBuilder or "normal". We can probably find out by trying what happens if one load e.g. MPFR into Julia (which also uses GMP) -- if that has the same issue, it's "normal", if it doesn't, then perhaps we are doing something wrong?

Another option would be for LoadFlint to simply iterate over all GMP instances and call `__gmp_set_memory_functions` for each of them.

**Comment by fingolfin** [comment]
I fixed the bug and released LoadFlint 0.1.2 -- @fieker please restart the Travis jobs for this PR

**Comment by fingolfin** [comment]
Actually, I just created my own version of this PR, see #819

**Comment by fieker** [comment]
On Sun, Mar 22, 2020 at 03:09:02PM -0700, Max Horn wrote:
> This fails in the Windows builds with this error:
> ```
> ERROR: LoadError: InitError: too many gmp
> ```
> It seems Flint is pulling in a second copy of GMP? I wonder if that's a bug in the FlintBuilder or "normal". We can probably find out by trying what happens if one load e.g. MPFR into Julia (which also uses GMP) -- if that has the same issue, it's "normal", if it doesn't, then perhaps we are doing something wrong?
> 
> Another option would be for LoadFlint to simply iterate over all GMP instances and call `__gmp_set_memory_functions` for each of them.
I would not call set_momory on someone elses function... they might have
other ideas. Its annoying: in Oscar we dont' care about native windows
(no polymake and I think no singular anyway)


But it now seems to work! Geat, thanks

**Comment by fieker** [comment]
On Sun, Mar 22, 2020 at 06:04:24PM -0700, Max Horn wrote:
> Actually, I just created my own version of this PR, see #819
Good!
Now we can consider merging..
I give Bill a chance to have a look...

**Pull request closed without merging**
