### PR TITLE
Implement new linear solving interface

### PR DESCRIPTION
**Pull request by joschmitt**
Implements the new linear solving interface in AbstractAlgebra for `QQMatrix`.
~This is currently based on #1632 to have AbstractAlgebra@0.36 available; I will rebase once we're at Nemo@0.40.~

I did not implement a special backend for the solving with a solve context. I don't see how we can do this differently for `QQMatrix` (assuming that `rref`/`echelon_form` calls flint in the background).
~Also, there does not seem to be a method to compute the kernel in flint, so the generic code is called for this. So I'm not sure how 'efficient' `can_solve_with_solution_and_kernel` is (I assume that the matrix is reduced twice).~
I also implemented `nullspace` for `QQMatrix`.

### CODE REVIEW

**Comment by joschmitt** [comment]
I added the necessary functions for the other flint types (except `zzModMatrix` because flint does not support solving if the modulus is not prime I think).
This needs https://github.com/Nemocas/AbstractAlgebra.jl/pull/1566 , so no CI for now.
If we don't want to do the whole release cycle again just because I forgot the kernel in AA before, I can also adjust to avoid using `AbstractAlgebra.Solve.kernel` for now.

**Comment by thofma** [comment]
I will tag a new AA with the kernel changes later today.

**Comment by joschmitt** [comment]
> I will tag a new AA with the kernel changes later today.

Thank you.

**Comment by thofma** [comment]
Done

**Comment by joschmitt** [comment]
I implemented functions for all the C types now, but this needs further new functionality in AbstractAlgebra (which I just have locally so far).
I'll work on special functions for solving with a `SolveCtx` next which will probably need more adjustments to AbstractAlgebra.

**Comment by joschmitt** [comment]
Is there a renaming script? Because I also added new methods using the old types.

**Comment by lgoettgens** [comment]
At the bottom of https://hackmd.io/ONVPdlfARgWzkfkNkcJkgA

**Pull request merged**
