### PR TITLE
Hack to make threaded flint working

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by wbhart** [comment]
Should we wait to see what happens with the PR @benlorenz pointed out? What do you think?

It looks like it could potentially fix the problem on Linux at least.

**Comment by thofma** [comment]
I don't mind too much. Given how long https://github.com/JuliaLang/julia/pull/27020 and https://github.com/JuliaLang/julia/pull/32254 have been stalling, it will take a few months before this makes it into a julia release (if this happens at all).

**Comment by wbhart** [comment]
Thanks. @thofma

**Comment by kalmarek** [comment]
yes, that's unfortunately true, the patch is small enough, but it already has slipped through twice, so I wouldn't bet on fast merging even after it's rebased onto master

**Pull request merged**
