### PR TITLE
add gcd_with_cofactors for mpolys

### PR DESCRIPTION
**Pull request by tthsqe12**
The new code is tested indirectly, so it should work with or without the AA changes.

### CODE REVIEW

**Comment by thofma** [comment]
Won't this create two independent `AA.gcd_with_cofactors` and `Nemo.gcd_with_cofactors` function? Or was it there already?

**Comment by tthsqe12** [comment]
there is a meta loop in nemo that imports lots of stuff from AA. If AA doesn't have it, there will be an unexported Nemo.gcd_with_cofactors. If AA does have it, it will get imported. I think it works because the test code doesn't reference it directly.

**Comment by tthsqe12** [comment]
16.66% is my lowest score. I suppose you want me to export it here and test it directly.

**Comment by thofma** [comment]
We can also quickly tag the new AA. What do you prefer?

**Comment by tthsqe12** [comment]
no, let's tag it slowly

**Comment by thofma** [comment]
OK, then please add the tests here.

**Pull request merged**
