### PR TITLE
Try to get Win32 working

### PR DESCRIPTION
**Pull request by thofma**
Just want to trigger appveyor, don't merge.

### CODE REVIEW

**Comment by thofma** [comment]
@wbhart Do you remember which of the following downloads I need to build the Win32 binaries?
https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/5.3.0/threads-win32/seh/

**Comment by wbhart** [comment]
I think it is x86_64-win32-seh.

**Comment by thofma** [comment]
Thanks. I'll give it a try.

**Comment by wbhart** [comment]
By the way, I'm implementing power series sqrt in Flint at the moment.
We'll want to include that in Nemo. Unless the win32 binaries are urgent,
or you can leave the setup running somewhere so you don't have to reinstall
it next time we want to update the binaries, it might be worth waiting
until I've finished with the power series code in Flint.

I don't know how long it will take, but I might have it working over Z in a
couple of days.

**Comment by thofma** [comment]
Thanks for letting me know.

But if I get them running, it won't be a problem to update them.

**Comment by thofma** [comment]
Did not suceed. I try again 2019.

**Pull request closed without merging**
