### PR TITLE
Add repo address to README.

### PR DESCRIPTION
**Pull request by wbhart**
Try to stop so many people reporting issues to my repo instead of the official one.

### CODE REVIEW

**Comment by slel** [comment]
Visiting the official repo on GitHub one reads "forked from wbhart/Nemo.jl"
which could lead some to assume yours is the main repo. Good to clarify.

**Comment by wbhart** [comment]
I've closed off issues on my repo, added a note to the description with a link to the official repo and put a note in the README. There isn't a lot else I can do, short of deleting my repository.

**Comment by slel** [comment]
Nothing more to do. I wish GitHub would provide an option to revert
the direction of which repo is displayed as being a fork of the other.
Sorry for the noise.

**Comment by thofma** [comment]
If we really want this, we could in principle contact the github support and ask them to do it.

**Comment by wbhart** [comment]
There are a few people who forked directly from me, rather than the
official repo. I'm not sure they can do it without orphaning those.

**Comment by rfourquet** [comment]
> If we really want this, we could in principle contact the github support and ask them to do it.

Last time I checked, I also understood that contacting them would be the solution. This would also help when making PRs by pushing a branch to Nemocas/Nemo.jl, as currently github proposes by default to make the PR against wbhart/Nemo.jl (even when the "make a PR" button is clicked from Nemocas/Nemo.jl)

**Comment by wbhart** [comment]
I think it is more complicated than that. GitHub derives the "main" package from the tree of forks. Because of how Git works, someone can't propose a PR against a package they weren't ultimately forked from, as there is no compatible history.

So the problem is really that there are forks from my repo that occurred before the forks from the community repo.

I propose that we ask people on the nemo-devel list to refork their repos from the main one, and I'll do the same at a time when I don't have any PR's open. That way everyone who wants to will be able to make PR's against the main repo if they want to.

**Pull request merged**
