### PR TITLE
Julia int

### PR DESCRIPTION
**Pull request by wbhart**
This is all working now. However, I want to document it. (I have tested every generic function to ensure it works with the new types.)

You can do:

R, x = PolynomialRing(Nemo.JuliaZZ, "x")
R, x = PolynomialRing(Nemo.JuliaQQ, "x")
R, x = PolynomialRing(Nemo.zz, "x")
R, x = PolynomialRing(Nemo.qq, "x")

to work over BigInts, Rational{BigInt}s, Ints or Rational{Int}s, respectively. And it all seems to work just fine.

There are new parents: Integers{<: Integer} and Rationals{<:Integer}
There are new unions: RingElement and FieldElement which include RingElem and FieldElem respectively, along with Julia Integers and Rationals.

### CODE REVIEW

**Comment by wbhart** [comment]
Passes now. No idea why it didn't pass before. Apparently using Union{Integer, Rational} instead of Integer makes it pass. But this is a bit crazy since it was just fine on Julia-0.7-dev.

**Comment by wbhart** [comment]
By the way, do you know if the Julia people are aware of the segfault in the nightlies?

**Comment by thofma** [comment]
Yes, it is here https://github.com/JuliaLang/julia/issues/23078

**Comment by wbhart** [comment]
Thanks.

**Pull request merged**
