### PR TITLE
Add type `NegInf` representing negative infinity

### PR DESCRIPTION
**Pull request by fingolfin**
Also expand the functionality of `PosInf` to match.

I have deliberately not yet tried to make use of this anywhere, e.g. for the degree of a zero polynomial, as that would likely be a breaking change and thus for a separate PR.

Moreover, it seems to me that this functionality actually should perhaps be moved to AbstractAlgebra... But one step after the other.

### CODE REVIEW

**Comment by thofma** [comment]
Looks good. You added some `signbit` methods, which are not used. Could one just loop over more elements in one of the tests?

**Comment by fingolfin** [comment]
I removed `Base.signbit(x::acb)`, as there also is no `signbit` for `Complex` (though there *is* a `sign` method with weird semantics).

Due to the funky official semantics for `sign` I also removed these (they are actually for an extension of ours which takes an additional argument; but I did not find a definition for them)
```
Base.sign(::Type{Int}, ::PosInf) = +1
Base.sign(::Type{Int}, ::NegInf) = -1
```

For the rest I added more tests. I also added `isfinite` / `isinf` methods for `QQFieldElem` (and fixed `isinf(::ZZRingElem)`, oops).


The existing tests for fmpz, fmpq etc. seem to be rather flaky, too. E.g. things like `iseven` are often tested with a single input (if in doubt, always an input that leads to `true` as output).

**Comment by fingolfin** [comment]
@thofma OK now?

**Review by thofma — APPROVED** [review]

**Comment by lgoettgens** [comment]
> Moreover, it seems to me that this functionality actually should perhaps be moved to AbstractAlgebra... But one step after the other.

I can try to include this in https://github.com/Nemocas/Nemo.jl/pull/1531 in the upcoming days.

**Comment by thofma** [comment]
I overlooked one failure in the doctests of Oscar. I mark this here as breaking.

**Comment by fingolfin** [comment]
Ahhhh, the printing changed and one doctests prints `PosInf()`, dang

**Pull request merged**
