### PR TITLE
Fmpz mod

### PR DESCRIPTION
**Pull request by thofma**
I updated the reference and moved the stuff out of Matrix.jl

I am afraid there is no better name than ppio. It computes both ppi and ppo as defined in Bernstein's paper.

### CODE REVIEW

**Comment by wbhart** [comment]
Yeah, looks good. I'll merge as soon as Travis is happy.

**Comment by wbhart** [comment]
The second error on Travis looks like it is my problem. The first error could be due to this PR.

**Comment by thofma** [comment]
With first error do you mean the solve_rational error?

**Comment by wbhart** [comment]
Looks like the Julia nighlies are borked. I'm inclined to just merge this without waiting. What do you think?

**Comment by wbhart** [comment]
By the way, is there any chance we could keep the import and export statements in Nemo in alphabetical order!

**Pull request merged**
