### PR TITLE
Change default return type of `order(::Group)`

### PR DESCRIPTION
**Pull request by lgoettgens**
As pointed out by @fingolfin in https://github.com/Nemocas/AbstractAlgebra.jl/pull/1528#discussion_r1425147632.

This requires https://github.com/Nemocas/AbstractAlgebra.jl/pull/1572 to be available.

### CODE REVIEW

**Comment by lgoettgens** [comment]
This doesn't work, as AbstractAlgebra code cannot see dispatches introduced in Nemo and below.
@fingolfin do you have any other idea on how to achieve this?

**Comment by thofma** [comment]
I think one way would be to have (in AA):
```
order(G::Group) = _order(G)
_order(G) = order(BigInt, G)
```
and the in Nemo
```
_order(G::Group) = order(ZZRingElem, G)
```
At least this is a trick I use for other things to overload the "generic" method.

**Comment by lgoettgens** [comment]
Thanks @thofma, that indeed works (at least locally).
https://github.com/Nemocas/AbstractAlgebra.jl/pull/1572 contains the required change in AA.

**Comment by lgoettgens** [comment]
@thofma can you merge and tag this? (the required invalidations job block disables me from doing it)

**Pull request merged**
