### PR TITLE
add continued fractions (and more divrem rounding modes)

### PR DESCRIPTION
**Pull request by tthsqe12**
@albinahlback after various discussions I decided to normalize the `s` in `(g, s, t) = gcd(a, b)` so that `s` is the unique representative `mod b/g`. Unfortunately your `ndivrem` for `fmpz` doesn't work here because it can round ties either up or down. It has to consistently round ties in a fixed direction in order to provide a unique representative for classes `mod b`. Can we change the flint function `fmpz_ndiv_qr` to do what my `nudivrem` does here? This would actually correspond to a named rounding mode in julia :).

### CODE REVIEW

**Comment by albinahlback** [comment]
So I actually think it's pretty nice to have `ndiv` defined this way, since it behaves similarly regardless of the input's sign. However, if other types of rounding at ties are needed, I'm all for it. Maybe something like
```
ndiv -> ntdiv
n stands for nearest integer, t for rounding towards zero (at ties)

nfdiv
n stands for nearest intefer, c for ceil/rounding towards +infinity at ties

etc
```

**Comment by wbhart** [comment]
I see the WIP removed, however the title still says "start ...". Also there is still some discussion. Let me know when you are ready for this to be reviewed.

**Comment by tthsqe12** [comment]
should be good now

**Review by wbhart — APPROVED** [review]
Looks ok. I prefer the section headings to start with a capital letter. Also, there is more here than continued fractions, and that could be reflected in the title. But looks like a lot of careful work.

The smod function will be particularly useful for some applications of mine. Thanks for adding that. We probably should add something similar to AA.

**Comment by tthsqe12** [comment]
@thofma this is going to have conflicts now. I will fix them along with some typos.

**Pull request merged**
