### PR TITLE
Add Julia floating point types to Nemo hierarchy

### PR DESCRIPTION
**Pull request by wbhart**
This PR does the following:

* Add a new parent Floats{T <: AbstractFloat}
* Add missing functions for Julia floating point types
* Add Julia floating point types to Nemo Fields hierarchy
* Add tests for Julia Integers, Rationals, Floats
* Fix some minor bugs

Ready to merge.

### CODE REVIEW

**Comment by thofma** [comment]
Are these BigFloat's supposed to be useful or do you just want to test the generic code?

**Comment by wbhart** [comment]
These are mainly for testing the generic code for inexact fields, of
course. There's no really interesting functionality.

**Comment by thofma** [comment]
I can imagine some interesting applications, but then one would have to wrap the BigFloat's slightly different. Similar to arb objects, one should track the precision in the parent object and move away from the global precision thing. So you could have a julia real field with 128 bit precision and one with 256 bit precision at the same time.

**Comment by wbhart** [comment]
That's right. I decided not to do that, since Julia itself uses a global
precision. The object here is just to make the Julia types available to
Nemo, rather than to create a new type.

**Comment by thofma** [comment]
I see.

**Pull request merged**
