### PR TITLE
move and remove common stuff for AbstractAlgebra

### PR DESCRIPTION
**Pull request by fieker**

### CODE REVIEW

**Comment by wbhart** [comment]
The imports for FractionField and PermutationGroup are currently not in the right place, and perhaps the exports should not be in Fraction.jl but in Nemo.jl along with the other exports.

**Comment by fieker** [comment]
On Sat, Mar 10, 2018 at 06:25:15AM -0800, wbhart wrote:
> The imports for FractionField and PermutationGroup are currently not in the right place, and perhaps the exports should not be in Fraction.jl but in Nemo.jl along with the other exports.

There is actually more wrong.... I'll have a look on monday

**Comment by wbhart** [comment]
You are exporting ZZ, QQ, PadicField, FiniteField twice.

**Comment by thofma** [comment]
Fixed.

**Pull request merged**
