### PR TITLE
Add fmpz_mod module

### PR DESCRIPTION
**Pull request by wbhart**
This adds an fmpz_mod module based on Flint.

Tests pass, but require the latest version of Flint in which a minor bug is fixed.

Currently fmpz_mod_poly still works with Generic.Res{fmpz}'s rather than the new fmpz_mod's. I can switch that over and add it to this PR if preferred. Or we can do this step by step.

### CODE REVIEW

**Comment by thofma** [comment]
Tests are failing. I guess we also need `gfp_fmpz_elem` which just mirrors `fmpz_mod_elem`, similar to `nmod_elem` and `gfp_elem`?

Also the name `GaloisField` for the parent of `gfp_elem` is not optimal anymore, since we now also need `GaloisFieldFmpz`?

**Comment by wbhart** [comment]
Yeah tests are failing due to the mentioned bug in Flint, which is fixed in trunk.

**Comment by thofma** [comment]
Where is this bug mentioned?

**Comment by rfourquet** [comment]
> Where is this bug mentioned?

In the OP:

> Tests pass, but require the latest version of Flint in which a minor bug is fixed.

**Comment by thofma** [comment]
Oops. Thanks!

**Comment by wbhart** [comment]
I've now added gfp_fmpz_elem/GaloisFmpzField. I've also updated gfp_fmpz_poly to use it.

I don't think I'll implement gfp_fmpz_mat since we don't even have gfp_mat yet, I think.

But next I'll implement fmpz_mod_mat in terms of what is in Flint. If you prefer that in a separate PR, let me know.

**Comment by thofma** [comment]
I have pushed the new flint binary version to this PR here.

You can decide if we should merge this now or after you added the matrices.

**Comment by wbhart** [comment]
I will merge this now, I think.

**Pull request merged**
