### PR TITLE
Fix `lu!` requiring real matrices to be square.

### PR DESCRIPTION
**Pull request by mjrodgers**
The Nemo call to the method `lu!` for real matrices was previously requiring the matrices to be square. This method calls to the `arb` library, which does not actually require the matrices to be square.

This pull request fixes issue #1498 which arises because the call to `is_invertible_with_inverse` relies on `rref` which functions correctly within `AbstractAlgebra`, but when called from `Nemo` (or `Oscar`), uses `Nemo`'s `lu!` method instead of `AbstractAlgebra`'s and then fails on non-square matrices.

You can see this issue within Nemo or Oscar:
```
mm=MatrixSpace(RealField(),1,2)([1,2])
rref(mm)

ERROR: Matrix must be square
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] lu!(P::Perm{Int64}, x::RealMat)
   @ Nemo ~/.julia/packages/Nemo/EuCgH/src/arb/RealMat.jl:499
 [3] rref!(A::RealMat)
   @ AbstractAlgebra ~/.julia/packages/AbstractAlgebra/YkCOC/src/Matrix.jl:1880
 [4] rref(M::RealMat)
   @ AbstractAlgebra ~/.julia/packages/AbstractAlgebra/YkCOC/src/Matrix.jl:1943
 [5] top-level scope
   @ REPL[11]:1
```

### CODE REVIEW

**Comment by thofma** [comment]
Would you mind adding a test? That would great.

**Comment by mjrodgers** [comment]
@thofma I have added a test for this. 

It seems there are some... weird things in the behavior of the `lu` methods.

Nemo defines its own `lu`/`lu!` calls for various types, that sometimes overwrite the `AbstractAlgebra` functions, and are inconsistent with the `AbstractAlgebra` methods.  Mostly in that most of the methods calling to the `Arb` library (in some way) require the matrices to be square, which clashes with what these methods get used for (solving systems of equations, reducing to rref). The actual Arb library call does not seem to require this (at least for the `RealMat` and `ComplexMat` calls). Here is a list, I only fixed the one for `RealMat` at the moment but it could be worthwhile to fix all of them.
```julia
function lu!(P::Generic.Perm, x::acb_mat)
function lu(P::Generic.Perm, x::acb_mat) # requires square matrix

function lu!(P::Generic.Perm, x::arb_mat) # requires square matrix
function lu(x::arb_mat, P = SymmetricGroup(nrows(x)))

function lu!(P::Generic.Perm, x::ComplexMat)
function lu(P::Generic.Perm, x::ComplexMat) # requires square matrix

function lu!(P::Generic.Perm, x::RealMat) # requires square matrix (until this pull request)
function lu(x::RealMat, P = SymmetricGroup(nrows(x)))
```

I'm having trouble testing the actual behavior for `arb_mat` and `acb_mat` types because I can't seem to construct matrices of these types reliably.
```julia
julia> M_arb = arb_mat(2,3, [1,1,1,1,1,1])
[#undef   #undef   #undef]
[#undef   #undef   #undef]
```

**Comment by thofma** [comment]
```
julia> RR = ArbField(64)
Real Field with 64 bits of precision and error bounds

julia> matrix(RR, 2, 3, [1,2,3,4,5,6])
[1.0000000000000000000   2.0000000000000000000   3.0000000000000000000]
[4.0000000000000000000   5.0000000000000000000   6.0000000000000000000]

julia> typeof(ans)
arb_mat
```
(Replace `ArbField` by `AcbField` to obtain `acb_mat`).

If it is not too much hassle, it would be good to fix it for all types.

**Comment by mjrodgers** [comment]
I've basically got it fixed for all types; for the complex types though, it's strange: the `lu` functions have signature 
```julia
function lu(P::Generic.Perm, x::ComplexMat)
```
and return only `L, U` whereas for the AbstractAlgebra methods (and the Nemo methods for Real/Arb matrices) the signature is 
```julia
function lu(x::RealMat, P = SymmetricGroup(nrows(x)))
```
and they return `r, p, L, U` (rank, permutation + the L and U matrices).

What this means is that the current Nemo tests for these complex lu methods don't even call the Nemo versions, they are falling back to the AbstractAlgebra versions.

I can change these signatures/return values so they all match; or maybe it's better even to remove all four of these `lu` methods and let the AbstractAlgebra ones be called in all cases (this would still use the specialized calls to `lu!` that use `arbLib`). What do you think, make them match, or remove and just use AbstractAlgebra generic methods?

**Comment by mjrodgers** [comment]
Okay I removed the four `lu()` methods to go with the AbstractAlgebra generic versions, and removed the checks in the `lu!()` methods after verifying that this didn't break anything (and added checks for the `lu` methods on nonsquare matrices). This should be ready to merge.

**Comment by mjrodgers** [comment]
There are actually more issues with this. These `arbLib` `lu!` functions break all sorts of things... For example, in current master branch of Nemo/Oscar, we can't
1. compute an `rref` for a matrix that is not square and invertible
2. find the rank of a matrix that is square and invertible...
This is because these rely on computing the lu factorization, which seems to fail in strange cases.

Which this pull request, some of these issues are fixed. But the rank is not accurately returned, and we still can't compute the rref for a square noninvertible matrix (and probably some other cases).

I honestly think we should remove these `arbLib` calls for `lu!` entirely, they completely break some core functionality for real and complex matrices in Nemo and Oscar.

**Comment by thofma** [comment]
Asking for the rank of a matrix of intervals is not too useful. (The rank of the 1x1 matrix [0 +/- 0.1] must be an interval containing {0,1}). Most of the linear algebra routines in AA are broken for non-exact domains, which is why we want to have the LU decomposition call via arblib.

What other core functionality is broken? Is there some code relying on it?

**Comment by mjrodgers** [comment]
Echelon forms is broken. You can't compute them in oscar for example
```julia
M_r =MatrixSpace(RealField(),3,3)([1,1,1,  0,1,-1, 1,1,1])
julia> rref(M_r)
ERROR: Could not find 3 invertible pivot elements
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] lu!(P::Perm{Int64}, x::RealMat)
   @ Nemo ~/.julia/packages/Nemo/EuCgH/src/arb/RealMat.jl:505
 [3] rref!(A::RealMat)
   @ AbstractAlgebra ~/.julia/packages/AbstractAlgebra/YkCOC/src/Matrix.jl:1880
 [4] rref(M::RealMat)
   @ AbstractAlgebra ~/.julia/packages/AbstractAlgebra/YkCOC/src/Matrix.jl:1943
 [5] top-level scope
   @ REPL[3]:1
```

**Comment by mjrodgers** [comment]
But if we take out the `lu!()` call that uses `arbLib`, the generic AbstractAlgebra `lu!()` does return what we would want, and allows us to compute the rref of this matrix.

**Comment by thofma** [comment]
The generic methods in AA for non-exact rings are bogus:
```
julia> RR = RealField()
Real field

julia> a = RR("0 +/- 0.1")
[+/- 0.101]

julia> lu(RR[RR("0 +/- 0.1")])^C

julia> lu(RR[a a; a a])
(2, (), [1.0000000000000000000 0; nan 1.0000000000000000000], [[+/- 0.101] [+/- 0.101]; 0 nan])

julia> rank(matrix(RR, 1, 1, [a]))
1
```
If you are lucky, you get something that is correct by accident. In most cases, you get silently wrong results.

**Comment by mjrodgers** [comment]
Okay, I understand. So then the current state of this pull request leaves the `arbLib` calls to `lu!` in place, with the caveat that the rank returned is sometime not correct; it allows computing `rref` in some situations where it would previously would throw an error, but will still throw an error in other situations.

(I can't actually at the moment find an example where the rank is incorrect, I thought I had one but was maybe mistaken - only cases where the rank can't be found because `lu` fails.)

**Comment by mjrodgers** [comment]
Okay, I understand. So then the current state of this pull request leaves the `arbLib` calls to `lu!` in place, with the caveat that the rank returned is sometime not correct; it allows computing `rref` in some situations where it would previously would throw an error, but will still throw an error in other situations.

This is using `arbLib` version of `lu!` with the check for square matrices removed.

```julia
julia> RR = RealField()
Real field

julia> M =MatrixSpace(RR,3,2)([0,1,1,  1,0,-1])
[                    0    1.0000000000000000000]
[1.0000000000000000000    1.0000000000000000000]
[                    0   -1.0000000000000000000]

julia> rank(M)
3
```

**Comment by mjrodgers** [comment]
I realize that the documentation says the matrix needs to be square, although this does not seem to be true in practice. Fixing just the inverse in the way you propose still leaves the issue of computing echelon forms (and leaves the `lu` functionality inconsistent with other same-named methods that don't require square matrices).

What about using the `gr_mat_lu` described [here](https://flintlib.org/doc/gr_mat.html#c.gr_mat_lu) as an alternative? It says that this method can be "mixed freely with methods in the corresponding Flint, Arb and Calcium modules", does not require the matrices to be square, and will return an error if it "fails to certify that a pivot element is zero or nonzero". It still probably makes sense to (separately) overload the methods for computing the inverse.

**Comment by thofma** [comment]
The `gr_*` methods will be part of flint 3.0, but this has not been released yet. We are at 2.9 at the moment, so we cannot use those.

**Comment by mjrodgers** [comment]
Ah okay, thanks for the reply.

**Comment by thofma** [comment]
I pushed a temporary fix for the last wrong rank example you posted. I think you are right, and we should give the `gr_mat_*` methods a try as soon as they are available.

I think this is now good to go, what do you think? Then we can address the 'real' issue with the inverse failing :)

**Comment by mjrodgers** [comment]
This looks good to me! I will work on the inverse, and take a look at using these `gr_mat` methods once they are available.

**Pull request merged**
