### PR TITLE
make ZZ and friends const

### PR DESCRIPTION
**Pull request by rfourquet**
Similar to https://github.com/Nemocas/AbstractAlgebra.jl/pull/457.

### CODE REVIEW

**Comment by wbhart** [comment]
I think this belongs with the related AbstractAlgebra patch and both should go into compatible versions. So I will hold off merging this until there is a new version of Nemo, since @thofma just tagged a new release of AbstractAlgebra.

**Comment by thofma** [comment]
yeah, but we don't have to do a major release for this, minor should be ok

**Comment by rfourquet** [comment]
As far as I can tell, this patch and AA's patch are, although related, totally independant functionally. Technically these changes are breaking, but probably no-one was using this feature (being able to change the binding).

**Comment by wbhart** [comment]
Ok.

**Comment by wbhart** [comment]
Any insight into the test errors? Should we just restart the build and see if it works?

**Comment by thofma** [comment]
Oops, my bad. Can you rebase?

**Pull request merged**
