### PR TITLE
Add ndivrem for rounding towards nearest integer

### PR DESCRIPTION
**Pull request by albinahlback**
Will remove draft if https://github.com/wbhart/flint2/pull/962 is merged and FLINT_jll is thereafter updated.

### CODE REVIEW

**Comment by fieker** [comment]
What about the "modern" julia interface: `div(x, y, r::RoundingMode=RoundToZero)` and `fld`, `cld` and partners? (Not that I like this interface, but it is there)

**Comment by albinahlback** [comment]
Sorry for late reply. I think it could be nice since it's more verbose.

**Comment by tthsqe12** [comment]
None of the julia rounding modes fit the bill here. If there was a name for the one in the pr, I think it would be `RoundNearestTiesTowards` ¯\_(ツ)_/¯ ?
```
RoundNearest
RoundNearestTiesAway
RoundNearestTiesUp
RoundFromZero
RoundUp
RoundDown
```

**Comment by thofma** [comment]
Needs a rebase.

**Comment by albinahlback** [comment]
Fixed

**Pull request merged**
