### PR TITLE
Newbranch3

### PR DESCRIPTION
**Pull request by fieker**

### CODE REVIEW

**Comment by fieker** [comment]
This is the cumulative merge moved from Bill to nemocas

**Comment by wbhart** [comment]
Unfortunately it has conflicts with master and so can't be merged.

**Comment by fieker** [comment]
On Thu, Mar 17, 2016 at 12:51:11AM -0700, wbhart wrote:
> Unfortunately it has conflicts with master and so can't be merged.

How do I see actually WHAT conflicts there are?

**Comment by wbhart** [comment]
You can follow the instructions on this page
https://github.com/Nemocas/Nemo.jl/pull/3 where it says "Use the command
line".

**Comment by wbhart** [comment]
Of course the instructions in Step 2 assume your master is clean, which it likely isn't. So you will have to adjust those instructions to merge with a clean branch (i.e. one that is taken from the Nemocas repository).

On the other hand, that should be equivalent to checking out and creating a new branch based on the Nemocas repo and then cherry-picking the commits you want across to that branch.

**Comment by fieker** [comment]
On Thu, Mar 17, 2016 at 01:00:29AM -0700, wbhart wrote:
> Of course the instructions in Step 2 assume your master is clean, which it likely isn't. So you will have to adjust those instructions to merge with a clean branch (i.e. one that is taken from the Nemocas repository).
> 
> On the other hand, that should be equivalent to checking out and creating a new branch based on the Nemocas repo and then cherry-picking the commits you want across to that branch.
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Nemocas/Nemo.jl/pull/3#issuecomment-197747620

I've followed all that *&(*&(@#@ instructions and still cannot merge....
Now, as per instructions from github, my master has all the changes...

**Comment by wbhart** [comment]
You have to resolve the merge conflicts from step 1 manually. That is what
happens between steps 1 and 2.

Once you've done that, you push to your repository, so that there is a new
branch in your GitHub repo. It is from this new branch that you create your
pull request.

Bill.

**Comment by thofma** [comment]
These instructions are for someone who wants to merge this pull request and not for the one who opened the pull request. Now it is really messed up.

**Comment by wbhart** [comment]
Yeah I think GitHub didn't post the comment I made immediately following
the one where I suggested using these instructions. I said that you want to
follow step 1 only and then after you have sorted out the conflict then
push the branch to your repo. I also mentioned that Claus probably doesn't
want to do this into his master since it isn't clean.

**Pull request closed without merging**
