### PR TITLE
Add some missing setindex functions

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by wbhart** [comment]
Was everything failing before these changes?

**Comment by thofma** [comment]
No. He is running into an infinite recursion. Looking into it.

**Comment by thofma** [comment]
Fixed the bug. I introduced it with the `similar` business. I don't know how this could ever pass on travis.

**Comment by thofma** [comment]
Hm, now failing only on 0.7dev.

**Comment by wbhart** [comment]
Have they just broken something, or is it the new code that breaks?

**Comment by wbhart** [comment]
The failure is a segfault in nf_elem_fmpz_mat_conversions. Could that be related to the new code?

**Comment by thofma** [comment]
It is the new code. Will look into it tomorrow.

**Comment by thofma** [comment]
Ok, it is not the new code. I can reproduce it without the changes here.

**Comment by wbhart** [comment]
Ok, then I will merge this code.

**Pull request merged**
