### PR TITLE
`nullspace(::QQMatrix)` via flint

### PR DESCRIPTION
**Pull request by joschmitt**
Reintroduce `nullspace(::QQMatrix)` via flint from #1633 which was reverted in #1655 since it created problems in OSCAR.

This contains additional commits that massage the result until it looks like what the generic AbstractAlgebra `nullspace` would return. Let's see if it works.

### CODE REVIEW

**Comment by joschmitt** [comment]
Review/merge?

**Comment by joschmitt** [comment]
I don't know how soon somebody will work on https://github.com/thofma/Hecke.jl/issues/1385.
Regarding the mathematical properties of the normal form: it is very hard to promise something here because we rely on flint which does not promise anything, at least not in the documentation. I already asked about this almost two years ago in https://github.com/oscar-system/Oscar.jl/issues/1062.
If we want to dig through flint and start documenting the "shape" of the output, I would say that this should be part of the general effort regarding linear solving (maybe one day the doc string of what is now `Solve.kernel` will have it). I don't think it makes sense to document something just for the `QQMatrix` nullspace, but not for the other flint or generic methods.

**Comment by thofma** [comment]
To keep it simple:
1) Add a comment in the code explaining why we do this (you can copy what you wrote in OP).
2) We eventually clean this up together with the other linear algebra functionality. Since I don't see us promising anything for the "shape", this probably means fixing https://github.com/thofma/Hecke.jl/issues/1385. But we will cross that bridge when we come it.

**Comment by joschmitt** [comment]
I added the comment. Maybe we don't need to have the CI run yet another time?

**Pull request merged**
