### PR TITLE
Update argument order in `compose`

### PR DESCRIPTION
**Pull request by lgoettgens**
This updates all definitions and uses of `compose` in Nemo according to https://github.com/oscar-system/Oscar.jl/issues/690 to follow `compose(f,g) = g(f(x))`.

This change is obviously breaking.

### CODE REVIEW

**Comment by lgoettgens** [comment]
Cf. https://github.com/Nemocas/AbstractAlgebra.jl/issues/1025

**Comment by fingolfin** [comment]
The breakage this introduces is of a worse kind than other such PRs, because instead of causing compile errors, it may result in some code actually continuing to work but return wrong results. I have no brilliant solution for this, though, other than perhaps it would be good to add `compose_left` and `compose_right` (but then who can remember which is which); or `precompose` / `postcompose` (but again I am not sure if people can remember; plus these are harder to find for tab completion). Hrm.

If we had compose_left / compose_right (or whatever), then code could be converted to use them, making remaining uses of `compose` stand out more. Then we could rip off the bandaid in two steps: in one we disable `compose` completely for a release (to catch any remaining code using it), and then in a later release could add it back...

(Personally I think what I could work with best myself is to use `*` and $\circ$ operators: I have been drilled since high school that $(f\circ g)(x) = f(g(x))$, and later learned that $x^{fg}=x^{f\cdot g} = x^{f*g} = (x^f)^g$, i.e., $(f*g)(x) = g(f(x))$. However, besides the obvious issue due to use of unicode, I also suspect that many won't be familiar with one or both of these, too.

Hrm. Sorry, no great solution from me here. We should still resolve this eventually, somehow!

**Comment by thofma** [comment]
Could we perhaps keep the discussion at https://github.com/oscar-system/Oscar.jl/issues/690?

**Comment by lgoettgens** [comment]
Making this a draft to prevent accidental merge

**Comment by lgoettgens** [comment]
too many conflicts. closing

**Pull request closed without merging**
