### PR TITLE
Added arg checks (nrows/ncols) for constructors of ZZMatrix & QQMatrix

### PR DESCRIPTION
**Pull request by JohnAAbbott**
Forbids negative matrix dimensions

### CODE REVIEW

**Comment by thofma** [comment]
Hm, these are internal and not meant for the user. We usually don't add argument checks for those. Because this also means checking things twice.

**Comment by JohnAAbbott** [comment]
I noticed that most of the constructors did not check the dimensions.  The checks do need to be made at least for `matrix_space` specializations since these do seem to be publicly visible.  It's not harmful to check the other constructors, but if you prefer to remove the checks, you can -- maybe an assertion is a possible compromise?

**Comment by thofma** [comment]
Do you remember which `matrix_space` or `matrix` invocation resulted in an error?

**Comment by JohnAAbbott** [comment]
Sorry for the delay in responding.  I'm fairly it was just `matrix_space(ZZ, -1,-1)` or something very similar.  An error was indeed signalled: flint reported "overflow", IIRC.  Good that an error was signalled, but its nature was not so helpful.

**Comment by lgoettgens** [comment]
The problem is that one can create the matrix space without problems, but only gets an error when the first actual matrix is created. See
```julia
julia> M = matrix_space(ZZ, -1,-1)
Matrix space of -1 rows and -1 columns
  over integer ring

julia> zero(M)
Exception (flint). Overflow creating size -1 x -1 object.
ERROR: Problem in the Flint-Subsystem
```

**Comment by JohnAAbbott** [comment]
Thanks @lgoettgens for the explicit example; now I see it, I recall that that was indeed the problem I originally encountered.

**Comment by JohnAAbbott** [comment]
Presumably creating a `matrix_space(ZZ, 0, -1)` would not trigger overflow when creating an object of that space; but I think that an error ought to be signalled in this case too.  My proposed modification produces:
```
julia> S = matrix_space(ZZ, 0,-1)
ERROR: Dimensions must be non-negative
```

**Comment by joschmitt** [comment]
I have the impression that the checks should then be put in the user facing `matrix_space` and `matrix` functions here and in AbstractAlgebra and not the constructors. Maybe this is in line with what @thofma said?

**Comment by lgoettgens** [comment]
> I have the impression that the checks should then be put in the user facing `matrix_space` and `matrix` functions here and in AbstractAlgebra and not the constructors. Maybe this is in line with what @thofma said?

Yes, exactly.

**Comment by JohnAAbbott** [comment]
My preference is to leave the checks in the constructors:
1. the checks are very cheap (and may occasionally help with debugging)
2. since Julia does not offer "private" functions (as in C++), anyone could call the constructors
3. the checks might also help someone reading the code understand what restrictions the parameters must satisfy

Well, the code is not mine, so my preferences perhaps count for little...

**Pull request closed without merging**
