### PR TITLE
Add some missing unsafe functions for nmod_mat

### PR DESCRIPTION
**Pull request by fieker**
… as direct access to the UInt entries

### CODE REVIEW

**Comment by wbhart** [comment]
The sub! function is broken. It would be useful if _get_entry_raw could be added for other rings where it makes sense, and then a catchall added to Rings.jl for all other rings.

**Comment by thofma** [comment]
What should the catchall in Rings.jl do?

**Comment by fieker** [comment]
I've added the corrections to sub!

I agree that the _raw stuff should be more universal, but
 - I'd like to keep the request simple and not mix to omany modules
 - I don't know what to do: eg. for fq_nmod, coeff returns the UInt while get_entry for nmod_mat does not (it returns the more correct, but invoncenient GenRes element)

What do we want as the two standarts?

**Comment by wbhart** [comment]
Yeah maybe this function isn't a suitable candidate for a catchall. I was thinking it would just default to get_entry (or get_index or whatever it is called). All I'm concerned about is adding yet another ad hoc function with an underscore in front of it to indicate that no one really needs to know about this function, including those who go looking for it at some later date. I mean, there's no documentation or test code. So what stops people adding more and more of these? What about polynomials? Will similar functions be added there? Or do they already exist? Should we check the naming scheme is consistent?

**Comment by fieker** [comment]
It exists (at least in Hecke) for various types. I don't mind adding docs and testing, but in the long term, I think we need access functions for any information stored in any structure - and unfiltered access at that. General experience shows that whatever reason you have for thinking "no-one will ever need that" will be overruled later - by some totally unexpected application.

More difficult is the mixture of get_entry{nmod_mat} -> GenRes (-> the need for the raw version), coeff{fq_nmod} -> UInt (-> the need for the GenRes version), norm(fq_nmod) -> fmpz (-> should be GenRes I think) and similar. We need to (possibly face to face) discuss ANY convention and then spend the neccessary hour to implement it.

I don't mind _raw functions and similar missing - they can be added on demand. But we should decide on the naming stuff.

**Comment by wbhart** [comment]
I have no objection to this function whatsoever. It's a good idea. The problem I am having here is that it looks like an ad hoc solution to a general problem. You quite often need access to entries of matrices and coefficients of polynomials and power series as the implementation type, rather than the Nemo type.

As you say, get_entry looks like it is already supposed to do this (as opposed to getindex), but someone already ad hoc implemented this the wrong way for this module, returning a Res instead of an int.

Also, one! is not a standard ad hoc operator. Again I ask, do you really want to implement one! for all modules in Nemo, including all future ones? If not, it shouldn't be added here! The more of these ad hoc operators you add, the greater the burden for people writing other modules.

**Comment by wbhart** [comment]
And again, I'm not complaining about one! per se, just that it's being done for one module only without documentation.

**Comment by wbhart** [comment]
Same for sub! It's not a standard operator. So given there's forty odd modules in Nemo, you just created a lot of work for someone!

**Comment by fieker** [comment]
one! (and zero!) I've used and added (to Hecke/ Nemo) for several rings - unfortunately, it is the basis for many memory efficient operations. I would not demand it as standard - maybe the use should be o = zero!(o), but otherwise re-using of variables is difficult. zero! is fine for anything additive, but one! is necessary for multiplicative stuff. 
Documenting this is a different issue - and using this is not without peril (I caused various violations over the last couple of days) but it is VERY efficient.

It adds burden to people writing new modules - but then, maybe one! and zero! should be the default and zero, one be automatically added by a catch-all? With the option of implementing special stuff when necessary for efficiency....

Having said that: my code needs only zero!  and mul! - I added the other ones only because I found this useful in other contexts...

Also, unfortunately, different modules will behave differently (over the time)

**Comment by wbhart** [comment]
I understand their usefulness. But I can't write generic code against one! and sub! if they only exist in a handful of modules. When I recently added the function add! because I realised we couldn't do without it, I added it to every module in Nemo. Now that generic code works against any module in Nemo, rather than just whatever I was working on at the time. Nemo is a generic layer on top of a C interface. Maintaining it ad hoc just isn't going to work!

**Comment by fieker** [comment]
I would not mandate sub!, ... for all modules. If there is a need, then they can be added. The strngth of Nemo/ Hecke is that I can write (fast) generic algorithms. I cannot test them on all (mathematically) possible rings on the time of writing, thus I will implement them as generic as possible - while using add!, sub! then I need efficiency. When I encounter missing cases I add them. Fundamentally, the options here are
 - to avoid using add! at all (-> slow)
 - add them to Hecke
 - add them to Nemo

**Comment by thofma** [comment]
What is a standard operator? It is not documented at all what functions a module (i.e. a new ring) must provide to be usable for the generic stuff. At the moment it is already try and error.

**Comment by wbhart** [comment]
Why wouldn't you mandate sub!? It can be implemented for just about every module in Nemo. We already have add! for every module in Nemo. I deliberately went to a lot of trouble to implement the generic code I was working on to pull a multiplication by -1 out before all the loops so I could use add! instead of sub! throughout the generic code so that the latter wouldn't be needed. And now you are adding it anyway? Maybe the student working with Tommy can add sub! and one! for all modules in Nemo, based on the add! and zero! implementations I've put in for all modules. We can't just keep doing more and more ad hoc stuff without cleaning up after ourselves, in my opinion.

**Comment by wbhart** [comment]
That's not correct, Tommy. When I wrote the documentation, I went to some effort to describe the functions that must be provided for each kind of module, e.g. polynomials, matrices, etc. If it hasn't been kept up to date, that certainly isn't my fault! It's only ad hoc because we aren't doing it in a systematic way, which is precisely what I'm complaining about here.

**Comment by wbhart** [comment]
Tommy, take a look at the Basic functionality section in the file doc/src/polynomial.md Admittedly, it looks like I forgot to add the add! function there, though I don't remember where I added that. Perhaps it was in the mpoly branch which I am still working on.

**Comment by fieker** [comment]
I think, in hindsight, we started in the wrong way. The ! functions should have all been there first and then the non! functions been implemented (generically) on top of them....
But I guess this is hindsight.

There is a reason that flint only provides the ! versions.

I don't mind defining this as an official goal - provided, in my mind, it can be done incremental and not only as one large pull request. Then one can systematically work through the modules one, by one, "fixing" stuff.

While waiting for computations to finish, lunch time to arrive or similar...

**Comment by thofma** [comment]
Sorry, for overlooking it. Can you point me to the relevent page where I can find all the functions I have to implement to get a working polynomial ring?

**Comment by fredrik-johansson** [comment]
Is there any performance drawback to making the syntax x = zero!(x) so that generic fallbacks can be provided?

**Comment by wbhart** [comment]
I don't think there is any drawback, Fredrik. We should do this some time. Of course it should be done en mass, not in bits and pieces.

**Comment by fieker** [comment]
I realised too that I am confusing to different issues
 - writing generic fast code
 - writing specific fast code
The needs are different. The first defines stuff that should be there globally, the second not.
E.g. I can easily see the need for coeff_raw!(fmpz, fmpz_mod_poly) while obiously, I cannot for nmod_poly stuff.
Generically, thus I cannot use this (and face it, generically, I don't deal with coefficients, I deal with euclidean ops and such). However, for specific situations, I definetely want that function.
Is this a reason to force this everywhere or to bann this everywhere?

Hecke, currently, uses 395 ccalls to arb, to flint, to antic, ...
This is to provide access to non-exported features as well as to do nefarious things.
Some of this is superseded since the corresponding ! functions have been globally added since. Some of this is still needed - but could be replaced using newly added global stuff. Others is there is stay I guess...

**Comment by fieker** [comment]
To add: some of this could/ should actually migrate over to Nemo...

**Comment by wbhart** [comment]
It should be obvious that if you are going to implement sub! for some modules, you should implement it for all modules that implement subtraction. It's not some obscure functionality needed to make something fast. It's a basic ring operation!

**Comment by fieker** [comment]
I think the main difference is the desire to keep all modules in sync vs the gradual improvement option.,,,

**Comment by wbhart** [comment]
I just checked and add! was added to speed up my mpoly branch, which explains why it isn't documented yet. I did take the time to add it to all modules in Nemo though. So we've gotten a little bit of extra inconsistency by merging my mpoly branch ahead of time. But I'd hate that to be used as an excuse for introducing even more inconsistency.

**Comment by wbhart** [comment]
There is no gradual improvement option. You either keep things consistent, or you end up with a mess like certain other Open Source projects we know about (and perhaps certain closed source ones I don't know about). I've seen Open Source maths projects where there is no consistency at all in function naming. They didn't even bother getting the spelling correct! Such projects shall remain nameless.

**Comment by thofma** [comment]
I still don't know where to find this list of standard operations every module needs to implement. I did not find anything about `show_minus_one` or `needs_parentheses` in the documentation.

**Comment by wbhart** [comment]
Branches are very useful for working on small projects like this that don't get done in one go. A project such as adding sub! for all modules in Nemo is a very good use for a branch.

**Comment by fredrik-johansson** [comment]
I think `show_minus_one` and `needs_parentheses` (and maybe some more methods) should have default implementations so that you don't have to define them for every ring. It's fine to have some redundant parentheses printed by default for strange rings.

**Comment by wbhart** [comment]
I appear to have missed those when writing the docs, Tommy. There is no documentation which specifies which functions have to be added for RingElem. Instead, I wrote similar documentation for each kind of ring, e.g. polynomials, because the functions vary a bit per kind of ring. We could introduce a page which includes only the functions that are needed for every ring.

But the fact is, I did at least try to document all this carefully when I did the last documentation rewrite. As I said above, check the Basic Functionality sections, e.g. in doc/src/polynomial.md

**Comment by thofma** [comment]
@wbhart http://nemocas.github.io/Nemo.jl/latest/polynomial/ tells what a Polynomial ring has to provide. But it does not tell what a ring `R` has to provide such that `PolynomialRing(R)` will work. Nowhere is mentioned that my new ring has to implement.

**Comment by wbhart** [comment]
Yes, you are right, Tommy. There should be a page on functions that must be added for all rings. This will grow as we add more kinds of rings. For example, to get Polynomial.jl to work over your new ring, you need mul! addeq! and a few others. But when I added MPoly, you also needed add! and zero!, and so on. 

I had simply been thinking about what functions would have to exist if someone wanted to add a new polynomial ring, etc., not what needs to be there if you implement a completely new kind of ring that isn't in Nemo yet. But the latter would be useful.

I'll add tickets for both of these things you've just pointed out.

**Comment by fieker** [comment]
This is the key difference: for me, mostly the gradual option is the only viable one as it allows to work for a specific application. I don't think this is going to kill the system, I think its going to help it fly. Among other things, it also adds various easy (boring) projects that beginners can participate. It keeps tasks manageable.
The basics have to be consistent - but thats the case. You can do add, sub, ... everywhere.
By the time one needs add! and sub! users also progressed a fair bit.
I also admit I cannot plan a final interface for all needs and all algorithms in advance. Over the time one discoveres that certain, even rather bizarre, operations have to be added to the "standard" sometimes by providing generic solutions, sometimes the "hard" way.

Looking at the (invisible) (internal) magma-ring-interface, there are I don't know, about 100 functions listed, some are more important that others (add vs. add_mult_into) some don;t apply to all rings (gcd and friends), ... and all of them are used somewhere in some "generic" algorithm. Which can fail for specific rings. It is attempted to test this by checking o the user level for certain interfaces to be there, but this is not perfect.

**Comment by fieker** [comment]
.. don't forget the hashing stuff and the deepcopy - if we ever figured out what julia requires there...

**Comment by thofma** [comment]
Yes, I think there was a misunderstanding. I know you put a lot of effort into writing the documentation Bill. I can add a part about what a ring has to provide. This should also help with the consistency.

**Comment by wbhart** [comment]
If you want to do something gradual, you have to open tickets for the things you didn't do generically across the whole system, so that the programming slaves know what needs to be done to clean it up. Otherwise we will just accumulate crud which no one knows how it works.

As a minimum for this PR, can you add a ticket explaining that sub! and one! need to be added for all rings in Nemo, assuming that this is what you really want. And can we think about what kind of interface we want in general for _get_entry_raw. For a start, the leading underscore can be omitted. As I've said before, leading underscores shouldn't be used in Julia code.

I'm ok with the name get_entry_raw and get_coeff_raw. But you might like to think about what happens if we need more than one such function for a given type, e.g. one that returns a UInt and one that returns a Poly{fmpz}, say. Would it not make more sense to have an interface like:

get_entry_raw(UInt, i, j)

Once we've decide on what we want generically, we can open a ticket to implement this across the whole of Nemo, and to remove the currently broken get_entry, which seems to have been intended to replace getindex for some unknown reason. Perhaps removing that, if that is desirable, can be another ticket, since it has to be replaced at each calling site with whatever the new standard is.

And at least, update the docs and add some test functions.

**Comment by thofma** [comment]
I have changed the names according to our discussion.

**Pull request merged**
