### PR TITLE
conversion from Arb integers to Int

### PR DESCRIPTION
**Pull request by heiderich**

### CODE REVIEW

**Comment by thofma** [comment]
I don't quite understand. What is this function doing that `unique_integer` is not doing? Also:
- This does not return an `Int`.
- The conversion should only be done if it really is an `Int` and not if it only contains a unique integer (similar to `Int(1.1)` versus `Int(1.0)`).

**Comment by heiderich** [comment]
> I don't quite understand. What is this function doing that unique_integer is not doing?

One purpose would be to use it with `change_base_ring`. A restriction to the second entry of the output of 
`unique_integer` would not be sufficient, as it would return 0 in case the arb object does contain a unique integer. But this is not the desired behavior in such a situation. I would expect an error in such cases.

> This does not return an Int.

Indeed. It returns a `Nemo.fmpz`. And I think this is what we want. I changed the definition.

> The conversion should only be done if it really is an Int and not if it only contains a unique integer (similar to Int(1.1) versus Int(1.0)).

When trying to convert an arb that does not contain an integer, it throws an error:

```
julia> convert( Nemo.fmpz, Nemo.ArbField(64)(1.1) )
ERROR: Argument must be an integer.
Stacktrace:
 [1] convert(::Type{Nemo.fmpz}, ::Nemo.arb) at /home/florian/.julia/v0.6/Nemo/src/arb/arb.jl:902
```

Is this what you are asking for?

**Comment by thofma** [comment]
No, I meant that also `convert(fmpz, ArbField(64)("1 +/- 0.1")` should throw. But after thinking about it again, what you propose makes sense.

To do the coercion between different rings we usually don't use `convert` but rather the `R(x)` approach, where `R` is a ring. Otherwise we cannot write generic code (for example in `change_base_ring`).

I am happy with this change if we change it to `(::FlintIntegerRing)(::arb)`. Then `FlintZZ(a)` will work, where `a` is an `arb`. Is this OK for you?

**Comment by heiderich** [comment]
> No, I meant that also convert(fmpz, ArbField(64)("1 +/- 0.1") should throw. But after thinking about it again, what you propose makes sense.

This does throw an error, cause I am checking `isint` first.

> I am happy with this change if we change it to (::FlintIntegerRing)(::arb). Then FlintZZ(a) will work, where a is an arb. Is this OK for you?

Yes, I changed it.

**Comment by thofma** [comment]
Sorry, my bad. I will merge as soon as green.

**Pull request merged**
