### PR TITLE
Large qadic

### PR DESCRIPTION
**Pull request by fieker**

### CODE REVIEW

**Comment by fieker** [comment]
I guess the tricky question is about updating the binary builder for flint...

**Comment by wbhart** [comment]
Trivial as far as I know. You just issue a new release on the builder and it's all automatic. @thofma can explain.

**Comment by thofma** [comment]
Binaries are on their way. I will finish this up here once they are done.

**Comment by fieker** [comment]
On Mon, Feb 17, 2020 at 11:02:43PM -0800, thofma wrote:
> Binaries are on their way. I will finish this up here once they are done.

Klasse, Danke

**Pull request merged**
