### PR TITLE
Sqrt functions

### PR DESCRIPTION
**Pull request by wbhart**
* Adds issquare_sqrt
* Renames square_root to sqrt
* Adds check=true flag to all sqrt functions
* Make better fmpz_mpoly_sqrt function

This is the Nemo counterpart to https://github.com/Nemocas/AbstractAlgebra.jl/pull/943

See https://github.com/Nemocas/Nemo.jl/issues/862

This is breaking in every possible way.

### CODE REVIEW

**Comment by thofma** [comment]
Needs a rebase.

**Comment by wbhart** [comment]
@thofma This seems to be perfect code now. No mitsakes here!

**Comment by thofma** [comment]
Yes, as usual!

**Comment by wbhart** [comment]
Are you already for me to merge this and the divides_functions branch?

**Comment by thofma** [comment]
Yes, also bump AA to 0.21.0 in the Project.toml (also src/Project.toml).

**Pull request merged**
