### PR TITLE
rename isnegative to displayed_with_minus_in_front

### PR DESCRIPTION
**Pull request by heiderich**
An exception is `isnegative` in `src/arb/arb.jl`. In this case I introduced a new function `displayed_with_minus_in_front` that returns `false` for the moment being.

### CODE REVIEW

**Comment by heiderich** [comment]
The Travis test seems to fail, because Nemo.jl is build against AbstractAlgebra 0.0.8. I saw that @thofma already bumped the version to 0.0.9 and opened https://github.com/JuliaLang/METADATA.jl/pull/16009. Now however the JuliaCIBot tests fail, because Nemo is too old (calls `isnegative`).

**Comment by thofma** [comment]
I think we need to import `displayed_with_minus_in_front` from AbstractAlgebra.

**Comment by heiderich** [comment]
I think the problem here is rather that (Travis at least) is installing AbstractAlgebra 0.0.8, which does not have `displayed_with_minus_in_front`.

**Comment by thofma** [comment]
We have to wait till it is merged on METADATA.

**Pull request merged**
