### PR TITLE
Fixes missing fit! and setcoeff! methods for relative and absolute series.

### PR DESCRIPTION
**Pull request by wbhart**
As the Series Ring Interface says these functions should be provided by series, I have added them for all the Flint series types where they were missing.

Indeed derivative called these functions, hence the added tests to make sure the new code works.

### CODE REVIEW

**Comment by thofma** [comment]
Error looks real.

**Comment by wbhart** [comment]
It does, but I'm unable to reproduce it locally and it also doesn't make any sense. It is just setting a coefficient of an fmpz_mod_poly. This should only happen if the modulus is zero, which it isn't.

I suspect something is wrong with fmpz_mod_poly. Maybe the struct in Nemo has the wrong size or there's something different about my Flint binary. @tthsqe12 do you have any clues what might be going wrong here?

**Comment by tthsqe12** [comment]
I will look into this on 1.4

**Comment by wbhart** [comment]
It's weird that 1.5 is successful. My Flint has the first entry of the ctx struct as n and it is an fmpz. It's a bit dodgy overall to reach into a Julia created struct (the ctx object) and pull out an fmpz (admittedly it is just an Int in this particular case, i.e. the modulus 31). But in general I'd be worried the gc might not see that we still have a reference to the contents of that ctx struct and clean it up.

**Comment by tthsqe12** [comment]
The different julia version have different gc implementations

**Comment by wbhart** [comment]
Then the first thing I would try is adding GC.@preserve to preserve the ctx struct while ccalls are made with its contents as parameters.

**Comment by thofma** [comment]
Where do we do this for example?

**Comment by wbhart** [comment]
Every ccall in Nemo's fmpz_mod_poly and fmpz_mod_rel_series and fmpz_mod_abs_series that passes ninv.

But to check if this is the problem, it would probably be good to begin with the stack trace:

```
[1] fmpz_mod_abs_series(::Nemo.fmpz_mod_ctx_struct, ::Array{Nemo.fmpz_mod,1}, ::Int64, ::Int64) at /home/runner/work/Nemo.jl/Nemo.jl/src/flint/FlintTypes.jl:3428
   [2] fmpz_mod_abs_series at /home/runner/work/Nemo.jl/Nemo.jl/src/flint/FlintTypes.jl:3438 [inlined]
   [3] (::FmpzModAbsSeriesRing)(::Nemo.fmpz_mod) at /home/runner/work/Nemo.jl/Nemo.jl/src/flint/fmpz_mod_abs_series.jl:644
```

**Comment by wbhart** [comment]
Actually, now I'm really not sure.

**Comment by tthsqe12** [comment]
There is a context object missing here
https://github.com/Nemocas/Nemo.jl/blob/master/src/flint/FlintTypes.jl#L3428
Can you add it in this this pr?

**Comment by tthsqe12** [comment]
I am going to go through the fq_nmod ccalls soon and make sure those all match the library, but this one is directly related to this pr.
Would it be dreaming to imagine a tool that parses the c headers and goes through all of the julia ccalls and makes sure they match?

**Comment by wbhart** [comment]
Yeah this seems more likely the issue. I don't know what I was thinking earlier! Just running tests locally now. Commit coming shortly.

**Comment by wbhart** [comment]
Is it really correct to pull ninv out of the ctx struct then use it? After all, if ninv is actually backed by an mpz, it would be cleaned up with the ctx struct. And that could very well go away if there were no references to it after ninv had been pulled out.

Of course it works for us here because ninv is actually an Int and not backed by an mpz for the example I chose.

**Comment by thofma** [comment]
`ninv` is an `fmpz_mod_ctx_struct`, with proper initialization and finalizers attached. I don't see why this would be unsafe.

**Comment by wbhart** [comment]
Oh, I see where I got confused. I saw base_ring(parent(f)).ninv and thought it was pulling an fmpz out. But it's a UInt.

I got confused because ninv is the name of an fmpz in another struct. So mea culpa.

**Comment by thofma** [comment]
The name is a bit misleading. When we adjusted it to Dans `fmpz_mod` changes in flint2 we kept the field names here.

**Pull request merged**
