### PR TITLE
Kronecker product

### PR DESCRIPTION
**Pull request by martinra**
Once the corresponding code is merged into Flint, the tests over ZZ and QQ must be run. The generic case is already complete.

### CODE REVIEW

**Comment by thofma** [comment]
I have built new Windows binaries. Can you change the flint commit in /deps/build.jl`?

**Comment by thofma** [comment]
Tests are failing. You moved some functions from flint/* to generic/*. To get them visible in flint/* you have to add them in the export/import lists in src/Nemo.jl.

**Comment by thofma** [comment]
Thanks.

**Comment by wbhart** [comment]
test_gen_mat_kronecker_product doesn't seem to be called anywhere!

**Comment by wbhart** [comment]
issquare is also misspelled in the exports from Matrix.jl

**Comment by wbhart** [comment]
Also the string printed at the beginning of test_gen_mat_kronecker_product contains a copy'n'paste error.

**Comment by wbhart** [comment]
Also test_gen_mat_kronecker_product should not contain the line:

```
   using Nemo, Base.Test
```

**Comment by wbhart** [comment]
And the following line is missing from test_gen_mat_kronecker_product:

```
   println("PASS")
```

**Comment by wbhart** [comment]
Similar problems occur in the other test functions.

**Comment by thofma** [comment]
My bad, I trusted you blindly @martinra

**Comment by martinra** [comment]
Ohh, I'm sorry. I suppose I relied to much on checks which in Julia are not in place. Have to admit that I even forgot that Julia doesn't issue warnings for unused exports. I'll look at this and fix it tomorrow.

**Pull request merged**
