### PR TITLE
Allow constructing polynomials from empty coefficient lists

### PR DESCRIPTION
**Pull request by fingolfin**
This produces a zero polynomial

Explicit tests will come in a PR which adds "ring interface conformance tests", but I run into a bunch of issues there, so I thought I should just submit this now, I think it is pretty obvious anyway.

### CODE REVIEW

**Comment by wbhart** [comment]
I think you should accept the type of [] not just the type of blah[] where blah is the type of the coefficients.

**Comment by fingolfin** [comment]
Not sure what you are saying here. Do you mean you want the user to be able to write `R([])`? But why? If this is interactive input, they should instead do `R(0)` or `zero(R)` or `R()`. If its in code, then the vector should have the right type -- and if it doesn't, that indicates type instability, and I'd rather get an error and fix it than silently accepting it.

Also, the ring interface does not make any promises about accepting `Vector{Any}`  which is the type of `[]`.

Or maybe you meant something else, but what?

**Comment by wbhart** [comment]
Yes, I meant that it makes it easier from interactive input. I don't currently see why users should be forced to do it a different way instead.

**Comment by fingolfin** [comment]
I don't understand -- why is `R([])` easier` for the user than `R()`  or `R(0)`?

**Comment by wbhart** [comment]
@fingolfin Don't worry about it.

**Comment by fingolfin** [comment]
Well, I have to worry if this ends up being a reason for this PR to be held up. Honestly, I don't see why: this PR clearly fixes a violation of the ring interface. You are asking for further changes, that go beyond what the ring interface demands. One can of course debate whether those are useful or not, but to me that's a separate issue from fixing the bug this PR is meant to fix... And I need it for the conformance tests for Nemo rings I am preparing in another PR.

**Comment by wbhart** [comment]
@fingolfin Well, worry no more. As I said, don't worry about it.

**Review by wbhart — APPROVED** [review]

**Pull request merged**
