### PR TITLE
Add is_zero_initialized for FLINT backed matrix types

### PR DESCRIPTION
**Pull request by fingolfin**
Complementing https://github.com/Nemocas/AbstractAlgebra.jl/pull/1929

However I think this is independent of that PR, it just won't do
anything useful without it.

### CODE REVIEW

**Comment by lgoettgens** [comment]
The way these two PRs are currently set up will produce two same-named functions. Either AA needs to export this new function, or this PR here needs to explicitly import it

**Comment by fingolfin** [comment]
True. I don't think we want to export this trait, do we? In that case it would make sense to just merge & release https://github.com/Nemocas/AbstractAlgebra.jl/pull/1929 and then update this PR here to (a) require the new AA version and (b) import `is_zero_initialized`.

**Comment by lgoettgens** [comment]
> True. I don't think we want to export this trait, do we? In that case it would make sense to just merge & release [Nemocas/AbstractAlgebra.jl#1929](https://github.com/Nemocas/AbstractAlgebra.jl/pull/1929) and then update this PR here to (a) require the new AA version and (b) import `is_zero_initialized`.

Agreed

**Comment by fingolfin** [comment]
Updated

**Review by lgoettgens — APPROVED** [review]

**Pull request merged**
