### PR TITLE
Remove global `Flint*` objects

### PR DESCRIPTION
**Pull request by lgoettgens**
As suggested by @fieker in https://github.com/oscar-system/Oscar.jl/issues/1379#issuecomment-2449199261.

I would consider this a breaking change for Nemo, and this possibly needs some changes downstream in Hecke and Oscar for uses of `FlintZZ` and `FlintQQ`.

### CODE REVIEW

**Comment by lgoettgens** [comment]
Triage decided (ref https://github.com/oscar-system/Oscar.jl/issues/1379#issuecomment-2459419414) to first replace all uses of these downstream, then wait for some time, and only then merge this. If we need deprecations or not may be discussed then.

**Comment by thofma** [comment]
can we keep the definitions but not export them? they are kind of handy

**Comment by lgoettgens** [comment]
> can we keep the definitions but not export them? they are kind of handy

the gaussian ones or the QQ/ZZ? And what is the benefit of e.g. `FlintQQ` over `QQ`?

**Comment by thofma** [comment]
The Gaussian ones

**Comment by lgoettgens** [comment]
We could just add `QQi` (instead of `FlintQQi`) as an unexported global for this (and similarly for `ZZi`)

**Comment by thofma** [comment]
also works for me

**Comment by fingolfin** [comment]
As a milder step I would suggest that as a milder change we instead (or at first) modify Oscar and/or Hecke to not import resp. not re-export these. That would then perhaps be "breaking" for Oscar and/or Hecke but not Nemo, which arguably affects fewer people... But I am open to this PR here as well *shrug*

**Comment by lgoettgens** [comment]
@thofma just approved via slack

**Pull request merged**
