### PR TITLE
wrap {fmpz|fmpq}_randbits

### PR DESCRIPTION
**Pull request by tthsqe12**

### CODE REVIEW

**Comment by thofma** [comment]
Stop typing, start walking.

**Comment by wbhart** [comment]
You need to add the docstrings to the actual documentation.

Also, $ is not the delimiter for inline code in markdown.

**Comment by thofma** [comment]
Also, should it be `rand_bits` instead of `randbits`? Similar to `height_bits`.

**Comment by tthsqe12** [comment]
should be good now with a nice history

**Pull request merged**
