### PR TITLE
provide muleq! for fmpq

### PR DESCRIPTION
**Pull request by martinra**
From what I see there is no tests for the unsafe methods. Is that correct?

### CODE REVIEW

**Comment by wbhart** [comment]
We have tests called Polynomials, which should test them indirectly. The
matrix test code should also test some. But there's nothing systematic.

**Comment by wbhart** [comment]
By the way, I'm not convinced about adding a new function muleq! for fmpq, without adding it for all other types as well. Is it really needed? Doesn't mul! do the job?

**Comment by martinra** [comment]
I could add muleq! to the other types as well. It's true I was being a bit lazy. For me it's more a question of consistency and convenience: If you have addeq! you should have muleq!, too, I believe. Should I go ahead and add it where addeq! is present?

**Comment by wbhart** [comment]
Ah, that's an awful lot of places. It's not an easy job.

And then there's the AbstractAlgebra documentation to update....

Are you sure it's actually needed? If so, maybe it's easier to add a
catchall in AbstractAlgebra.jl which simply turns a call to muleq! into a
call to mul! (The AbstractAlgebra.jl docs would still need to be updated,
though fortunately only in one place now).

The thing is, addeq! can be implemented for many types more efficiently
than add! But the same is not true for muleq!. It's usually the case, for
polynomials for example, that you have to allocate something new because
the product will be much larger than the things being multiplied. So it's
not really clear what problem you would be solving by adding muleq! to the
system.

It's up to you if you want to do this. I just wanted to make sure you were
aware of the pros and cons.

**Comment by martinra** [comment]
So I'd read this as: For Nemo unsafe functions you prefer a techinical perspective, where functions are provided if they make a difference. Thanks for explaining the pros and cons. I think I'll not pursue it then.

**Comment by wbhart** [comment]
On 21 February 2018 at 16:53, martinra <notifications@github.com> wrote:

> So I'd read this as: For Nemo unsafe functions you prefer a techinical
> perspective, where functions are provided if they make a difference. Thanks
> for explaining the pros and cons. I think I'll not pursue it then.
>
That's probably a reasonable read on it. My personal perspective is to have
as few of them as possible, as they are difficult to get correct and need
to be implemented for all rings, both now and future. Some work has gone
into keeping them minimal, for example, note there is no sub!. We go to the
trouble of pulling a sign out of a loop in many places, so that we can use
add! instead. Of course we may add it some time in the future, but for now
I'm content with what we have.

But if anyone wants to do the work, I'm happy to support more of these
things. It's easy enough to add such a function for any new ring that is
added. The hard part is just adding them for all the existing rings. Hope
that makes sense.

**Pull request closed without merging**
