### PR TITLE
Conform `nmod` rand function to RNG interface

### PR DESCRIPTION
**Pull request by Keno**
The interface requires taking an RNG as the first argument and passing
it down to any interior calls to `rand`. Do that for nmod.

### CODE REVIEW

**Comment by thofma** [comment]
I want to be able to say `z = rand(R)`. Is this still possible?

**Comment by Keno** [comment]
Yes, the generic methods in base take care of adding the default RNG argument if not provided.

**Comment by thofma** [comment]
Can we also use our own default RNG which will be used for `rand(R)`? There is a random generator in the C library, which in the near feature has to be hooked up. Maybe I should ask @rfourquet :)

**Comment by Keno** [comment]
You can, but you'd likely be violating user expectations that seeding the global RNG produces reproducable numbers for invocations of `rand`.

**Comment by rfourquet** [comment]
> Yes, the generic methods in base take care of adding the default RNG argument if not provided.

This is true but only for one argument, i.e. `rand(R)` will work but not `rand(R, 1:9)`, even if you defined `rand(rng, R, 1:9)`. Also, `rand(R, 10)` to create an array won't work.

This is because the intended way to use the `Random` API is not to define e.g. `rand(rng, R)` but rather to define a `Sampler` for `R`. Unfortunately there is no way to directly do that when `rand` needs more than one object, like `R` and `1:9`. A struct should be created to wrap both subobjects. This is exactly what RandomExtensions.jl tries to solve, it would be a single method to overload (like is done now with `rand`), and a call would look like `rand(rng, make(R, 1:9))`.  

> Can we also use our own default RNG which will be used for rand(R)

Use, sure, and I would be glad to help making the C rng a proper subtype of `AbstractRNG`! 
But if you mean to have it as the default like Keno seems to have understood, I don't think it's a good idea, as everyone expect `GLOBAL_RNG` to be the default.

**Comment by thofma** [comment]
I must say that `rand(rng, make(R, 1:9))` looks a bit cumbersome compared to `rand(R, 1:9)`.

Also, does this mean that every time one draws random elements, I have to create a new object? How big is the overhead?

**Comment by rfourquet** [comment]
> I must say that rand(rng, make(R, 1:9)) looks a bit cumbersome compared to rand(R, 1:9).

True, but it's one solution to make `rand` with `R` adhere to the `Random` API. Unfortunately `Random` doesn't have a convenient solution out the box, and I'm definitely not pushing here to use RandomExtensions (it can take one or two seconds to load, plus a similar thing could be easily implemented for Nemo). 

> Also, does this mean that every time one draws random elements, I have to create a new object? How big is the overhead?

You mean a `make` object? in this case yes, but this is irrelevant, it's just an immutable struct wrapping other objects, this is completely elided by the compiler AFAIU.

**Comment by wbhart** [comment]
So we discussed this and we'll merge this PR and roll out the optional random generator across our packages (or rather, Rafael will).

This should work out ok because we are currently only using integer ranges for everything, which don't require the Flint random generator (there may be a handful of exceptions that will have to be dealt with at some time in the future, but they should be rare).

**Comment by rfourquet** [comment]
> Is there anything similar in Julia using towers of structures that we could look at as an example? 

Sorry to mention this package again, but solving this problem is exactly one of the goals of [`RandomExtensions.jl`](https://github.com/rfourquet/RandomExtensions.jl), the README gives some examples. I'm not sure it can be directly used because I didn't have parent-objects-which-are-not-types in mind, but it can certainly be adapted.

As it's general, the recursive structure has to be replicated in the `make` calls, e.g. ` rand(make(Set, make(String, 3), 10))` will produce a set of length 10 of strings of length 3. But in the case of `Nemo`, a ring has the knowledge of its base ring, so the tower of calls could be flattened. For example, `rand(make(polyring, 1:4, make(nmodring, 1:9)` could do what `rand(polyring, 1:4, 1:9)` does, and could be flattened to `rand(make(polyring, 1:4, 1:9))` (by defining `make(polyring, range, rest...) = make(polyring, range, make(base_ring(polyring), rest...))`)

I agree that this could be merged as this is a strict improvement (also I would have let Keno time to update according to my suggested change). And I was indeed planning to offer to do the same for other `rand` methods, it won't take much time.

**Comment by wbhart** [comment]
> > Is there anything similar in Julia using towers of structures that we could look at as an example?
> 
> Sorry to mention this package again, but solving this problem is exactly one of the goals of [`RandomExtensions.jl`](https://github.com/rfourquet/RandomExtensions.jl), the README gives some examples. I'm not sure it can be directly used because I didn't have parent-objects-which-are-not-types in mind, but it can certainly be adapted.

We'll certainly take a look at this.

> 
> As it's general, the recursive structure has to be replicated in the `make` calls, e.g. ` rand(make(Set, make(String, 3), 10))` will produce a set of length 10 of strings of length 3. But in the case of `Nemo`, a ring has the knowledge of its base ring, so the tower of calls could be flattened. For example, `rand(make(polyring, 1:4, make(nmodring, 1:9)` could do what `rand(polyring, 1:4, 1:9)` does, and could be flattened to `rand(make(polyring, 1:4, 1:9))` (by defining `make(polyring, range, rest...) = make(polyring, range, make(base_ring(polyring), rest...))`)

I really don't understand why you want a syntax that requires this word "make" to be added everywhere.

Tommy and I discussed a syntax like:

rand(rng, R, :degree=>1:5, :terms=>1:3, :Ints=>-10:10) 

But maybe I'm being naive about how extensible or usable this would be.

> 
> I agree that this could be merged as this is a strict improvement (also I would have let Keno time to update according to my suggested change). And I was indeed planning to offer to do the same for other `rand` methods, it won't take much time.

Claus is happy for you to work on rolling out Keno's approach for all our rand generators and updating the test code to match.

I wasn't sure from your suggestion whether this would preserve the simplicity of the current approach or not. How would a call to the random generator look after your change? And what extra overhead would there be to define this for each of our 100 or so rings/groups/fields/modules/ideals, etc?

**Comment by rfourquet** [comment]
> I really don't understand why you want a syntax that requires this word "make" to be added everywhere.

As I said, I'm _not_ willing to push this specific syntax for Nemo. You asked for example of how this problem can be solved, so `make` is one solution. I designed it with certain goals in mind, which don't all necessarily apply to Nemo: extension of `Random` with strict compatibility (as candidate for inclusion in a future `Random` release), optimal efficiency, composability (with independant types). 
One other API that I implemented for e.g. `rand(make(polyring, 1:4, make(nmodring, 1:9)` looks like `rand(polyring => (1:4, nmodring => 1:9))`. It's not inference-friendly, so is not optimally efficient in some cases, but it would be in the case of Nemo. Also, as I said, calls to `make` can be flattened in `Nemo` (which is not true in general case).

> rand(rng, R, :degree=>1:5, :terms=>1:3, :Ints=>-10:10)

Looks user-friendly, and maybe without significant loss of efficiency. I'm not certain this can be made general enough, but it may be implementable on top of a lower level API which is general. 

> I wasn't sure from your suggestion whether this would preserve the simplicity of the current approach or not. How would a call to the random generator look after your change?

The calls would look exactly the same. This is just using the official API instead of relying on an implementation detail. As a bonus, it also allows to call the array version, e.g. `rand(ring, 10, 10)`.

> And what extra overhead would there be to define this for each of our 100 or so rings/groups/fields/modules/ideals, etc?

In terms of efficiency, I never observed an overhead with this API since it's in `Base`/`Random`.  For the anecdote, I waited two years before including it in `Base` until I could not detect any performance regression (basically, it required that immutable objects containing reference to mutable objects (e.g. arrays) can be stack-allocated in some relevant cases).

If you mean overhead in terms of lines of code, it won't cost anything (just few more characaters per methods, as you can see in my review of this PR).

**Pull request merged**
