### PR TITLE
Fix partition function.

### PR DESCRIPTION
**Pull request by wbhart**
It doesn't make sense to define p(0), and in any event, it is certainly not 1. Edit: nope, see below.

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
Yes, p(0) = 1. There is exactly 1 partition of 0, namely the empty sum.

In addition, p(-n) = 0 for negative n makes sense.

**Comment by fredrik-johansson** [comment]
You should consult http://fungrim.org/topic/Partition_function/ about an edge case like this :-)

**Comment by wbhart** [comment]
Thanks @fredrik-johansson 

I think I'll change the PR to define it for negative n then.

**Comment by rfourquet** [comment]
The tests have to be updated, e.g. at "test/flint/fmpz-test.jl:577" and "test/flint/fmpz-test.jl:581" (taken from CI failure).

**Pull request merged**
