### PR TITLE
Enable code coverage reporting via Codecov

### PR DESCRIPTION
**Pull request by fingolfin**
Also updates badges in README.md

Badge preview: https://github.com/fingolfin/Nemo.jl/blob/mh/coverage/README.md

### CODE REVIEW

**Comment by fingolfin** [comment]
There is a failure in the Julia nightly build on macOS, but I don't see hot it could be caused by this PR (which touches no code):
```
acb.lindep...: Test Failed at /Users/runner/work/Nemo.jl/Nemo.jl/test/arb/acb-test.jl:403
  Expression: Phi == (x ^ 2 * y + 16x) - y ^ 2
   Evaluated: 16*x^2 - x*y^2 == x^2*y + 16*x - y^2
```

**Comment by wbhart** [comment]
The failure can be ignored. The algorithm is heuristic. One day we'll implement something more rigorous, but that is nontrivial.

**Comment by thofma** [comment]
These comments from the bot are very distracting and flooding my email account. I will probably disable them soonish unless @wbhart insists on them.

**Comment by fingolfin** [comment]
I don't like the emails either, which is why I set up a mail filter rule in my account to send them all to /dev/null. I do think the coverage comments themselves are highly valuable, though -- it is a pity that GitHub doesn't seem to have a feature for bots to make such comments w/o triggering an email. In any case, if a mail filter is not an option, then it is possible to turn off the comments without disabling the coverage tracking.

**Comment by thofma** [comment]
Yes, I saw that option in the codecov config. We will see how it works and then decide.

**Pull request merged**
