### PR TITLE
Change order of inputs in divisor_sigma

### PR DESCRIPTION
**Pull request by albinahlback**
Merge if https://github.com/wbhart/flint2/pull/1019 is merged and `FLINT_jll` is updated.

### CODE REVIEW

**Comment by fingolfin** [comment]
This is going to break any existing code calling `divisor_sigma`, right? Worse, it'll be "silent breakage", i.e., code may appear to still run but now produces garbage. So at the very least, there must be a corresponding change to the Nemo version indicating a breaking change once this is merged, and perhaps a NEWS items that explicitly warns about this.

That in mind, is changing the order really that important and worth the cost induced on any users of this function (and the negative PR fallout if a user's code is silently broken and they are annoyed with Nemo as a consequence)?

**Comment by wbhart** [comment]
The order is not currently correct. There is also likelihood that users are getting garbage already by passing arguments in the logical order and not consulting the docs.

Besides, this function is very, very rarely used. I don't think we are going to get a massive backlash from correcting our mistake.

**Comment by albinahlback** [comment]
> This is going to break any existing code calling `divisor_sigma`, right? Worse, it'll be "silent breakage", i.e., code may appear to still run but now produces garbage. So at the very least, there must be a corresponding change to the Nemo version indicating a breaking change once this is merged, and perhaps a NEWS items that explicitly warns about this.
> 
> That in mind, is changing the order really that important and worth the cost induced on any users of this function (and the negative PR fallout if a user's code is silently broken and they are annoyed with Nemo as a consequence)?

I hear what you are saying, Max. And indeed, the "silent breakage" is the hardest part as we cannot simply deprecate it.

**Comment by albinahlback** [comment]
Closing due to https://github.com/wbhart/flint2/pull/1019.

**Pull request closed without merging**
