### PR TITLE
rename exppii to the more standard cispi

### PR DESCRIPTION
**Pull request by tthsqe12**
We missed `exppii` in the big acb rename. I hope this is acceptable. @fredrik-johansson @albinahlback

### CODE REVIEW

**Comment by albinahlback** [comment]
Hmm, I prefer `exppii`.

**Comment by tthsqe12** [comment]
I had a favourable opinion on the name `exppii` until I learned that `exp(im*t)` is widely called `cis(t)`, and them my opinion dropped even lower once I found `Base.cispi`. It would be a shame to write `cispi(0.1)` for machine precision and then `exppii(CC(1//10))` for arbitrary precision.

**Comment by albinahlback** [comment]
Yeah, that sounds good.

**Comment by tthsqe12** [comment]
Hold on here folks. We have some more.
```
isint => isinteger
```

**Comment by albinahlback** [comment]
> Hold on here folks. We have some more for arb.
> 
> ```
> isint => isinteger
> atan2 => atan
> ```

I agree with the change of `isint` to `isinteger`, but why should one change `atan2` to `atan`? They are two different functions, both implemented in Nemo.

**Comment by albinahlback** [comment]
Ok, sounds good

**Comment by thofma** [comment]
Good to go?

**Comment by albinahlback** [comment]
There should be more deprecations I believe

**Comment by albinahlback** [comment]
This looks good

**Pull request merged**
