### PR TITLE
Ndigits

### PR DESCRIPTION
**Pull request by fieker**

### CODE REVIEW

**Comment by wbhart** [comment]
The new tests appear to fail.

**Comment by wbhart** [comment]
Still seems to be a failing test. Something to do with flog.

**Comment by wbhart** [comment]
This will be quite slow. I would use GMP's sizeinbase for 2 <= base <= 62. I'm sure it uses lookup tables and logarithms.

Outside that range one should probably approximate the answer with a very cheap bit computation, then refine it by comparing with powers of the base.

**Comment by fredrik-johansson** [comment]
Yeah, no reason to compute the number of digits exactly when a quick upper bound will do. I also wouldn't use slow repeated division to actually extract the digits.

**Comment by fieker** [comment]
On Thu, Jun 24, 2021 at 02:13:25AM -0700, Fredrik Johansson wrote:
> Yeah, no reason to compute the number of digits exactly when a quick upper bound will do. I also wouldn't use slow repeated division to actually extract the digits.
> 
the specs are: ndigits ist THE number of digits, if this is slow, use a
different function for an upper bound

feel free to get faster algorithms for the digits as well as for
ndigits. This is just copied from julia....

**Comment by fredrik-johansson** [comment]
I meant in digits(). Certainly ndigits() should return the exact number.

**Comment by fieker** [comment]
On Thu, Jun 24, 2021 at 02:35:42AM -0700, Fredrik Johansson wrote:
> I meant in digits(). Certainly ndigits() should return the exact number.
> 
Digits also has to, otherwise the array will be too long

**Comment by fredrik-johansson** [comment]
Well, you can overallocate and then resize the array.

Anyway, I guess it's not a big deal if digits() isn't super-optimized. I would at least make it subquadratic though (say by recursivy splitting in half if ndigits > 100).

**Comment by fredrik-johansson** [comment]
Sorry, misclicked!

**Comment by wbhart** [comment]
This looks ok to me.

**Comment by wbhart** [comment]
Modulo failing tests of course.

**Comment by wbhart** [comment]
I think some more tests are required to test all the new code. Codecov has posted some warnings at the relevant places on the "Files changed" page on the GitHub pull request.

**Comment by wbhart** [comment]
Well, codecov is happy, and I think you got the tests passing. So I will not review it again and just merge it when the final light goes green I think. :-)

**Comment by wbhart** [comment]
Success!!

**Pull request merged**
