### PR TITLE
Fix an aliasing bug and some incorrect results in fmpz powering.

### PR DESCRIPTION
**Pull request by wbhart**
Tests are taken from a PR of Rafael Fourquet and written by him.

### CODE REVIEW

**Comment by rfourquet** [comment]
Not that I'm too concerned about that, but you could as well have used my commits, to keep attribution. Actually I will update my PR.

**Comment by wbhart** [comment]
I didn't notice that the tests were done on a separate commit, sorry. But I did try to do something towards attribution by making a note in the commit message.

**Comment by rfourquet** [comment]
Oh I see, no problem, merge the PR you want.

**Comment by rfourquet** [comment]
> I didn't notice that the tests were done on a separate commit

Actually, it's possible with git to amend a commit and this keeps attribution to the original author (maybe the attribution is shared, I'm not sure). So for next time, you can either (depending on what is needed) squash the commits into one, and amend it, or keep the original commits and add one to the list. Actually, in this case, as I pushed into the main repo, you could have pushed to the original branch, this allows to not multiply the number of PRs (two PRs for the same thing can be useful when they solve the problem in different ways, but here it's just the same code (minus one commit) moved from one PR to the next). Also, I'm quite proficient with git so don't hesitate to ask me questions. Here, I'm not sure why you didn't wait that I update my PR, I might have had to make more clear that I was willing to amend it (It's a breeze for me to do that, it took me literally 1 min, so this might have saved you some time).

**Comment by wbhart** [comment]
Superceded.

**Pull request closed without merging**
