### PR TITLE
add valuation to fq_nmod_poly - and c-i-fy the nmod_poly one

### PR DESCRIPTION
**Pull request by fieker**

### CODE REVIEW

**Comment by wbhart** [comment]
Any chance the same function could be added to fq_poly, nmod_poly, fmpz_mod_poly (remove already exists in Flint) and in fmpz_poly, fmpq_poly (remove doesn't yet exist in Flint) and generic Poly.jl and MPoly.jl and a ticket opened to add remove to fmpz_mpoly in Flint and also add remove to the docs/src/polynomial.md documentation.

**Comment by fieker** [comment]
nmod_poly: done (old)
fq_nmod_poly: done
fq_poly: done
fmpq_poly 
fmpz_mod_poly

missing: GenPoly (not sure if thats a good idea if the coefficients are in a ring only), similar with MPoly.

Docs: all functions have a doc-string, currently.
BUT: there is a plan to soon (Friday?) go through the valuations again: split into two functions: remove returning the valuation and the left-over bit and valuation that just does the valuation.

This needs to be coordinated with Hecke, thus I am not doing this now...

**Comment by wbhart** [comment]
These functions should exist for Poly and MPoly. Of course they won't run if there aren't the appropriate divrem functions, but Julia will complain if they are missing.

**Comment by thofma** [comment]
Where should functions for polynomials of type `PolyElem{T}` go? generic/Poly.jl?

**Comment by wbhart** [comment]
At the moment univariate and multivariate polynomials are necessarily two different things. So the univariate generic implementation would have to go in Poly.jl and the multivariate one in MPoly.jl.

I plan to introduce a new MPolyElem abstract class, or something like that. We could use the existing PolyElem as a supertype of both UPolyElem and MPolyElem, say. But I didn't get around to making this change yet.

**Comment by thofma** [comment]
Don't merge yet.

**Comment by wbhart** [comment]
Can this PR be closed?

**Comment by wbhart** [comment]
Oh, I missed that it has been merged, sorry.

**Pull request merged**
