### PR TITLE
keep Nemo.GF separate from AbstractAlgebra.GF

### LINKED ISSUE #650: calling GF can make a GFField or GaloisField depending on the argument
```julia
julia> GF(3)
Galois field with characteristic 3

julia> typeof(ans)
Nemo.GaloisField

julia> GF(0x3)
Finite field F_3

julia> typeof(ans)
AbstractAlgebra.GFField{UInt8}
```

This is not necessarily a problem, but I think this should at least be documented, as this can be surprising. It's true that the docs mention only a `GF` constructor for `Int/UInt`, but it's easy to forget that and to end up creating a different type of object by using anothing integer type. 

Another possibility would be to have `Nemo.GF != AbstractAlgebra.GF`. If these functions remain unified, we can consider using `Nemo.GaloisField` for any integer types smaller than `Int/UInt`.

In any case, it would be great to document the difference in performance/behavior between AA's and Nemo's Galois fields.

Also, is it an option to consider depending the Primes package in `AbstractAlgebra` to check for primality for the argument of `GF`?

### PR DESCRIPTION
**Pull request by rfourquet**
Fix #650.

### CODE REVIEW

**Comment by thofma** [comment]
Looks fine to me. @wbhart?

**Comment by wbhart** [comment]
First see the comment I made on #650 

I really think @fieker gets to make the call here, as he seems to indicate he wants to use his veto.

**Comment by thofma** [comment]
To summarise for @fieker:

With this change, after `using Nemo` (or `using Hecke`), a call to `GF` will only give "flint" things and it will only work for `GF(::Int)` (giving the nmod things) and `GF(::fmpz)` (giving the fmpz_mod* things).

**Comment by fieker** [comment]
On Tue, Oct 08, 2019 at 11:57:33PM -0700, thofma wrote:
> To summarise for @fieker:
> 
> With this change, after `using Nemo` (or `using Hecke`), a call to `GF` will only give "flint" things and it will only work for `GF(::Int)` (giving the nmod things) and `GF(::fmpz)` (giving the fmpz_mod* things).
> 

Great! Thanks

Just to clarify Bill's comment about GF and FiniteField and my take on
things
  GF(p) == FiniteField(p)
  GF(p, k) == FiniteField(p, k)
  GF(p^k) I would never use, but could also be mapped to GF(p, k)

Minor twist:
  GF returns one argument
  FiniteField two

So Bill and I were chatting, and a compromise would be to have GF()
always only return one argument, while FiniteField will always give 2

If (and its a big if) (p or (p,k)) are in the Conway range, the second
argument should be a multiplicative generator (which is then trivial as
a root of the Conway poly is such a generator)
However, if you're outside Conway, you get a root, ie. an algebra
generator

Probably there also should be a FiniteField(poly) version which will use
my polynomial, and possibly other "standard" choices to be added later
(factors of cyclo, (Gaussian)-normal bases, ...)

I am NOT suggesting doing it now, but this was to clarify MY take on
GF/FiniteField (because I was annoyed about one only working for p and
the other one only for (p,k))

**Pull request merged**
