### PR TITLE
Bump antic version

### PR DESCRIPTION
**Pull request by thofma**
Let's see what appveyor is saying.

### CODE REVIEW

**Comment by wbhart** [comment]
I believe we are aware of the problem on OSX. The original author of this is trying to figure out how to fix it [1]. Unfortunately, neither he nor I understand Macs well enough to sort it out. Hopefully Isuru Fernando will have some insight.

[1] https://github.com/wbhart/flint2/pull/450#issuecomment-372136141

**Comment by thofma** [comment]
Arb is working, so why not antic? I did not change the flint version.

**Comment by thofma** [comment]
The failure is just a connection issue with github.

**Comment by thofma** [comment]
Don't merge. I need to add tests. Also I am not sure about the name `representation_mat_q` for the version that returns an fmpz_mat and an fmpz.

**Comment by thofma** [comment]
Ok, this is good to go.

**Pull request merged**
