### PR TITLE
Fix import of exp

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by wbhart** [comment]
This is not correct. You can't import exp from Base, because Nemo defines exp to always have a result in the same ring. See julia/Integer.jl.

This was done correctly and shouldn't be changed.

What bug were you trying to fix?

**Comment by thofma** [comment]
There are two competing exp definitions in Nemo:
```julia
julia> methods(Nemo.exp)
# 6 methods for generic function "exp":
exp(a::Nemo.fmpz_mod_rel_series) in Nemo at /home/thofmann/.julia/v0.6/Nemo/src/flint/fmpz_mod_rel_series.jl:576
exp(a::Nemo.nmod_rel_series) in Nemo at /home/thofmann/.julia/v0.6/Nemo/src/flint/nmod_rel_series.jl:621
exp(a::T) where T<:Nemo.RingElem in Nemo at /home/thofmann/.julia/v0.6/Nemo/src/Rings.jl:152
exp(a::T) where T<:Integer in Nemo at /home/thofmann/.julia/v0.6/Nemo/src/julia/Integer.jl:133
exp(a::Rational{T}) where T<:Integer in Nemo at /home/thofmann/.julia/v0.6/Nemo/src/julia/Rational.jl:126
exp(a::T) where T in Nemo at /home/thofmann/.julia/v0.6/Nemo/src/Nemo.jl:274

julia> methods(Base.exp)
# 20 methods for generic function "exp":
exp(a::Float16) in Base.Math at math.jl:950
exp(a::Complex{Float16}) in Base.Math at math.jl:951
exp(x::BigFloat) in Base.MPFR at mpfr.jl:517
exp(x::Nemo.arb) in Nemo at /home/thofmann/.julia/v0.6/Nemo/src/arb/arb.jl:1080
exp(x::Nemo.acb) in Nemo at /home/thofmann/.julia/v0.6/Nemo/src/arb/acb.jl:756
exp(a::Nemo.padic) in Nemo at /home/thofmann/.julia/v0.6/Nemo/src/flint/padic.jl:532
exp(a::Nemo.fmpq_rel_series) in Nemo at /home/thofmann/.julia/v0.6/Nemo/src/flint/fmpq_rel_series.jl:620
exp(a::Nemo.fmpq_abs_series) in Nemo at /home/thofmann/.julia/v0.6/Nemo/src/flint/fmpq_abs_series.jl:495
exp(x::Nemo.arb_mat) in Nemo at /home/thofmann/.julia/v0.6/Nemo/src/arb/arb_mat.jl:503
exp(x::Nemo.acb_mat) in Nemo at /home/thofmann/.julia/v0.6/Nemo/src/arb/acb_mat.jl:567
exp(z::Complex) in Base at complex.jl:502
exp(x::T) where T<:Union{Float32, Float64} in Base.Math at special/exp.jl:68
exp(x::AbstractFloat) in Base.Math at math.jl:274
exp(x::Real) in Base.Math at math.jl:243
exp(A::SparseMatrixCSC) in Base at deprecated.jl:56
exp(x::AbstractSparseArray{Tv,#s267,1} where #s267<:Integer) where Tv<:Number in Base.SparseArrays at sparse/sparsevector.jl:1054
exp(x::AbstractArray{T,N} where N) where T<:Number in Base at deprecated.jl:56
exp(a::Nemo.RelSeriesElem) in Nemo.Generic at /home/thofmann/.julia/v0.6/Nemo/src/generic/RelSeries.jl:944
exp(a::Nemo.AbsSeriesElem) in Nemo.Generic at /home/thofmann/.julia/v0.6/Nemo/src/generic/AbsSeries.jl:706
exp(a::Union{Nemo.Generic.LaurentSeriesFieldElem{T}, Nemo.Generic.LaurentSeriesRingElem{T}} where T<:Union{AbstractFloat, Integer, Nemo.RingElem, Rational}) in Nemo.Generic at /home/thofmann/.julia/v0.6/Nemo/src/generic/LaurentSeries.jl:969
```

**Comment by thofma** [comment]
Is this on purpose?

**Comment by wbhart** [comment]
Yes, it's on purpose. The definition used inside Nemo is not exported to
the user. It is there so that the power series code will work, regardless
of whatever definition is in Base.

**Comment by thofma** [comment]
Does not make any sense to me. Why is `exp(a::Nemo.nmod_rel_series)` defined for `Nemo.exp` and `exp(a::Nemo.fmpq_rel_series)` for `Base.exp`?

What I posted above was after `using Nemo`. Some of our methods are defined for `Nemo.exp` and some are defined for `Base.exp`.

**Comment by wbhart** [comment]
The first one seems incorrect. The nmod_rel_series type is one of ours, and
exp should be available to the user for this type, hence it should be
defined for Base.exp (you don't need to import exp from Base to do this).

The only exp's which should be defined for Nemo.exp are internal ones, e.g.
for Integer, Rational, AbstractFloat, etc. where we would have type piracy
otherwise.

**Comment by thofma** [comment]
Makes sense. I updated the PR.

(The conditional import of `isone` was appeared two times, so I removed one of them.)

**Pull request merged**
