### PR TITLE
Fix Win64 build and add appveyor support

### PR DESCRIPTION
**Pull request by thofma**
This should do it.

### CODE REVIEW

**Comment by thofma** [comment]
It now works @wbhart 

I had to remove the memory manager stuff since the dll's are too old. I had to use `@windows`. Using `!on_windows` it failed during precompilation with no specific error message.

On windows `run(ln ...)` does not work anymore. I tried to use `symlink`, but it needs permissions we not always have. So in case it fails I just copy libflint.dll to libflint-13.dll.

I disabled the the download of the mpir sources. For some reason this fails now and then on appveyor
with
```
LoadError: automatic download failed (error: 2148270085): http://mpir.org/mpir-2.7.2.tar.bz2
while loading C:\Users\appveyor\.julia\v0.4\Nemo\deps\build.jl, in expression starting on line 63
```
see https://ci.appveyor.com/project/thofma/nemo-jl-n5gdb/build/1.0.37

**Comment by wbhart** [comment]
Claus needs the memory manager stuff. I don't think you can remove it.

The fix is to rebuild the dlls again now that Flint has changed.

**Comment by thofma** [comment]
You also need to build pari with the patch.

**Comment by wbhart** [comment]
Yeah, is it going on my todo list then?

**Comment by wbhart** [comment]
Perhaps the best thing to do is open a ticket for it and whoever does it
first gets one internet point redeemable on any public forum.

**Comment by thofma** [comment]
I am happy to do it if you show me how to do it.

**Comment by wbhart** [comment]
I don't know how up-to-date this is, but here are some incomplete and
possibly inaccurate steps:

* some virus scanners will conflict with msys2. I had to
temporarily disable mine, otherwise it gave permission denied
errors.

* Follow instructions here:

   https://msys2.github.io/

Start the msys2 shell again, from the Start Menu

Be sure to select the correct threading and exception models.

* pacman -S wget gcc vim tar make texinfo git diffutils

* Install mingw-w64 and mingw-w32 (or whatever the current equivalent is)
and remember where you installed them (e.g. c:\mingw32 and c:\mingw64) --
don't recall where you get them from

* Probably need to edit your .bash_config or whatever file it is to put the
path to the correct gcc in your PATH

* Check you have gcc-5.2.0 or later with gcc -v (critical step)

* git clone https://github.com/wbhart/mpir mpir-2.7.2

* cd mpir-2.7.2

* ./configure --enable-gmpcompat --enable-shared --disable-static
LDFLAGS=-static-libgcc --build=core2-w64-mingw64

* make -j

* get mpfr-3.1.3 tarball, untar and change into directory

* ./configure LDFLAGS=-static-libgcc --enable-shared --disable-static
--with-gmp-build=/home/User/mpir-2.7.2

* make -j

* git clone antic repositoty into directory antic

* git clone flint2 repository into directory flint2 and change into
directory

* ./configure --enable-shared --disable-static
--with-mpir=/home/User/mpir-2.7.2 --with-mpfr=/home/User/mpfr-3.1.3
--extensions=../antic

* make -j

* git clone arb into arb directory

* ./configure --with-mpir=../mpir-2.7.2 --with-mpfr=../mpfr-3.1.3
--with-flint=../flint2 --enable-shared --disable-static

* edit arb Makefile, removing -ansi -pedantic and replacing it with -std=c99

* make

* I don't currently have instructions on building Pari 2.7.4, which is
quite difficult and requires some hackery. It begins with ./Configure
--with-gmp=....

* apply pari patch

* make

* some hackery (make the directory it is expecting to find and move the
file it is expecting to find)

* make

* rename all the dlls appropriately

* make them available somewhere (and ask me to put them on the nemocas
website)

We should write these instructions up somewhere in full so we don't keep
losing them.

Bill.

**Comment by wbhart** [comment]
Here are some more packages you will need with Pacman at step 3 above:

autoconf, bash, flex, sed

Bill.

**Comment by thofma** [comment]
Thanks, I will give it a try.

**Comment by wbhart** [comment]
Let me know if you need any help. I will probably have to help directly
with the Pari bit. It causes considerably more problems than the others,
and I don't recall all the hacks needed off the top of my head.

Some of them might be in my terminal log, I'm not sure.

**Comment by thofma** [comment]
I have built everything.

mpir, flint+antic: No problems.

arb: Tests failing (I think this is known).

pari: Could not get it to use my mpir build. And I think the tests are failing.

Nevertheless Nemo is running and the tests are passing. Unfortunately, using my libpari.dll yields:
```julia
julia> factor(ZZ(3)^50)
Dict{Nemo.fmpz,Int64} with 3 entries:
  835399                   => 1
  42460262440761727099629. => 1
  3                        => 1
```
I get the same wrong result with the libpari.dll on nemocas.org/binaries. Can you confirm this with your Nemo installation on Windows?

**Comment by thofma** [comment]
I tried it again with all the *.dlls from nemocas.org/binaries for w64. I still get the wrong result with the factorization.

Here is my setup:
```
julia> versioninfo()
Julia Version 0.4.3
Commit a2f713d (2016-01-12 21:37 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7 CPU         860  @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> Int
Int64
```

**Comment by wbhart** [comment]
This could well be a 64 bit Windows bug in Pari.

**Pull request closed without merging**
