### PR TITLE
Finite field sqrt

### PR DESCRIPTION
**Pull request by wbhart**
Note that this requires Flint-2.7 which will be released later this year, hence the breaking label. Tests will fail until then.

It also changes the actual finite field structs in line with Flint-2.7.

It adds sqrt and is_square.

### CODE REVIEW

**Comment by wbhart** [comment]
@thofma @tthsqe12 What do you want me to do here? Are you happy for it to raise an exception (which can be caught) if the Flint function fq_sqrt returns 0? As it is, the Nemo function returns the square root if it is a square, so we can't return a boolean unless you want me to return a tuple.

Of course, changing the (proposed exception) behaviour here would imply changing it throughout Nemo.

**Comment by thofma** [comment]
I am happy with `sqrt` throwing if flint returns 0.

Regarding is `issquare`, I would be happy to introduce the tuple variant (and help rolling it out in the rest of Nemo). As of https://github.com/JuliaLang/julia/pull/34126, tuples don't have the performance penalty that they used to have (they will be stack allocated).

**Comment by wbhart** [comment]
That sounds a bit inconvenient. Instead of:

```
if issquare(a)
   # blah blah blah
end
```

it becomes:

```
if issquare(a)[1]
    # blah blah blah
end
```

Are you sure you want that? Moreover, an extra object is created to store the sqrt, even if you don't need it!

**Comment by thofma** [comment]
I don't mind the `[1]` and the additional object. It is IMHO better then doing the work twice if one has `issquare(a)` followed by an `sqrt(a)`. Catching exceptions is just asking for trouble.

We have to do this unfortunately(?) quite often in Hecke. There are lots of function pairs like `issquare`/`sqrt`, e.g. `isprincipal`/`principal_generator` for ideals, where testing the attribute automatically computes the "proof" (I hope you know what I mean). So far we have not found a better way to solve this problem in julia.

**Comment by wbhart** [comment]
Well, if everyone agrees I guess we can do it. I don't like the [1] very much, but I imagine I could live with it.

What is the current mechanism for figuring out what everyone agrees? It seems meetings are only for status reporting.

Should I just tag a bunch of people here?

**Comment by wbhart** [comment]
If you want it, I suppose you could open a ticket first and see if there are any vocal complaints.

**Comment by tthsqe12** [comment]
I dont like the issquare()[1]. Nor is catching an exception particularly attractive. If both the property and the object that proves the property true are desired in one function call, how about a third function, issquare_and_sqrt? :)

**Comment by thofma** [comment]
I will open an issue somewhere and we can discuss it there.

**Pull request closed without merging**
