### PR TITLE
Add `fmma` and `fmms` binding for Flint

### PR DESCRIPTION
**Pull request by albinahlback**

### CODE REVIEW

**Comment by albinahlback** [comment]
Apparently I'm not good at copy-pasta.

**Comment by thofma** [comment]
Cool, thanks. Would you mind adding a docstring?

**Comment by albinahlback** [comment]
One sec

**Comment by albinahlback** [comment]
Now it should be fine (I was behind in some commits). I also chose to export them.

**Review by tthsqe12 — APPROVED** [review]

**Pull request merged**
